Repository wagtail/wagtail, pull requests merged in 2018-10, with the labels that each got.

#4805 Do not log user out when changing their own password
  CHANGELOG.txt
  docs/releases/2.3.rst
  wagtail/users/tests.py
  wagtail/users/views/users.py
Labels: type:Bug

#4812 Catch empty non-StreamValues in get_prep_value
  wagtail/core/blocks/stream_block.py
  wagtail/tests/testapp/migrations/0035_streamfieldmigrationmodels.py
  wagtail/tests/testapp/migrations/0036_streamfieldmigrationmodels_add_field.py
  wagtail/tests/testapp/models.py
Labels: Release blocker

#4804 Update hook examples to use django.templatetags.static
  docs/reference/hooks.rst
Labels: Documentation, status:Needs review

#4847 Make EmbedBlock tests work offline
  wagtail/embeds/tests.py
Labels: sprint:Minsk2018, status:Needs review, type:Bug

#4853 Document the Dockerfile in the project template
  docs/reference/project_template.rst
Labels: Documentation, sprint:Minsk2018, status:Needs review

#4855 fix help text positioning to avoid text cutting with narrow field
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.4.rst
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/admin/templates/wagtailadmin/edit_handlers/object_list.html
Labels: component:Frontend, sprint:Minsk2018

#4747 Allow custom logos of any height in the admin menu
  CHANGELOG.txt
  docs/releases/2.4.rst
  wagtail/admin/static_src/wagtailadmin/scss/components/_logo.scss
  wagtail/admin/static_src/wagtailadmin/scss/components/_main-nav.scss
Labels: component:Frontend, sprint:Minsk2018, type:Bug

#4866 Fix StreamField full-width layout, UI regression from #4855
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
Labels: component:Frontend, sprint:Minsk2018, type:Bug
