Repository wagtail/wagtail, pull requests merged in 2018-05, with the labels that each got.

#4509 Fix minor typo in modeladmin docs
  docs/reference/contrib/modeladmin/menu_item.rst
Labels: Documentation, component:Modeladmin, type:Cleanup/Optimisation

#4514 Fix regression in #3988 where no revision records exist - fixes #4505
  wagtail/admin/tests/test_pages_views.py
  wagtail/admin/views/pages.py
Labels: type:Bug

#4523 Update supported databases in docs
  docs/advanced_topics/performance.rst
Labels: Documentation

#4503 Adds another valid AudioBoom oEmbed pattern.
  wagtail/embeds/oembed_providers.py
Labels: component:Embeds, type:Enhancement

#4528 Add documentation for deploying with cloud storage
  docs/advanced_topics/deploying.rst
Labels: Documentation, status:Needs review
