Repository wagtail/wagtail, pull requests merged in 2018-08, with the labels that each got.

#4709 Security audit of npm packages
  package-lock.json
  package.json
Labels: component:Frontend, status:Needs review

#4730 Prevent AppRegistryNotReady error when wagtail.contrib.sitemaps is in INSTALLED_APPS
  wagtail/contrib/sitemaps/sitemap_generator.py
Labels: type:Bug

#4736 Simplify URL validator code on EmbedForm
  wagtail/embeds/forms.py
Labels: type:Cleanup/Optimisation

#4617 Remove old-skool font-support since woff and woff2 would be sufficient
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-bold.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-bolditalic.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-italic.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-light.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-lightitalic.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-regular.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-semibold.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/opensans-semibolditalic.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/robotoslab-bold.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/robotoslab-regular.ttf
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail.eot
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail.svg
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail.ttf
  wagtail/admin/static_src/wagtailadmin/scss/_font-icons.scss
  wagtail/admin/static_src/wagtailadmin/scss/_fonts.scss
  wagtail/admin/static_src/wagtailadmin/scss/_mixins.scss
Labels: component:Frontend, status:Needs review, type:Cleanup/Optimisation
