Repository wagtail/wagtail, pull requests merged in 2018-04, with the labels that each got.

#4375 Added change email functionality from the account settings
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.1.rst
  wagtail/admin/templates/wagtailadmin/account/change_email.html
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/urls/__init__.py
  wagtail/admin/views/account.py
  wagtail/admin/wagtail_hooks.py
  wagtail/users/forms.py
Labels: component:Frontend, sprint:Arnhem2018, type:Enhancement

#4382 Add request to Edit Handler
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.1.rst
  wagtail/admin/edit_handlers.py
  wagtail/admin/tests/test_edit_handlers.py
  wagtail/admin/views/pages.py
  wagtail/contrib/forms/tests/test_views.py
  wagtail/contrib/modeladmin/views.py
  wagtail/contrib/settings/views.py
  wagtail/snippets/tests.py
  wagtail/snippets/views/snippets.py
Labels: sprint:Arnhem2018, type:Enhancement

#4385 2844 image chooser block default title
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.1.rst
  wagtail/images/templates/wagtailimages/chooser/chooser.js
Labels: component:Images, sprint:Arnhem2018, status:Needs review

#4381 Add icon template tag with accessibility options (PoC)
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.1.rst
  wagtail/admin/templates/wagtailadmin/shared/icon.html
  wagtail/admin/templates/wagtailadmin/shared/wagtail_icon.html
  wagtail/admin/templatetags/wagtailui_tags.py
Labels: Accessibility, sprint:Arnhem2018, status:Needs review

#4390 Improve Domain Selection for Multiple Sites
  CONTRIBUTORS.rst
  wagtail/core/models.py
  wagtail/core/tests/test_page_model.py
Labels: sprint:Arnhem2018, status:Needs review

#4467 Expose reusable client-side code to build Draftail extensions
  CHANGELOG.txt
  client/src/components/Draftail/index.js
  client/src/components/Draftail/index.test.js
  client/src/index.js
  client/src/index.test.js
  client/tests/stubs.js
  docs/advanced_topics/customisation/admin_templates.rst
  docs/advanced_topics/customisation/extending_draftail.rst
  docs/releases/2.1.rst
  wagtail/admin/static_src/wagtailadmin/app/draftail.entry.js
  wagtail/admin/static_src/wagtailadmin/app/draftail.entry.test.js
  wagtail/admin/static_src/wagtailadmin/app/wagtailadmin.entry.js
  wagtail/admin/static_src/wagtailadmin/app/wagtailadmin.entry.test.js
Labels: component:Rich text, type:Enhancement

#4228 Add a meaningful error message for invalid arguments to pageurl
  wagtail/core/templatetags/wagtailcore_tags.py
  wagtail/core/tests/tests.py
Labels: status:Needs review, type:Cleanup/Optimisation
