Repository wagtail/wagtail, pull requests merged in 2019-05, with the labels that each got.

#5233 Clarify: extra fields can be indexed by PostgreSQL backend
  docs/topics/search/indexing.rst
Labels: Documentation, component:Search

#5295 Small wording revision
  docs/reference/contrib/modeladmin/primer.rst
Labels: Documentation

#5179 Clear pending AJAX request if error occurs on page chooser
  wagtail/admin/static_src/wagtailadmin/js/page-chooser-modal.js
Labels: component:Frontend, status:Needs review, type:Bug
