Repository wagtail/wagtail, pull requests merged in 2019-08, with the labels that each got.

#5474 Make image fallback work for images with big/small aspect ratios
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/src/components/Draftail/blocks/MediaBlock.scss
  docs/releases/2.7.rst
Labels: component:Frontend, component:Rich text, type:Bug

#5479 Apply escaping to JS translation strings.
  wagtail/admin/templates/wagtailadmin/admin_base.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/utils.py
Labels: Release blocker, status:Needs review

#5483 Clarify CHANGELOG instructions in "Committing code" docs
  docs/contributing/committing.rst
Labels: Documentation, type:Cleanup/Optimisation

#5463 Add labels to snippet checkboxes for accessibility (#5328)
  CHANGELOG.txt
  docs/releases/2.7.rst
  wagtail/snippets/templates/wagtailsnippets/snippets/list.html
Labels: Accessibility, component:Frontend, sprint:Philly2019

#5487 Add python 3.8-dev to Travis CI as an allowed failure
  .travis.yml
  tox.ini
Labels: type:Cleanup/Optimisation

#5446 Add caption field to Table Block module
  docs/_static/images/screen40_table_block.png
  docs/reference/contrib/table_block.rst
  wagtail/contrib/table_block/blocks.py
  wagtail/contrib/table_block/static/table_block/js/table.js
  wagtail/contrib/table_block/templates/table_block/blocks/table.html
  wagtail/contrib/table_block/templates/table_block/widgets/table.html
  wagtail/contrib/table_block/tests.py
Labels: Accessibility, component:Streamfield, sprint:Philly2019, status:Needs work, type:Enhancement
