Repository wagtail/wagtail, pull requests merged in 2019-10, with the labels that each got.

#5594 Added multiple issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  CONTRIBUTORS.rst
Labels: type:Cleanup/Optimisation

#5621 Recommend signals rather than hooks for model-level customisations
  docs/reference/hooks.rst
Labels: Documentation, status:Needs review

#5625 Fix regression in elasticsearch5 tests
  wagtail/search/backends/elasticsearch7.py
Labels: Release blocker, component:Search

#5622 Add squash.io to thanks section in readme
  .github/squash-logo.svg
  README.md
Labels: Documentation, status:Needs review

#5584 Add documentation for how to use alternative image tags
  docs/topics/images.rst
Labels: Documentation, component:Images, status:Needs review

#5630 Rename wagtail/admin/locale.py to localization.py
  docs/releases/2.7.rst
  wagtail/admin/localization.py
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/utils.py
  wagtail/admin/wagtail_hooks.py
  wagtail/users/forms.py
Labels: Release blocker, type:Cleanup/Optimisation

#5647 Formalise Python 3.8 support (take 2)
  .travis.yml
  README.md
  docs/getting_started/tutorial.rst
  docs/releases/upgrading.rst
  setup.py
Labels: type:Cleanup/Optimisation

#5644 Avoid calling versioned_static from static form media definitions
  wagtail/admin/rich_text/editors/hallo.py
  wagtail/admin/tests/test_widgets.py
  wagtail/admin/widgets.py
  wagtail/contrib/settings/forms.py
  wagtail/documents/widgets.py
  wagtail/images/widgets.py
  wagtail/snippets/widgets.py
  wagtail/tests/testapp/forms.py
Labels: Release blocker, status:Needs review, type:Bug
