Repository wagtail/wagtail, pull requests merged in 2019-07, with the labels that each got.

#5403 Document the workaround for broken wagtailimages.Filter references in custom image migrations
  docs/releases/2.4.rst
Labels: Documentation, component:Images, status:Needs review, type:Bug

#5441 Pin Squash docker image to a specific version
  .squash.yml
Labels: type:Cleanup/Optimisation

#5447 Fix broken pipenv/docutils dependency on CircleCI
  setup.py
Labels: type:Cleanup/Optimisation

#5440 Fix the required styles on title fields
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
Labels: Release blocker, component:Frontend, sprint:Philly2019, type:Bug

#5462 use lighter grey for streamfield group label for accessible contrast
  CHANGELOG.txt
  client/scss/components/_streamfield.scss
  docs/releases/2.7.rst
Labels: Accessibility, component:Frontend, component:Streamfield, type:Bug

#5456 Pass down process_child_object when copying pages recursively
  wagtail/core/models.py
  wagtail/core/tests/test_page_model.py
Labels: Release blocker, type:Bug

#5470 Fix jcrop holder image having no alt tag. Fix part of #5309
  wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js
Labels: Accessibility, component:Frontend, component:Images, sprint:Philly2019, type:Bug
