Repository wagtail/wagtail, pull requests merged in 2019-06, with the labels that each got.

#5305 Update squash user details to be more portable
  .squash.yml
Labels: type:Cleanup/Optimisation

#5349 Add a "Dashboard" label for logo link in the main nav for screen reader users
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.txt
  docs/releases/2.6.rst
  wagtail/admin/templates/wagtailadmin/base.html
Labels: Accessibility, component:Frontend, type:Bug

#5354 #5327 remove menu markup from dropdowns
  CHANGELOG.txt
  docs/releases/2.6.rst
  wagtail/admin/templates/wagtailadmin/pages/action_menu/menu.html
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_button_with_dropdown.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_pagination.html
  wagtail/admin/templates/wagtailadmin/pages/search_results.html
  wagtail/admin/templates/wagtailadmin/shared/ajax_pagination_nav.html
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb.html
  wagtail/admin/templates/wagtailadmin/shared/main_nav.html
  wagtail/admin/templates/wagtailadmin/shared/pagination_nav.html
  wagtail/admin/templates/wagtailadmin/shared/search_other.html
  wagtail/contrib/modeladmin/templates/modeladmin/edit.html
  wagtail/contrib/modeladmin/templates/modeladmin/index.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/snippets/templates/wagtailsnippets/snippets/edit.html
Labels: Accessibility, component:Frontend, type:Bug

#5359 Change icon font implementation to be screen-reader friendly (#1224)
  client/scss/components/_breadcrumb.scss
  client/scss/components/_chooser.scss
  client/scss/components/_forms.scss
  client/scss/components/_help-block.scss
  client/scss/components/_icons.scss
  client/scss/components/_loading-mask.scss
  client/scss/components/_main-nav.scss
  client/scss/components/_messages.scss
  client/scss/components/_streamfield.scss
  client/scss/components/_tabs.scss
  client/scss/components/_tag.scss
  client/scss/elements/_forms.scss
  client/scss/overrides/_vendor.datetimepicker.scss
  client/scss/overrides/_vendor.tagit.scss
  client/scss/settings/_variables.icons.scss
  docs/contributing/css_guidelines.rst
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail-icomoon.json
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail.woff
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/documents/static_src/wagtaildocs/js/hallo-plugins/hallo-wagtaildoclink.js
  wagtail/images/static_src/wagtailimages/js/hallo-plugins/hallo-wagtailimage.js
Labels: Accessibility, component:Frontend, type:Bug

#5377 Adds clearer text to the close button for modals
  CHANGELOG.txt
  client/tests/stubs.js
  docs/releases/2.6.rst
  wagtail/admin/static_src/wagtailadmin/js/modal-workflow.js
  wagtail/admin/templates/wagtailadmin/admin_base.html
Labels: Accessibility, component:Frontend, type:Bug

#5382 Ensure the 'add child page' icon displays when focused
  CHANGELOG.txt
  client/scss/components/_listing.scss
  docs/releases/2.6.rst
Labels: Accessibility, component:Frontend, type:Bug

#5383 Fixed Remove tab order customisations in CMS admin #5351
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/src/components/Explorer/PageCount.js
  client/src/components/Explorer/__snapshots__/PageCount.test.js.snap
  docs/advanced_topics/customisation/admin_templates.rst
  docs/releases/2.6.rst
  package-lock.json
  wagtail/admin/forms/auth.py
  wagtail/admin/templates/wagtailadmin/login.html
  wagtail/admin/templates/wagtailadmin/pages/action_menu/publish.html
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/contrib/modeladmin/templates/modeladmin/create.html
  wagtail/contrib/modeladmin/templates/modeladmin/edit.html
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
  wagtail/snippets/templates/wagtailsnippets/snippets/create.html
  wagtail/snippets/templates/wagtailsnippets/snippets/edit.html
Labels: Accessibility, component:Frontend, type:Bug

#5378 Fix help-inverse icon regression introduced by icon refactorings in #5359
  client/scss/components/_icons.scss
  client/scss/settings/_variables.icons.scss
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: component:Frontend, type:Bug

#5395 5329 permissions checkbox labels
  CHANGELOG.txt
  docs/releases/2.6.rst
  wagtail/admin/forms/collections.py
  wagtail/admin/templates/wagtailadmin/permissions/includes/collection_member_permissions_form.html
  wagtail/admin/templates/wagtailadmin/shared/field.html
  wagtail/users/static_src/wagtailusers/scss/groups_edit.scss
  wagtail/users/templates/wagtailusers/groups/edit.html
  wagtail/users/templates/wagtailusers/groups/includes/formatted_permissions.html
  wagtail/users/templates/wagtailusers/groups/includes/page_permissions_form.html
Labels: Accessibility, component:Frontend, type:Bug

#5398 Re-add loading of Wagtail icon font for userbar. Fix #5397
  wagtail/admin/static_src/wagtailadmin/scss/userbar.scss
Labels: component:Frontend, type:Bug

#5254 Refactor submenu JS to remove jquery dep and move to wagtail-client
  client/src/includes/initSubmenus.js
  client/src/index.js
  wagtail/admin/menu.py
  wagtail/admin/static_src/wagtailadmin/app/wagtailadmin.entry.js
  wagtail/admin/static_src/wagtailadmin/js/submenu.js
  wagtail/admin/templates/wagtailadmin/base.html
  wagtail/admin/templates/wagtailadmin/shared/menu_submenu_item.html
Labels: component:Frontend, type:Cleanup/Optimisation

#5386 Add more contextual information for screen readers in the explorer menu
  CHANGELOG.txt
  client/src/components/Explorer/ExplorerItem.js
  client/src/components/Explorer/__snapshots__/ExplorerItem.test.js.snap
  client/tests/stubs.js
  docs/releases/2.6.rst
  wagtail/admin/templates/wagtailadmin/admin_base.html
Labels: Accessibility, component:Frontend, type:Enhancement

#5402 Add dedicated accessibility section to v2.6 release notes
  docs/releases/2.6.rst
Labels: Accessibility, type:Cleanup/Optimisation

#5380 Improve voiceover experience for links on the page listing
  CHANGELOG.txt
  docs/releases/2.6.rst
  wagtail/admin/templates/wagtailadmin/pages/listing/_button_with_dropdown.html
  wagtail/admin/wagtail_hooks.py
Labels: Accessibility, component:Frontend, type:Enhancement

#5394 5336 focus move to pages explorer when open
  CHANGELOG.txt
  client/src/components/Button/Button.js
  client/src/components/Button/Button.test.js
  client/src/components/Button/__snapshots__/Button.test.js.snap
  client/src/components/Explorer/ExplorerPanel.js
  client/src/components/Explorer/ExplorerToggle.js
  client/src/components/Explorer/__snapshots__/ExplorerHeader.test.js.snap
  client/src/components/Explorer/__snapshots__/ExplorerItem.test.js.snap
  client/src/components/Explorer/__snapshots__/ExplorerPanel.test.js.snap
  client/src/components/Explorer/__snapshots__/ExplorerToggle.test.js.snap
  client/src/components/Transition/Transition.js
  client/src/components/Transition/Transition.test.js
  client/src/components/Transition/__snapshots__/Transition.test.js.snap
  client/tests/stubs.js
  docs/releases/2.6.rst
  wagtail/admin/templates/wagtailadmin/admin_base.html
Labels: Accessibility, component:Frontend, type:Bug

#5372 5274 voice over fixes
  CHANGELOG.txt
  docs/releases/2.6.rst
  wagtail/admin/site_summary.py
  wagtail/admin/static_src/wagtailadmin/js/privacy-switch.js
  wagtail/admin/templates/wagtailadmin/collections/_privacy_switch.html
  wagtail/admin/templates/wagtailadmin/home/site_summary_pages.html
  wagtail/admin/templates/wagtailadmin/pages/_lock_switch.html
  wagtail/admin/templates/wagtailadmin/pages/_privacy_switch.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_table_headers_explore.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_pages_views.py
  wagtail/admin/utils.py
  wagtail/admin/views/home.py
  wagtail/documents/templates/wagtaildocs/homepage/site_summary_documents.html
  wagtail/documents/wagtail_hooks.py
  wagtail/images/templates/wagtailimages/homepage/site_summary_images.html
  wagtail/images/wagtail_hooks.py
Labels: Accessibility, component:Frontend, type:Enhancement
