Repository wagtail/wagtail, pull requests merged in 2019-04, with the labels that each got.

#5198 Bump django-taggit to 0.24
  setup.py
Labels: type:Cleanup/Optimisation

#5159 Support additional custom handler for links in Rich text editor.
  CHANGELOG.txt
  docs/advanced_topics/customisation/rich_text_internals.rst
  docs/releases/2.5.rst
  wagtail/core/rich_text/rewriters.py
  wagtail/core/tests/test_rich_text.py
Labels: component:Rich text, sprint:Arnhem2019, type:Enhancement

#5190 Add consistent whitespace around sortable table headings
  CHANGELOG.txt
  docs/releases/2.5.rst
  wagtail/admin/templates/wagtailadmin/pages/revisions/list.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/sites/templates/wagtailsites/index.html
  wagtail/users/templates/wagtailusers/users/list.html
Labels: component:Frontend, type:Bug

#5147 Reuse the label_for_field function for fields in the InspectView
  wagtail/contrib/modeladmin/tests/test_page_modeladmin.py
  wagtail/contrib/modeladmin/views.py
  wagtail/tests/modeladmintest/models.py
  wagtail/tests/modeladmintest/wagtail_hooks.py
Labels: sprint:Arnhem2019

#5221 Fix hooks documentation typo
  docs/reference/hooks.rst
Labels: Documentation

#5217 Remove Python 3.4 compatibility hacks from WagtailTestUtils
  wagtail/tests/utils/assert_logs.py
  wagtail/tests/utils/wagtail_tests.py
Labels: type:Cleanup/Optimisation

#5211 Grammar fixes
  docs/reference/contrib/postgres_search.rst
Labels: Documentation

#5231 Fix Redux DevTools deprecation warning
  .eslintrc
  CONTRIBUTORS.rst
  client/src/components/Explorer/index.js
Labels: good first issue, type:Cleanup/Optimisation

#5236 Add color-white to wagtail-version so it's visible
  CHANGELOG.txt
  client/scss/components/_main-nav.scss
  docs/releases/2.6.rst
Labels: component:Frontend, good first issue, type:Bug

#5253 Fix typo in rewrite handlers example code
  docs/advanced_topics/customisation/rich_text_internals.rst
Labels: Documentation, component:Rich text
