Repository wagtail/wagtail, pull requests merged in 2020-01, with the labels that each got.

#5756 Add test case for tag field inside InlinePanel
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/tests/testapp/migrations/0046_personpage.py
  wagtail/tests/testapp/models.py
Labels: type:Bug

#5694 Move all usage of versioned_static to media methods
  wagtail/admin/rich_text/editors/draftail/__init__.py
  wagtail/admin/rich_text/editors/draftail/features.py
  wagtail/admin/rich_text/editors/hallo.py
  wagtail/admin/staticfiles.py
  wagtail/admin/tests/test_rich_text.py
  wagtail/admin/tests/test_templatetags.py
  wagtail/admin/wagtail_hooks.py
  wagtail/documents/wagtail_hooks.py
  wagtail/embeds/wagtail_hooks.py
  wagtail/images/wagtail_hooks.py
Labels: component:Frontend cache, status:Needs Work, type:Bug

#5746 Add an empty block area on the search results listing.
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_explore.html
Labels: component:Search, status:Needs Review

#5777 Add alert role to search results
  wagtail/admin/templates/wagtailadmin/chooser/_search_results.html
  wagtail/admin/templates/wagtailadmin/pages/search_results.html
  wagtail/contrib/redirects/templates/wagtailredirects/results.html
  wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/results.html
  wagtail/documents/templates/wagtaildocs/chooser/results.html
  wagtail/documents/templates/wagtaildocs/documents/results.html
  wagtail/images/templates/wagtailimages/chooser/results.html
  wagtail/images/templates/wagtailimages/images/results.html
  wagtail/snippets/templates/wagtailsnippets/chooser/results.html
  wagtail/snippets/templates/wagtailsnippets/snippets/results.html
  wagtail/users/templates/wagtailusers/groups/results.html
  wagtail/users/templates/wagtailusers/users/results.html
Labels: Accessibility, sprint:Bristol2020, status:Needs Review

#5775 Reorder elements in the order form
  wagtail/admin/static_src/wagtailadmin/scss/layouts/login.scss
  wagtail/admin/templates/wagtailadmin/login.html
Labels: Accessibility, component:Frontend, sprint:Bristol2020

#5773 Show 'Close Explorer' button on mobile viewports
  client/src/components/Explorer/Explorer.scss
  client/src/components/Explorer/ExplorerPanel.js
  client/src/components/Explorer/__snapshots__/ExplorerPanel.test.js.snap
Labels: Accessibility, component:Frontend, sprint:Bristol2020, status:Needs Review

#5784 Add aria label for password reset
  wagtail/admin/templates/wagtailadmin/login.html
Labels: Accessibility, component:Frontend, sprint:Bristol2020, type:Bug

#5740 Update rich text toolbar styles
  CHANGELOG.txt
  client/src/components/Draftail/Draftail.scss
  docs/releases/2.9.rst
Labels: component:Frontend, component:Rich text, type:Enhancement
