Repository wagtail/wagtail, pull requests merged in 2020-07, with the labels that each got.

#6202 move import of Site to avoid error when wagtail.contrib.sitemaps is in INSTALLED_APPS
  wagtail/contrib/sitemaps/sitemap_generator.py
Labels: type:Bug

#6200 [Workflow] Add task description in choosers
  docs/advanced_topics/custom_tasks.rst
  wagtail/admin/templates/wagtailadmin/workflows/select_task_type.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/select_task_type.html
  wagtail/admin/tests/test_workflows.py
  wagtail/admin/views/workflows.py
  wagtail/core/models.py
Labels: component:Workflow

#6201 [Workflow] Update home dashboard styles
  wagtail/admin/static_src/wagtailadmin/js/lock-unlock-action.js
  wagtail/admin/static_src/wagtailadmin/scss/layouts/home.scss
  wagtail/admin/templates/wagtailadmin/home.html
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
  wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html
  wagtail/admin/templates/wagtailadmin/home/recent_edits.html
  wagtail/admin/templates/wagtailadmin/home/user_pages_in_workflow_moderation.html
  wagtail/admin/templates/wagtailadmin/home/workflow_pages_to_moderate.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/workflows/includes/workflow_tasks_with_status.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
  wagtail/admin/views/home.py
Labels: component:Workflow

#6217 Expand Pillow dependency to include 7.x
  setup.py
Labels: component:Security, type:Cleanup/Optimisation

#6227 Add duplicate icon from wagtail-react-streamfield
  client/scss/settings/_variables.icons.scss
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail-icomoon.json
  wagtail/admin/static_src/wagtailadmin/fonts/wagtail.woff
  wagtail/admin/templates/wagtailadmin/icons/duplicate.svg
  wagtail/admin/wagtail_hooks.py
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: component:Streamfield

#6155 Sanitise window.location.hash when passing to jquery for tab handling
  CHANGELOG.txt
  docs/releases/2.10.rst
  wagtail/admin/static_src/wagtailadmin/js/core.js
Labels: component:Security, status:Needs Review, type:Cleanup/Optimisation

#6238 Use % formatting for new workflow / audit log translation strings
  docs/reference/hooks.rst
  wagtail/admin/action_menu.py
  wagtail/admin/wagtail_hooks.py
Labels: component:Workflow

#6239 Fix sphinx warnings from workflow / audit log documentation
  docs/reference/pages/model_reference.rst
Labels: Documentation, component:Workflow

#6246 Use icon tag instead of CSS for lock/unlock messages
  client/scss/components/_messages.scss
  wagtail/admin/templates/wagtailadmin/base.html
Labels: component:Frontend, type:Bug

#6247 Shorten and de-capitalise default workflow/task name
  wagtail/core/migrations/0048_add_default_workflows.py
Labels: component:Workflow

#6248 Apply permission check on workflow tasks menu item
  wagtail/admin/wagtail_hooks.py
Labels: component:Workflow

#5780 Add basic skiplink
  CHANGELOG.txt
  client/scss/components/_skiplink.scss
  client/scss/settings/_variables.scss
  client/scss/styles.scss
  client/src/includes/initSkipLink.js
  client/src/index.js
  docs/releases/2.10.rst
  wagtail/admin/static_src/wagtailadmin/app/wagtailadmin.entry.js
  wagtail/admin/static_src/wagtailadmin/js/core.js
  wagtail/admin/templates/wagtailadmin/base.html
  wagtail/admin/templates/wagtailadmin/skeleton.html
Labels: Accessibility, component:Frontend, sprint:Bristol2020

#6242 Add chevron to dropdowns that are missing them
  CHANGELOG.txt
  client/scss/components/_forms.scss
  docs/releases/2.10.rst
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
  wagtail/documents/templates/wagtaildocs/multiple/add.html
  wagtail/images/templates/wagtailimages/multiple/add.html
Labels: Accessibility, type:Bug

#6116 Hide inactive delete button with .u-hidden instead of .visuallyhidden
  CHANGELOG.txt
  docs/releases/2.10.rst
  wagtail/snippets/static_src/wagtailsnippets/js/snippet-multiple-select.js
  wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html
Labels: Accessibility, component:Snippets

#6115 Remove visible focus states from .visiblyhidden util
  CHANGELOG.txt
  client/scss/tools/_mixins.general.scss
  docs/releases/2.10.rst
Labels: Accessibility, status:Needs Review

#6251 Fix site delete URL
  wagtail/admin/viewsets/model.py
Labels: Release blocker, type:Bug

#6249 Always publish the latest version of a page on workflow completion
  wagtail/core/workflows.py
Labels: component:Workflow

#5885 Add edit button to draftail images and embeds blocks tooltip
  client/src/components/Draftail/blocks/EmbedBlock.js
  client/src/components/Draftail/blocks/EmbedBlock.test.js
  client/src/components/Draftail/blocks/ImageBlock.js
  client/src/components/Draftail/blocks/ImageBlock.test.js
  client/src/components/Draftail/blocks/MediaBlock.js
  client/src/components/Draftail/blocks/MediaBlock.test.js
  client/src/components/Draftail/blocks/__snapshots__/EmbedBlock.test.js.snap
  client/src/components/Draftail/blocks/__snapshots__/ImageBlock.test.js.snap
  client/src/components/Draftail/blocks/__snapshots__/MediaBlock.test.js.snap
  client/src/components/Draftail/sources/ModalWorkflowSource.js
  client/src/components/Draftail/sources/ModalWorkflowSource.test.js
  client/tests/stubs.js
  wagtail/admin/localization.py
Labels: component:Rich text, type:Enhancement

#6269 Add before_{create,edit,delete}_snippet hooks
  CHANGELOG.txt
  docs/reference/hooks.rst
  docs/releases/2.11.rst
  wagtail/snippets/tests.py
  wagtail/snippets/views/snippets.py
Labels: component:Snippets, type:Enhancement

#6266 Fix docs for `construct_page_listing_buttons`
  docs/reference/hooks.rst
Labels: Documentation

#6275 Move SpreadsheetExportMixin to wagtail.admin.views.mixins
  wagtail/admin/views/mixins.py
  wagtail/admin/views/reports.py
  wagtail/contrib/forms/views.py
  wagtail/contrib/modeladmin/views.py
  wagtail/tests/testapp/models.py
Labels: type:Bug
