Repository wagtail/wagtail, pull requests merged in 2020-08, with the labels that each got.

#6280 Adds :focus-within .actions for page listings
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/scss/components/_listing.scss
  docs/contributing/developing.rst
  docs/releases/2.11.rst
Labels: Accessibility, component:Frontend, sprint:WagtailSpaceUS2020, type:Bug

#6276 Fix appconf for wagtail.tests.modeladmintest
  wagtail/tests/modeladmintest/__init__.py
  wagtail/tests/modeladmintest/apps.py
Labels: type:Cleanup/Optimisation

#6284 Version command
  wagtail/bin/wagtail.py
Labels: status:Needs Review

#6287 Fix misapplied format strings inside gettext
  wagtail/admin/forms/pages.py
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/views/pages.py
  wagtail/admin/views/workflows.py
  wagtail/contrib/forms/forms.py
Labels: type:Cleanup/Optimisation

#6286 Cache the SVG icon HTML fragment
  wagtail/admin/templatetags/wagtailadmin_tags.py
Labels: type:Cleanup/Optimisation

#6290 Fix WAGTAILFRONTENDCACHE_LANGUAGES
  wagtail/contrib/frontend_cache/tests.py
  wagtail/contrib/frontend_cache/utils.py
Labels: type:Bug

#6303 Add missing translation for workflow
  wagtail/admin/templates/wagtailadmin/reports/workflow_tasks.html
Labels: component:Workflow

#6315 Fix all `E303: Too many blank lines` Flake8 errors
  setup.cfg
  wagtail/admin/mail.py
  wagtail/admin/tests/api/test_pages.py
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/pages/test_moderation.py
  wagtail/admin/tests/pages/test_move_page.py
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/tests/test_compare.py
  wagtail/admin/tests/test_edit_handlers.py
  wagtail/admin/tests/test_rich_text.py
  wagtail/admin/tests/test_widgets.py
  wagtail/admin/tests/test_workflows.py
  wagtail/contrib/forms/models.py
  wagtail/contrib/forms/tests/test_models.py
  wagtail/contrib/forms/tests/test_views.py
  wagtail/contrib/forms/tests/utils.py
  wagtail/contrib/modeladmin/helpers/search.py
  wagtail/contrib/modeladmin/tests/test_simple_modeladmin.py
  wagtail/contrib/modeladmin/views.py
  wagtail/contrib/postgres_search/tests/test_stemming.py
  wagtail/contrib/routable_page/tests.py
  wagtail/contrib/sitemaps/tests.py
  wagtail/contrib/table_block/tests.py
  wagtail/core/migrations/0048_add_default_workflows.py
  wagtail/core/tests/test_blocks.py
  wagtail/core/tests/test_management_commands.py
  wagtail/core/tests/test_page_model.py
  wagtail/core/tests/test_rich_text.py
  wagtail/documents/views/documents.py
  wagtail/images/models.py
  wagtail/images/tests/test_admin_views.py
  wagtail/images/tests/test_image_operations.py
  wagtail/images/tests/tests.py
  wagtail/tests/testapp/migrations/0034_advertwithuuidcustomprimarykey.py
  wagtail/users/views/groups.py
Labels: type:Cleanup/Optimisation

#6331 Avoid setting self.content_type on page CreateView / EditView
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/views/pages/create.py
  wagtail/admin/views/pages/edit.py
Labels: type:Bug

#6350 [doc] Deploying on Google Cloud
  docs/advanced_topics/deploying.rst
Labels: Documentation

#6361 Update responsive embeds docs
  docs/topics/writing_templates.rst
Labels: Documentation, component:Embeds, status:Needs Review
