Repository wagtail/wagtail, pull requests merged in 2020-12, with the labels that each got.

#6597 fix: breadcrumb margin overlapping burger menu
  CHANGELOG.txt
  docs/releases/2.12.rst
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
Labels: component:Frontend, status:Needs Review, type:Bug

#6529 added collection_id param to setPage in document-chooser-modal.js
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.12.rst
  wagtail/documents/static_src/wagtaildocs/js/document-chooser-modal.js
Labels: type:Bug

#6530 Feature/field comment frontend
  client/package-lock.json
  client/src/components/CommentApp/comments.js
  client/tests/stubs.js
  client/webpack.config.js
  package-lock.json
  package.json
  wagtail/admin/localization.py
  wagtail/admin/static_src/wagtailadmin/app/comments.entry.js
  wagtail/admin/static_src/wagtailadmin/app/comments.entry.test.js
  wagtail/admin/static_src/wagtailadmin/js/blocks/sequence.js
  wagtail/admin/static_src/wagtailadmin/js/page-chooser.js
  wagtail/admin/static_src/wagtailadmin/js/vendor/uuidv4.min.js
  wagtail/admin/templates/wagtailadmin/block_forms/field.html
  wagtail/admin/templates/wagtailadmin/block_forms/sequence_member.html
  wagtail/admin/templates/wagtailadmin/block_forms/stream_member.html
  wagtail/admin/templates/wagtailadmin/edit_handlers/inline_panel_child.html
  wagtail/admin/templates/wagtailadmin/icons/comment.svg
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/shared/field.html
  wagtail/admin/templates/wagtailadmin/widgets/chooser.html
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/views/pages/edit.py
  wagtail/admin/wagtail_hooks.py
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/contrib/table_block/tests.py
  wagtail/core/blocks/stream_block.py
  wagtail/core/tests/test_blocks.py
  wagtail/images/static_src/wagtailimages/js/image-chooser.js
  wagtail/snippets/static_src/wagtailsnippets/js/snippet-chooser.js
  wagtail/snippets/tests.py
Labels: status:Needs Work, type:Enhancement

#6573 Update pagination icons to use SVGs
  CHANGELOG.txt
  docs/releases/2.12.rst
  wagtail/admin/templates/wagtailadmin/pages/listing/_pagination.html
  wagtail/admin/templates/wagtailadmin/shared/ajax_pagination_nav.html
  wagtail/admin/templates/wagtailadmin/shared/pagination_nav.html
  wagtail/contrib/modeladmin/templatetags/modeladmin_tags.py
Labels: Accessibility, component:Frontend, type:Enhancement

#6609 Add {% if page %} around language selector example
  docs/advanced_topics/i18n.rst
Labels: Documentation, component:i18n

#6572 Allows to mark the language names as translation strings
  wagtail/core/models.py
  wagtail/core/tests/test_locale_model.py
  wagtail/core/tests/test_utils.py
  wagtail/tests/settings.py
Labels: type:Bug

#6624 Avoid recommending replacing image/document models entirely
  docs/reference/settings.rst
Labels: Documentation

#6644 Add js translatable string for comment save warning
  client/tests/stubs.js
  wagtail/admin/localization.py
Labels: status:Needs Review, type:Enhancement

#6652 Prevent remove_stale_contenttypes from removing the access_admin permission
  wagtail/admin/migrations/0001_create_admin_access_permissions.py
  wagtail/admin/migrations/0002_admin.py
  wagtail/admin/models.py
  wagtail/admin/tests/tests.py
Labels: status:Needs Review, type:Bug
