Repository wagtail/wagtail, pull requests merged in 2020-02, with the labels that each got.

#5831 Add README badges for LGTM
  README.md
Labels: type:Enhancement

#5840 Remove support for Django 2.1
  .travis.yml
  CHANGELOG.txt
  README.md
  docs/getting_started/integrating_into_django.rst
  docs/releases/2.9.rst
  docs/releases/upgrading.rst
  setup.py
  tox.ini
Labels: type:Cleanup/Optimisation

#5752 Fix documents tests on Windows
  wagtail/documents/tests/test_views.py
Labels: component:Documents, status:Needs Review
