Repository wagtail/wagtail, pull requests merged in 2020-05, with the labels that each got.

#6002 Docs - revise bg colour & wagtail on hover styles
  docs/_static/css/custom.css
Labels: Documentation, status:Needs Review

#6001 Docs - Fix sphinx warnings
  docs/_static/js/banner.js
  docs/conf.py
  docs/reference/pages/model_reference.rst
Labels: Documentation, status:Needs Review

#6012 Fix gulp.dest path rewriter output from Gulp 4 upgrade
  gulpfile.js/tasks/styles.js
Labels: Release blocker, type:Bug

#4731 add ability to overwrite wagtail logo with own logo for the userbar
  CHANGELOG.txt
  docs/advanced_topics/customisation/admin_templates.rst
  docs/releases/2.10.rst
  wagtail/admin/static_src/wagtailadmin/scss/userbar.scss
  wagtail/admin/templates/wagtailadmin/userbar/base.html
Labels: component:Frontend, type:Enhancement

#6024 Fix typo in ModelAdminGroup example
  docs/reference/contrib/modeladmin/index.rst
Labels: component:Documents

#6029 docs - revise heading levels for feature detection (images)
  docs/advanced_topics/images/feature_detection.rst
Labels: Documentation

#6031 Add export_filename option to modeladmin
  docs/reference/contrib/modeladmin/indexview.rst
  wagtail/contrib/modeladmin/tests/test_simple_modeladmin.py
  wagtail/contrib/modeladmin/views.py
  wagtail/tests/modeladmintest/wagtail_hooks.py
Labels: component:Modeladmin, type:Enhancement

#6039 Mention INSTALLED_APPS ordering in custom user docs
  docs/advanced_topics/customisation/custom_user_models.rst
Labels: Documentation

#5953 Some cleanups in PostgreSQL search module
  docs/reference/contrib/postgres_search.rst
  wagtail/contrib/postgres_search/backend.py
  wagtail/contrib/postgres_search/models.py
  wagtail/contrib/postgres_search/query.py
Labels: component:Search, status:Needs Review, type:Cleanup/Optimisation

#6032 Explain commit to pr branch
  docs/contributing/committing.rst
Labels: Documentation, status:Needs Review

#6050 Fix typo in 2.10 release notes doc
  docs/releases/2.10.rst
Labels: Documentation

#6071 Fix test suite migrations to match django-taggit 1.3.0
  setup.py
  wagtail/tests/testapp/migrations/0051_tag_verbose_name.py
Labels: type:Cleanup/Optimisation

#6075 Fix RestaurantTag migration tests introducing an extra migration
  wagtail/tests/testapp/migrations/0047_restaurant_tags.py
Labels: Release blocker, component:Tagging, status:Needs Review, type:Cleanup/Optimisation

#6054 Update Python and JS test coverage collection to exclude tests
  .coveragerc
  package.json
Labels: status:Needs Review, type:Cleanup/Optimisation

#6077 Translate site default label.
  wagtail/contrib/settings/forms.py
  wagtail/core/models.py
Labels: component:Site, status:Needs Review

#6087 Update AbstractForm to use mode_name for preview mode
  wagtail/contrib/forms/models.py
Labels: component:Form builder, status:Needs Review, type:Cleanup/Optimisation
