Repository wagtail/wagtail, pull requests merged in 2020-09, with the labels that each got.

#6277 Simplify Page.copy()
  setup.py
  wagtail/core/migrations/0047_add_workflow_models.py
  wagtail/core/models.py
Labels: type:Cleanup/Optimisation

#6318 Allow nested sections in tabs
  client/scss/components/_tabs.scss
Labels: component:Frontend

#6389 Avoid 'ZZZZ' tree paths as placeholders on preview
  wagtail/admin/views/pages/preview.py
Labels: status:Needs Review, type:Cleanup/Optimisation

#6243 Add icon sprite via local storage
  CHANGELOG.txt
  docs/releases/2.11.rst
  wagtail/admin/templates/wagtailadmin/skeleton.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_icon_sprite.py
  wagtail/admin/urls/__init__.py
  wagtail/admin/views/home.py
Labels: sprint:WagtailSpaceUS2020, type:Enhancement

#6402 Support SVG icons in ModelAdmin menu items
  CHANGELOG.txt
  docs/reference/contrib/modeladmin/menu_item.rst
  docs/releases/2.11.rst
  wagtail/contrib/modeladmin/menus.py
  wagtail/contrib/modeladmin/options.py
Labels: component:Modeladmin, type:Enhancement

#6341 Force string url before passing to urlparse
  wagtail/api/v2/tests/tests.py
  wagtail/api/v2/utils.py
Labels: component:API

#6392 Performance improvements for page copy
  wagtail/core/models.py
Labels: component:i18n, type:Cleanup/Optimisation
