Repository wagtail/wagtail, pull requests merged in 2020-06, with the labels that each got.

#6092 add gitignore to tests folder - ignore test-media sub-folder
  wagtail/tests/.gitignore
Labels: status:Needs Review, type:Cleanup/Optimisation

#6104 Fix typo in request.site middleware deprecation warning
  wagtail/core/middleware.py
Labels: component:Site, status:Needs Review

#6040 WebP images quality/lossless compression parameters
  docs/topics/images.rst
  setup.py
  wagtail/images/image_operations.py
  wagtail/images/models.py
  wagtail/images/tests/test_image_operations.py
  wagtail/images/wagtail_hooks.py
Labels: component:Images, status:Needs Work

#6153 Remove 'whitelist' from page reference docs
  docs/reference/pages/model_reference.rst
Labels: Documentation

#6148 Workflow failure icon
  wagtail/admin/templates/wagtailadmin/icons/failure.svg
  wagtail/admin/templates/wagtailadmin/reports/workflow.html
  wagtail/admin/templates/wagtailadmin/shared/workflow_status.html
  wagtail/admin/wagtail_hooks.py
Labels: component:Workflow, status:Needs Review

#6147 [Workflow] Get STATUS_CHOICES from Task when annotating all_tasks_with_status
  wagtail/core/models.py
Labels: component:Workflow, status:Needs Review

#6169 [Workflow management UI changes 1] Implemented task chooser modal
  wagtail/admin/forms/workflows.py
  wagtail/admin/static_src/wagtailadmin/js/task-chooser-modal.js
  wagtail/admin/static_src/wagtailadmin/js/task-chooser.js
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/admin/templates/wagtailadmin/widgets/chooser.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/chooser.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/create_form.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/results.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/select_task_type.html
  wagtail/admin/templates/wagtailadmin/workflows/widgets/task_chooser.html
  wagtail/admin/tests/test_workflows.py
  wagtail/admin/urls/workflows.py
  wagtail/admin/views/workflows.py
  wagtail/admin/widgets/chooser.py
  wagtail/admin/widgets/workflows.py
  wagtail/core/utils.py
Labels: component:Workflow, status:Needs Review

#6158 Optimise npm install in squash for speed & logs visibility
  .squash.yml
Labels: component:Frontend, status:Needs Review, type:Cleanup/Optimisation

#6167 Upgrade jquery to 3.5.1
  CHANGELOG.txt
  docs/releases/2.10.rst
  wagtail/admin/static_src/wagtailadmin/js/page-editor.test.js
  wagtail/admin/static_src/wagtailadmin/js/vendor/jquery-3.2.1.min.js
  wagtail/admin/static_src/wagtailadmin/js/vendor/jquery-3.5.1.min.js
  wagtail/admin/templates/wagtailadmin/admin_base.html
Labels: component:Frontend, component:Security, type:Cleanup/Optimisation

#6179 Move pages summary item hook into wagtail.admin.wagtail_hooks
  wagtail/admin/site_summary.py
  wagtail/admin/wagtail_hooks.py
Labels: type:Cleanup/Optimisation

#6117 Fix gulp watch task
  gulpfile.js/tasks/watch.js
Labels: status:Needs Review

#6183 Purge image rendition cache on rendition deletion
  wagtail/images/models.py
  wagtail/images/signal_handlers.py
  wagtail/images/tests/test_models.py
Labels: component:Images, status:Needs Review, type:Bug
