Repository wagtail/wagtail, pull requests merged in 2020-11, with the labels that each got.

#6506 More prominent note about wagtail-localize in i18n docs
  docs/advanced_topics/i18n.rst
Labels: Documentation, component:i18n

#6507 Check if new pages are site roots and clear the site_root_paths cache
  wagtail/core/models.py
  wagtail/core/tests/tests.py
Labels: type:Bug

#6523 Switch IE11 home warning message to show for all users regardless of role
  wagtail/admin/views/home.py
Labels: type:Cleanup/Optimisation

#6272 #6090 Document accessibility considerations
  docs/advanced_topics/accessibility_considerations.rst
  docs/advanced_topics/customisation/rich_text_internals.rst
  docs/advanced_topics/index.rst
Labels: Accessibility, Documentation, sprint:WagtailSpaceUS2020, type:Enhancement

#6547 Handle get_supported_language_variant returning a language variant not in LANGUAGES
  CHANGELOG.txt
  docs/releases/2.11.2.rst
  wagtail/core/tests/test_utils.py
  wagtail/core/utils.py
Labels: component:i18n, type:Bug
