Repository wagtail/wagtail, pull requests merged in 2021-05, with the labels that each got.

#7126 Admin URLs respect APPEND_SLASH setting
  wagtail/admin/tests/tests.py
  wagtail/admin/urls/__init__.py
Labels: component:Page

#7138 Fix usage of html syntax instead of html+django
  docs/advanced_topics/adding_reports.rst
  docs/reference/contrib/forms/index.rst
  docs/reference/contrib/settings.rst
  docs/topics/search/searching.rst
Labels: Documentation

#7169 Prevent JS error on URL hashes that are not tabs
  client/src/entrypoints/admin/core.js
Labels: type:Bug

#7142 Update accessibility contribution guidance in bug report and PR templates
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing/html_guidelines.rst
Labels: Accessibility, Documentation, component:Frontend, type:Enhancement

#7164 Add documentation for custom JS on StructBlocks
  docs/advanced_topics/customisation/streamfield_blocks.rst
  docs/releases/2.13.rst
Labels: Documentation

#7171 Disable options without translated parent. Add help text.
  client/scss/elements/_forms.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  wagtail/contrib/simple_translation/forms.py
  wagtail/contrib/simple_translation/templates/simple_translation/admin/input_option.html
  wagtail/contrib/simple_translation/templates/simple_translation/admin/submit_translation.html
  wagtail/contrib/simple_translation/tests/test_forms.py
Labels: Release blocker, status:Needs Review

#6748 Updates to forgotten password styling
  CHANGELOG.txt
  docs/_static/images/screen01_login.png
  docs/releases/2.14.rst
  wagtail/admin/static_src/wagtailadmin/scss/layouts/login.scss
  wagtail/admin/templates/wagtailadmin/login.html
  wagtail/admin/tests/test_password_reset.py
Labels: Accessibility, component:User Management, status:Needs Review, type:Bug

#6922 Simplify oembed dict missing key fallback
  wagtail/embeds/finders/oembed.py
Labels: size:Small, status:Needs Review, type:Cleanup/Optimisation

#7220 Avoid n+1 query on recent edits dashboard panel
  wagtail/admin/tests/pages/test_dashboard.py
  wagtail/admin/views/home.py
Labels: status:Needs Review, type:Cleanup/Optimisation

#7212 Hide comment notifications checkbox when commenting is disabled
  wagtail/admin/edit_handlers.py
  wagtail/admin/forms/pages.py
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/views/pages/edit.py
Labels: type:Bug
