Repository wagtail/wagtail, pull requests merged in 2021-09, with the labels that each got.

#7501 Fix typos on site settings docs
  docs/reference/contrib/settings.rst
Labels: status:Needs Work, component:Documents

#7489 Update wagtail.contrib.postgres_search Config
  wagtail/contrib/postgres_search/apps.py
Labels: status:Needs Review, component:Search

#7478 update package lock - caniuse-lite db
  package-lock.json
Labels: type:Cleanup/Optimisation, status:Needs Review

#7510 Notifications to active users only
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.15.rst
  wagtail/admin/mail.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/test_workflows.py
Labels: status:Needs Work, component:User Management

#7512 fix warning message for disabling workflow task view
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/admin/tests/test_workflows.py
  wagtail/admin/views/workflows.py
Labels: component:Workflow

#7524 Fix page history with delete user
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/admin/tests/test_audit_log.py
  wagtail/core/models/audit_log.py
Labels: type:Bug, status:Needs Review

#7520 Use gettext_lazy in modeladmin views where required
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/contrib/modeladmin/views.py
Labels: type:Bug, component:Modeladmin, component:UI localization

#7320 Use date format from current locale for xlsx export
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/admin/tests/test_reports_views.py
  wagtail/admin/views/mixins.py
Labels: status:Needs Work, status:Needs Tests

#7493 Make hamburger menu a button for tab accessibility
  CHANGELOG.txt
  client/scss/components/_main-nav.scss
  docs/releases/2.15.rst
  wagtail/admin/templates/wagtailadmin/base.html
Labels: status:Needs Review, Accessibility

#7507 Fix userbar tabbing behaviour
  CHANGELOG.txt
  client/src/entrypoints/admin/userbar.js
  docs/releases/2.15.rst
Labels: status:Needs Review, component:Frontend, Accessibility

#7527 Docs: Clarify Jinja2 template configuration
  docs/reference/jinja2.rst
Labels: Documentation, status:Needs Review

#7538 Add missing bind_to call to PreviewOnEdit, fixes #7537
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/admin/tests/pages/test_preview.py
  wagtail/admin/views/pages/preview.py
Labels: component:Page

#7548 Add page synchronization to simple_translation
  docs/reference/contrib/simple_translation.rst
  wagtail/contrib/simple_translation/models.py
  wagtail/contrib/simple_translation/tests/test_views.py
Labels: type:Enhancement, status:Needs Review, component:Search

#7544 Update _dropdown.legacy.scss - Styling for the dropdown
  CHANGELOG.txt
  client/scss/components/_dropdown.legacy.scss
  docs/releases/2.15.rst
Labels: status:Needs Review, Accessibility

#7444 Use a mixin instead of properties for various image file related methods
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/images/models.py
Labels: status:Needs Review, component:Images

#7554 Add section about CSV exports to security docs
  docs/contributing/security.md
Labels: Documentation, component:Security

#6818 Docs: Include custom permissions hook documentation
  CHANGELOG.txt
  docs/reference/hooks.rst
  docs/releases/2.15.rst
  docs/topics/permissions.rst
Labels: Documentation, status:Needs Review
