Repository wagtail/wagtail, pull requests merged in 2021-07, with the labels that each got.

#7298 Prevent comments CSS from overriding custom colours
  client/scss/components/_comments-controls.scss
  client/scss/components/_comments-notification-dropdown.scss
  client/src/components/CommentApp/main.scss
Labels: component:Commenting, component:Frontend, status:Needs Review, type:Bug

#7309 `select_related` user profile when listing users
  wagtail/users/views/users.py
Labels: Performance

#7314 Give quoted and unquoted versions of pip install commands
  docs/contributing/developing.rst
Labels: Documentation, status:Needs Review

#7315 Use `select_related` when viewing the Site History report
  wagtail/admin/views/reports/audit_logging.py
Labels: Performance

#7318 Improve admin listing performance
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/views/pages/listing.py
  wagtail/core/models/__init__.py
  wagtail/core/query.py
Labels: Performance, type:Cleanup/Optimisation

#7324 Add missing max_length on temporary thumbnail_url migration
  wagtail/embeds/migrations/0008_allow_long_urls.py
Labels: status:Needs Review, type:Bug

#7351 Eliminate use of re_path from integration docs
  docs/getting_started/integrating_into_django.md
Labels: Documentation

#7347 Fix "undefined label" warnings caused by missing leading underscore
  docs/topics/pages.md
  docs/topics/permissions.rst
Labels: Documentation

#7360 Replace is_safe_url with url_has_allowed_host_and_scheme
  wagtail/admin/views/pages/lock.py
  wagtail/admin/views/pages/utils.py
  wagtail/admin/views/pages/workflow.py
  wagtail/admin/views/workflows.py
Labels: type:Cleanup/Optimisation

#7359 Set default_auto_field on simple_translation app config
  wagtail/contrib/simple_translation/apps.py
Labels: type:Cleanup/Optimisation

#7361 Ensure error count badge counts StreamField non-block errors
  client/src/entrypoints/admin/page-editor.js
Labels: component:Streamfield, type:Bug

#7346 Converts inline panel anchor to button to make keyboard focusable.
  CHANGELOG.txt
  docs/releases/2.15.rst
  wagtail/admin/templates/wagtailadmin/edit_handlers/inline_panel.html
Labels: Accessibility, component:Panels, status:Needs Review, type:Bug
