Repository wagtail/wagtail, pull requests merged in 2021-11, with the labels that each got.

#7677 Add Assistiv Labs sponsorship info to the README
  .github/assistivlabs-logo.png
  README.md
Labels: type:Cleanup/Optimisation, status:Needs Review, Accessibility

#7638 Add more SketchFab oembed patterns
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/embeds/oembed_providers.py
Labels: hacktoberfest-accepted

#7634 Fix Dashboard icons in high-contrast mode
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/admin/static_src/wagtailadmin/scss/layouts/home.scss
Labels: Accessibility, hacktoberfest-accepted

#7683 Change spin animation name to make it less prone to be overridden
  CHANGELOG.txt
  client/scss/components/_loading-mask.scss
  client/src/components/LoadingSpinner/LoadingSpinner.scss
  docs/releases/2.16.md
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: status:Needs Review, component:Frontend

#7738 collapse option on StreamField, StreamBlock, ListBlock
  CHANGELOG.txt
  client/src/components/StreamField/blocks/ListBlock.js
  client/src/components/StreamField/blocks/StreamBlock.js
  docs/reference/streamfield/blocks.rst
  docs/releases/2.16.md
  wagtail/core/blocks/list_block.py
  wagtail/core/blocks/stream_block.py
  wagtail/core/fields.py
  wagtail/core/tests/test_blocks.py
Labels: type:Enhancement, component:Streamfield
