Repository wagtail/wagtail, pull requests merged in 2021-10, with the labels that each got.

#7563 Fix link to node.js download
  docs/contributing/developing.rst
Labels: Documentation, size:Small

#6828 Add How-To instructions for landing-page redirects
  CHANGELOG.txt
  docs/advanced_topics/formbuilder_routablepage_redirect.md
  docs/advanced_topics/index.rst
  docs/releases/2.15.rst
Labels: Documentation, status:Needs Review

#7535 update documentation & 2.15 release to drop IE11 support
  docs/advanced_topics/customisation/admin_templates.rst
  docs/advanced_topics/customisation/streamfield_blocks.rst
  docs/contributing/developing.rst
  docs/editor_manual/browser_issues.rst
  docs/extending/extending_draftail.rst
  docs/releases/2.15.rst
  package.json
  wagtail/admin/templates/wagtailadmin/skeleton.html
Labels: Documentation, status:Needs Review

#7572 Deployment docs - update wagtail getting started
  docs/advanced_topics/deploying.rst
Labels: Documentation

#7534 Add ability to customise the pre-filled Image title (image uploads)
  CHANGELOG.txt
  docs/advanced_topics/images/index.rst
  docs/advanced_topics/images/title_generation_on_upload.md
  docs/releases/2.15.rst
  wagtail/admin/views/generic/multiple_upload.py
  wagtail/images/static_src/wagtailimages/js/add-multiple.js
  wagtail/images/static_src/wagtailimages/js/image-chooser-modal.js
  wagtail/images/templates/wagtailimages/images/add.html
  wagtail/images/templates/wagtailimages/multiple/add.html
  wagtail/images/tests/test_admin_views.py
  wagtail/images/views/multiple.py
Labels: status:Needs Review, component:Images

#7575 update hooks documentation to use mark_safe as no variables are used
  docs/reference/hooks.rst
Labels: Documentation

#7578 Capture log output from style fallback unit test
  wagtail/admin/rich_text/converters/contentstate.py
  wagtail/admin/tests/test_contentstate.py
Labels: type:Cleanup/Optimisation
