Repository wagtail/wagtail, pull requests merged in 2021-03, with the labels that each got.

#6839 Docs: Convert "getting started - demo site" from RST to MD
  docs/getting_started/demo_site.md
  docs/getting_started/demo_site.rst
Labels: Documentation, type:Enhancement

#6854 Fix crash when copying an alias page
  wagtail/core/models.py
  wagtail/core/tests/test_page_model.py
Labels: type:Bug

#6865 Add first draft of GSOC issue template
  .github/ISSUE_TEMPLATE/GSOC.md
Labels: GSOC

#6830 Change `master` to `main`
  .circleci/config.yml
  .circleci/trigger-nightly-build.sh
  README.md
  client/scss/tools/_functions.breakpoints.scss
  client/scss/tools/_mixins.breakpoints.scss
  docs/README.md
  docs/advanced_topics/embeds.rst
  docs/conf.py
  docs/contributing/committing.rst
  docs/contributing/release_process.rst
  docs/contributing/security.md
  docs/editor_manual/new_pages/inserting_videos.rst
  docs/reference/settings.rst
  docs/releases/0.7.rst
  wagtail/admin/static_src/wagtailadmin/js/vendor/bootstrap-transition.js
Labels: type:Cleanup/Optimisation

#6872 Prevent error on page editing after changing LANGUAGE_CODE
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/core/models.py
Labels: Release blocker

#6816 Fix copy_for_translation on inherited and clusterable models
  wagtail/core/models.py
  wagtail/core/tests/test_translatablemixin.py
  wagtail/tests/i18n/migrations/0002_clusterabletestmodel_clusterabletestmodelchild_clusterabletestmodeltranslatablechild.py
  wagtail/tests/i18n/models.py
Labels: component:i18n, type:Bug

#6862 Use TypeScript configuration for all JS linting
  .eslintrc
  client/src/api/admin.test.js
  client/src/entrypoints/admin/core.js
  client/src/entrypoints/admin/hallo-bootstrap.js
  client/src/entrypoints/admin/hallo-plugins/hallo-wagtaillink.js
  client/src/entrypoints/admin/modal-workflow.js
  client/src/entrypoints/admin/page-chooser-modal.js
  client/src/entrypoints/admin/page-editor.js
  client/src/entrypoints/admin/task-chooser-modal.js
  client/src/entrypoints/admin/userbar.js
  client/src/entrypoints/admin/wagtailadmin.js
  package.json
Labels: type:Cleanup/Optimisation

#6833 Docsearch w/ Search Results Page
  docs/_static/css/custom.css
  docs/_static/css/docsearch.overrides.css
  docs/_templates/layout.html
  docs/_templates/search.html
  docs/_templates/searchbox.html
  docs/conf.py
Labels: Documentation, type:Enhancement

#6883 Fix the DocSearch search input appearing smaller after initialization
  docs/_static/css/docsearch.overrides.css
Labels: Documentation, type:Bug

#6884 Fix DocSearch widget initialisation JS error
  docs/_templates/layout.html
  docs/_templates/search.html
Labels: Documentation, type:Bug

#6649 Switch register_setting, register_settings_menu_item to use SVG icons (#6107)
  CHANGELOG.txt
  docs/releases/2.13.rst
  wagtail/contrib/settings/registry.py
  wagtail/contrib/settings/tests/test_admin.py
Labels: Accessibility, component:Frontend, type:Enhancement

#6892 Update register_admin_menu_item documentation to match SVG icons setup
  docs/reference/hooks.rst
Labels: Documentation, status:Needs Review, type:Cleanup/Optimisation

#6796 Create DOCUMENTATION.md
  .github/ISSUE_TEMPLATE/DOCUMENTATION.md
  CONTRIBUTORS.rst
Labels: sprint:Documentation2021, status:Needs Work, type:Enhancement

#6943 Remove redundant 'filter_page_type' helper methods
  wagtail/admin/views/chooser.py
  wagtail/api/v2/utils.py
  wagtail/api/v2/views.py
Labels: component:Page, status:Needs Review, type:Cleanup/Optimisation

#6936 Show current page in breadcrumb
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
Labels: component:Page

#6940 6925 Update StreamField Screenshot in Editor's Guide
  docs/_static/images/screen11.8_adding_new_blocks.png
  docs/_static/images/screen11.9_streamfield_reordering.png
  docs/_static/images/screen11_empty_streamfield.png
Labels: Documentation
