Repository wagtail/wagtail, pull requests merged in 2021-02, with the labels that each got.

#6768 Quote pip install command in developing docs
  docs/contributing/developing.rst
Labels: sprint:Documentation2021

#6770 Support skipping CI
  .github/workflows/test.yml
Labels: sprint:Documentation2021

#6776 Remove 'new'
  docs/editor_manual/intro.rst
Labels: sprint:Documentation2021

#6769 Remove excited tone
  docs/getting_started/tutorial.rst
Labels: sprint:Documentation2021

#6777 Improve existing page docs in editor guide
  docs/editor_manual/editing_existing_pages.rst
Labels: sprint:Documentation2021

#6773 Changed heading in image index
  CONTRIBUTORS.rst
  docs/topics/images.rst
Labels: sprint:Documentation2021

#6783 Fix typo in inline code formatting
  docs/advanced_topics/custom_tasks.rst
Labels: sprint:Documentation2021

#6775 Changed the title for Wagtail AMP support
  docs/advanced_topics/amp.rst
Labels: sprint:Documentation2021

#6786 Limit GitHub Actions docs and test workflows depending on changed paths
  .github/workflows/docs.yml
  .github/workflows/test.yml
Labels: sprint:Documentation2021

#6784 Fix broken "make livehtml" command
  docs/Makefile
Labels: sprint:Documentation2021

#6789 Move "writing documentation" page into Contributing
  docs/contributing/documentation-modes.rst
  docs/contributing/index.rst
  docs/explanation/index.rst
  docs/index.rst
Labels: sprint:Documentation2021

#6794 Include privacy within the settings tab section
  docs/editor_manual/new_pages/the_promote_tab.rst
Labels: Documentation, sprint:Documentation2021

#6780 Promote panel changes
  docs/editor_manual/new_pages/the_promote_tab.rst
  wagtail/admin/edit_handlers.py
  wagtail/core/migrations/0061_change_promote_tab_helpt_text_and_verbose_names.py
  wagtail/core/models.py
Labels: Documentation, component:Page, component:Panels, sprint:Documentation2021

#6822 Pin treebeard to <4.5 to prevent migration issues
  setup.py
Labels: Release blocker

#6823 Insert Plausible.io analytics code into docs
  docs/_templates/layout.html
Labels: Documentation

#6829 Docs: Convert "reporting security issues" from RST to MD
  CONTRIBUTORS.rst
  docs/contributing/security.md
  docs/contributing/security.rst
Labels: Documentation, type:Enhancement

#6639 Special case date lookups for searching
  wagtail/search/backends/base.py
  wagtail/search/tests/elasticsearch_common_tests.py
  wagtail/search/tests/test_elasticsearch5_backend.py
  wagtail/search/tests/test_elasticsearch6_backend.py
  wagtail/search/tests/test_elasticsearch7_backend.py
Labels: component:Search, type:Enhancement

#6320 Fix Jinja2 to include_block not including local variables
  setup.py
  wagtail/core/jinja2tags.py
  wagtail/core/tests/test_jinja2.py
  wagtail/tests/testapp/jinja2_templates/tests/jinja2/include_block_only_test.html
  wagtail/tests/testapp/jinja2_templates/tests/jinja2/include_block_tag_with_additional_variable.html
Labels: status:Needs Review, type:Enhancement
