Repository wagtail/wagtail, pull requests merged in 2021-04, with the labels that each got.

#6967 Tidy up page editor inline JS
  wagtail/admin/templates/wagtailadmin/pages/edit.html
Labels: status:Needs Review, type:Cleanup/Optimisation

#6528 Add contrib simple translation
  docs/advanced_topics/i18n.rst
  docs/reference/contrib/index.rst
  docs/reference/contrib/simple_translation.rst
  wagtail/contrib/simple_translation/__init__.py
  wagtail/contrib/simple_translation/apps.py
  wagtail/contrib/simple_translation/forms.py
  wagtail/contrib/simple_translation/migrations/0001_initial.py
  wagtail/contrib/simple_translation/migrations/__init__.py
  wagtail/contrib/simple_translation/models.py
  wagtail/contrib/simple_translation/templates/simple_translation/admin/submit_translation.html
  wagtail/contrib/simple_translation/tests/__init__.py
  wagtail/contrib/simple_translation/tests/test_forms.py
  wagtail/contrib/simple_translation/tests/test_migrations.py
  wagtail/contrib/simple_translation/tests/test_views.py
  wagtail/contrib/simple_translation/tests/test_wagtail_hooks.py
  wagtail/contrib/simple_translation/views.py
  wagtail/contrib/simple_translation/wagtail_hooks.py
  wagtail/tests/settings.py
Labels: component:i18n, status:Needs Review, type:Enhancement

#7015 Lock nav and page scroll together only when search autocomplete is open. Fix #6935
  docs/_static/css/custom.css
  docs/_templates/layout.html
Labels: Documentation, type:Bug

#6998 Choosers: refactor to use SVG icons
  CHANGELOG.txt
  client/scss/components/_chooser.scss
  docs/releases/2.13.rst
  wagtail/admin/templates/wagtailadmin/widgets/chooser.html
  wagtail/admin/templates/wagtailadmin/widgets/page_chooser.html
  wagtail/documents/templates/wagtaildocs/widgets/document_chooser.html
  wagtail/images/templates/wagtailimages/widgets/image_chooser.html
  wagtail/snippets/templates/wagtailsnippets/widgets/snippet_chooser.html
Labels: Accessibility, component:Frontend, type:Enhancement

#6739 Make all Collection form fields translate-able
  CHANGELOG.txt
  docs/releases/2.13.rst
  wagtail/admin/forms/collections.py
  wagtail/documents/forms.py
  wagtail/images/forms.py
Labels: component:UI localization, type:Bug

#6999 Fix wagtailembeds thumbnail_url migration for MySQL 8.0.13
  .github/workflows/test.yml
  wagtail/embeds/migrations/0008_allow_long_urls.py
Labels: Release blocker

#6980 Apply chevron padding fix to all applicable `select` elements
  CHANGELOG.txt
  client/scss/components/_forms.scss
  docs/releases/2.13.rst
Labels: type:Bug

#6930 Add Sphinx Wagtail Theme
  docs/_static/css/docsearch.overrides.css
  docs/_templates/layout.html
  docs/_templates/searchbox.html
  docs/conf.py
  docs/getting_started/index.md
  docs/index.rst
  docs/requirements.txt
  setup.py
Labels: Documentation, status:Needs Review

#7023 Wagtail API pages endpoint to respond with a 400 error (instead of 500 error) when entering an invalid value to a filter
  wagtail/api/v2/filters.py
  wagtail/api/v2/tests/test_pages.py
Labels: component:API

#7062 Add search details and contributors to theme release notes
  docs/releases/2.13.rst
Labels: Documentation

#7073 Fix comments list height to prevent grey bar at bottom
  client/src/components/CommentApp/main.scss
Labels: type:Bug

#7077 Fix #7007: Add ancestor_of API filter
  docs/advanced_topics/api/v2/usage.rst
  wagtail/api/v2/filters.py
  wagtail/api/v2/tests/test_pages.py
  wagtail/api/v2/views.py
Labels: component:API, status:Needs Review

#7072 Apply WidgetAdapter to CheckboxSelectMultiple.
  wagtail/core/widget_adapters.py
Labels: type:Bug

#7100 Add decorator to CommentableEditor even when disabled
  client/src/components/Draftail/CommentableEditor/CommentableEditor.tsx
Labels: type:Bug

#7069 Redirect to parent page when a child page is deleted from its listing view
  wagtail/admin/tests/test_buttons_hooks.py
  wagtail/admin/wagtail_hooks.py
Labels: status:Needs Review, type:Bug

#6870 Docs: Covert "topics - pages" from RST to MD
  docs/topics/pages.md
  docs/topics/pages.rst
Labels: Documentation, status:Needs Review
