Repository wagtail/wagtail, pull requests merged in 2022-03, with the labels that each got.

#8061 Test integration - npm package updates
  client/tests/integration/package-lock.json
  client/tests/integration/package.json
Labels: type:Cleanup/Optimisation, Accessibility

#8041 update browserslist - not ie 11
  package-lock.json
  package.json
Labels: type:Cleanup/Optimisation

#8072 refine documentation for `show_in_menus`
  docs/reference/pages/model_reference.rst
Labels: Documentation

#8064 Page Editor Improvements: TypeScale configuration
  client/src/tokens/typeScale.js
  client/src/tokens/typography.js
  client/tailwind.config.js
Labels: type:Enhancement, component:Design system

#8082 Readme - add badges
  README.md
Labels: Documentation

#8054 Revise SVG Icons to use Icons import or css where necessary
  CHANGELOG.txt
  client/scss/components/_button.scss
  client/scss/components/_forms.scss
  client/scss/components/_header.scss
  client/scss/components/_help-block.scss
  client/scss/components/_loading-mask.scss
  client/scss/components/_main-nav.scss
  client/scss/components/_tag.scss
  client/scss/elements/_forms.scss
  client/scss/overrides/_vendor.datetimepicker.scss
  client/scss/overrides/_vendor.tagit.scss
  client/src/components/Explorer/Explorer.scss
  client/src/components/Explorer/ExplorerHeader.tsx
  client/src/components/PageExplorer/PageExplorer.scss
  client/src/components/PageExplorer/PageExplorerHeader.tsx
  client/src/components/StreamField/blocks/FieldBlock.js
  client/src/components/StreamField/blocks/__snapshots__/FieldBlock.test.js.snap
  docs/releases/2.17.md
  wagtail/admin/static_src/wagtailadmin/images/icons/arrow-down.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/cross.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/radio-full.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/spinner.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/tag.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/tick.svg
  wagtail/admin/static_src/wagtailadmin/scss/layouts/login.scss
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/admin/templates/wagtailadmin/account/password_reset/confirm.html
  wagtail/admin/templates/wagtailadmin/chooser/browse.html
  wagtail/admin/templates/wagtailadmin/collection_privacy/set_privacy.html
  wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html
  wagtail/admin/templates/wagtailadmin/page_privacy/set_privacy.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list_explore.html
  wagtail/admin/templates/wagtailadmin/pages/revisions/compare.html
  wagtail/admin/templates/wagtailadmin/shared/field.html
  wagtail/admin/templates/wagtailadmin/shared/header.html
  wagtail/admin/templates/wagtailadmin/workflows/edit.html
  wagtail/admin/templates/wagtailadmin/workflows/edit_task.html
  wagtail/contrib/modeladmin/templates/modeladmin/includes/search_form.html
  wagtail/contrib/redirects/templates/wagtailredirects/choose_import_file.html
  wagtail/contrib/redirects/templates/wagtailredirects/import_summary.html
  wagtail/contrib/redirects/templates/wagtailredirects/index.html
  wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/add.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/images/templates/wagtailimages/images/url_generator.html
  wagtail/locales/templates/wagtaillocales/edit.html
  wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html
  wagtail/users/static_src/wagtailusers/scss/groups_edit.scss
Labels: status:Needs Review, status:Needs Work, component:Frontend

#8067 docs - add third party tutorials Jan/Feb 2022
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation

#8084 docs - move markdown docs to MyST
  docs/advanced_topics/third_party_tutorials.md
  docs/conf.py
  docs/contributing/documentation_guidelines.md
  docs/contributing/security.md
  docs/extending/forms.md
  docs/extending/template_components.md
  docs/getting_started/index.md
  docs/getting_started/integrating_into_django.md
  docs/getting_started/the_zen_of_wagtail.md
  docs/getting_started/tutorial.md
  docs/reference/contrib/legacy_richtext.md
  docs/releases/2.16.2.md
  docs/releases/2.16.md
  docs/releases/2.17.md
  docs/requirements.txt
  docs/topics/index.md
  docs/topics/pages.md
  setup.py
Labels: Documentation

#8058 construct_synced_page_tree_list hook tests
  docs/reference/hooks.rst
  wagtail/admin/templates/wagtailadmin/pages/confirm_unpublish.html
  wagtail/contrib/simple_translation/tests/test_wagtail_hooks.py
Labels: status:Needs Work, component:i18n, component:Page

#8007 documentation - migrate form builder docs to markdown
  docs/advanced_topics/accessibility_considerations.rst
  docs/advanced_topics/add_to_django_project.rst
  docs/reference/contrib/forms/customisation.md
  docs/reference/contrib/forms/customisation.rst
  docs/reference/contrib/forms/index.md
  docs/reference/contrib/forms/index.rst
Labels: Documentation, status:Needs Review, component:Form builder

#8105 Use released django-modelcluster when testing against Django main
  .github/workflows/test.yml
Labels: type:Cleanup/Optimisation

#8113 Replaced focus-outline-on utility
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/scss/overrides/_utilities.focus.scss
  client/src/components/Sidebar/Sidebar.stories.tsx
  client/src/entrypoints/admin/wagtailadmin.js
  client/src/index.ts
  client/src/utils/focus.js
  client/src/utils/focus.test.js
  docs/releases/2.17.md
Labels: type:Cleanup/Optimisation, status:Needs Review

#8111 Removed uppercasing from SCSS files
  CHANGELOG.txt
  client/scss/components/_bulk_actions.scss
  client/scss/components/_button.scss
  client/scss/components/_comments-controls.scss
  client/scss/components/_comments-notification-dropdown.scss
  client/scss/components/_dropdown.legacy.scss
  client/scss/components/_forms.scss
  client/scss/components/_listing.scss
  client/scss/components/_main-nav.scss
  client/scss/components/_tabs.scss
  client/scss/components/_workflow-tasks.scss
  client/scss/elements/_typography.scss
  client/src/components/CommentApp/main.scss
  client/src/components/Sidebar/modules/MainMenu.scss
  docs/releases/2.17.md
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/contrib/modeladmin/static_src/wagtailmodeladmin/scss/index.scss
  wagtail/images/templates/wagtailimages/images/edit.html
Labels: type:Enhancement, Accessibility, component:Design system

#8070 Add alwaysdata among Cloud providers
  CONTRIBUTORS.rst
  docs/advanced_topics/deploying.rst
Labels: type:Enhancement, status:Needs Design Decision, Documentation

#8117 Tailwind setup follow-up: RTL support and Windows High Contrast mode
  client/tailwind.config.js
  package-lock.json
  package.json
Labels: type:Enhancement, status:Needs Review, component:Design system

#8133 documentation - adopt MyST syntax for form builder section
  docs/reference/contrib/forms/customisation.md
  docs/reference/contrib/forms/index.md
Labels: Documentation, component:Form builder

#8132 refine documentation guidelines for links
  docs/contributing/documentation_guidelines.md
Labels: Documentation

#8102 Add a custom clean page to the docs
  CHANGELOG.txt
  docs/reference/contrib/modeladmin/tips_and_tricks/custom_clean.md
  docs/reference/contrib/modeladmin/tips_and_tricks/index.md
  docs/releases/2.17.md
Labels: Documentation, status:Needs Review, component:Modeladmin

#8109 Update InlinePanel for change in ClusterForm formsets/exclude_formsets semantics (EditHandler rewrite)
  setup.py
  wagtail/admin/edit_handlers.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: type:Cleanup/Optimisation, status:Needs Review, component:Panels

#8154 documentation - update node installation instructions
  docs/contributing/developing.rst
Labels: Documentation, status:Needs Review

#8119 Prevent refresh on enter in header search (documents and images)
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.17.md
  wagtail/admin/templates/wagtailadmin/shared/header.html
Labels: status:Needs Review, component:Search, component:Images, component:Documents, GSOC

#8153 format readme with prettier
  README.md
Labels: Documentation, status:Needs Review

#8120 Removed outdated handling of length parameter to If-Modified-Since header.
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.17.md
  wagtail/utils/sendfile_streaming_backend.py
Labels: Compatibility

#8118 Sidebar style updates
  client/scss/components/_logo.scss
  client/scss/components/_main-nav.scss
  client/scss/settings/_variables.scss
  client/src/components/PageExplorer/PageExplorer.scss
  client/src/components/PageExplorer/PageExplorerItem.scss
  client/src/components/PageExplorer/PageExplorerItem.tsx
  client/src/components/PublicationStatus/PublicationStatus.scss
  client/src/components/Sidebar/Sidebar.scss
  client/src/components/Sidebar/Sidebar.stories.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/Sidebar/__snapshots__/Sidebar.test.js.snap
  client/src/components/Sidebar/menu/MenuItem.scss
  client/src/components/Sidebar/menu/SubMenuItem.scss
  client/src/components/Sidebar/menu/SubMenuItem.tsx
  client/src/components/Sidebar/menu/__snapshots__/SubMenuItem.test.js.snap
  client/src/components/Sidebar/modules/MainMenu.scss
  client/src/components/Sidebar/modules/MainMenu.tsx
  client/src/components/Sidebar/modules/Search.scss
  client/src/components/Sidebar/modules/Search.tsx
  client/src/components/Sidebar/modules/WagtailBranding.scss
  client/src/components/Sidebar/modules/WagtailBranding.tsx
  client/src/components/Sidebar/modules/WagtailLogo.tsx
  client/src/components/Sidebar/modules/__snapshots__/MainMenu.test.js.snap
  client/src/tokens/colors.js
  client/tailwind.config.js
  tailwind.config.js
  wagtail/admin/static_src/wagtailadmin/images/logo-body.svg
  wagtail/admin/static_src/wagtailadmin/images/logo-eyeclosed.svg
  wagtail/admin/static_src/wagtailadmin/images/logo-eyeopen.svg
  wagtail/admin/static_src/wagtailadmin/images/logo-tail.svg
  wagtail/admin/static_src/wagtailadmin/images/wagtail-logo.svg
  wagtail/admin/static_src/wagtailadmin/scss/layouts/404.scss
  wagtail/admin/templates/wagtailadmin/404.html
  wagtail/admin/templates/wagtailadmin/icons/expand-right.svg
  wagtail/admin/templates/wagtailadmin/shared/animated_logo.html
  wagtail/admin/tests/ui/test_sidebar.py
  wagtail/admin/ui/sidebar.py
  wagtail/admin/wagtail_hooks.py
Labels: type:Enhancement

#8122 Pinterest_embed_support
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/2.17.md
  wagtail/embeds/oembed_providers.py
Labels: status:Needs Work, component:Embeds, GSOC

#8201 AbstractFormField.save - add to the docstring about clean name
  wagtail/contrib/forms/models.py
Labels: component:Form builder

#8198 Clean up oembed providers
  wagtail/embeds/oembed_providers.py
Labels: component:Embeds

#8219 Improved CTAs for complying with check in procedures
  .github/PULL_REQUEST_TEMPLATE.md
Labels: sprint:Cleveland2022

#8218 Fixing translations for 'Title' in listing templates
  CONTRIBUTORS.rst
  wagtail/admin/templates/wagtailadmin/pages/listing/_list_choose.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list_move.html
Labels: type:Bug, component:UI localization, sprint:Cleveland2022

#8013 Fix permission error while sorting pages
  CHANGELOG.txt
  docs/releases/2.16.2.md
  wagtail/actions/move_page.py
  wagtail/admin/tests/pages/test_move_page.py
  wagtail/admin/tests/pages/test_reorder_page.py
Labels: status:Needs Review, component:Page

#8224 Put PR template boilerplate in HTML comment
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:Cleanup/Optimisation, status:Needs Review

#8197 Slim sidebar interactions updates
  client/scss/core.scss
  client/scss/overrides/_vendor.tippy.scss
  client/scss/settings/_variables.scss
  client/src/components/PageExplorer/PageExplorerItem.scss
  client/src/components/Sidebar/Sidebar.scss
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/Sidebar/SidebarPanel.scss
  client/src/components/Sidebar/__snapshots__/Sidebar.test.js.snap
  client/src/components/Sidebar/menu/LinkMenuItem.tsx
  client/src/components/Sidebar/menu/MenuItem.scss
  client/src/components/Sidebar/menu/MenuItem.tsx
  client/src/components/Sidebar/menu/PageExplorerMenuItem.tsx
  client/src/components/Sidebar/menu/SubMenuItem.scss
  client/src/components/Sidebar/menu/SubMenuItem.tsx
  client/src/components/Sidebar/menu/__snapshots__/PageExplorererMenuItem.test.js.snap
  client/src/components/Sidebar/menu/__snapshots__/SubMenuItem.test.js.snap
  client/src/components/Sidebar/modules/MainMenu.scss
  client/src/components/Sidebar/modules/MainMenu.test.js
  client/src/components/Sidebar/modules/MainMenu.tsx
  client/src/components/Sidebar/modules/Search.scss
  client/src/components/Sidebar/modules/Search.tsx
  client/src/components/Sidebar/modules/WagtailBranding.scss
  client/src/components/Sidebar/modules/WagtailBranding.tsx
  client/src/components/Sidebar/modules/WagtailLogo.tsx
  client/src/components/Sidebar/modules/__snapshots__/MainMenu.test.js.snap
  client/tailwind.config.js
  package-lock.json
  package.json
Labels: type:Bug, type:Enhancement, status:Needs Review, status:Needs Work, Accessibility

#8250 Upgrade to curlylint 0.13.1
  setup.py
Labels: type:Cleanup/Optimisation

#8255 Remove description of some-day milestone
  docs/contributing/issue_tracking.md
Labels: Documentation

#8252 Renumber Wagtail 2.17 to 3.0
  CHANGELOG.txt
  client/scss/components/_logo.scss
  docs/reference/pages/model_reference.rst
  docs/reference/pages/panels.rst
  docs/reference/streamfield/blocks.rst
  docs/releases/3.0.md
  docs/releases/index.rst
  docs/releases/upgrading.rst
  docs/topics/pages.md
  wagtail/__init__.py
  wagtail/admin/panels.py
  wagtail/admin/templates/wagtailadmin/base.html
  wagtail/documents/edit_handlers.py
  wagtail/fields.py
  wagtail/images/edit_handlers.py
  wagtail/project_template/requirements.txt
  wagtail/snippets/edit_handlers.py
  wagtail/tests/test_streamfield.py
  wagtail/utils/deprecation.py
Labels: type:Cleanup/Optimisation

#8075 adds instagram reels support
  wagtail/embeds/finders/instagram.py
  wagtail/embeds/tests/test_embeds.py
Labels: status:Needs Review, component:Embeds

#8006 forms - remove unidecode and legacy clean name approach
  docs/releases/3.0.md
  setup.py
  wagtail/contrib/forms/models.py
  wagtail/contrib/forms/tests/test_models.py
  wagtail/contrib/forms/tests/test_views.py
  wagtail/images/models.py
  wagtail/test/testapp/fixtures/test.json
Labels: type:Cleanup/Optimisation, status:Needs Review, component:Form builder
