Repository wagtail/wagtail, pull requests merged in 2022-08, with the labels that each got.

#8104 Fix query search in filtered image admin listing
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/4.0.md
  wagtail/images/tests/test_admin_views.py
  wagtail/images/views/images.py
Labels: status:Needs Review, component:Search, component:Images, GSOC

#8924 Add third party tutorials
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation, status:Needs Review

#8923 Implement combined rich text split and block insertion
  CHANGELOG.txt
  client/src/components/Draftail/index.js
  client/src/components/StreamField/blocks/BaseSequenceBlock.js
  client/src/components/StreamField/blocks/ListBlock.js
  client/src/components/StreamField/blocks/ListBlock.test.js
  client/src/components/StreamField/blocks/StreamBlock.js
  client/src/components/StreamField/blocks/StreamBlock.test.js
  client/src/entrypoints/admin/telepath/widgets.js
  docs/advanced_topics/customisation/admin_templates.md
  docs/releases/4.0.md
Labels: type:Enhancement, component:Streamfield, component:Rich text

#8933 Remove `DeleteMenuItem` in `PageActionMenu`
  wagtail/admin/action_menu.py
Labels: component:Page

#8936 Skip two Axe tests currently timing out
  client/tests/integration/editor.test.js
Labels: Accessibility, Infrastructure

#8930 Implement max length UI for RichTextField, with identical client & server character count. Fix #2268
  CHANGELOG.txt
  client/src/components/Draftail/Draftail.scss
  client/src/components/Draftail/__snapshots__/index.test.js.snap
  client/src/components/Draftail/controls/MaxLength.test.tsx
  client/src/components/Draftail/controls/MaxLength.tsx
  client/src/components/Draftail/index.js
  client/src/components/Draftail/index.test.js
  client/src/entrypoints/admin/telepath/widgets.test.js
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/releases/4.0.md
  wagtail/rich_text/__init__.py
  wagtail/tests/test_rich_text.py
Labels: status:Needs Review, component:Rich text

#8909 Added a forced-color media query to disabled buttons in high contrast
  CHANGELOG.txt
  client/scss/components/_button.scss
  docs/releases/4.0.md
Labels: status:Needs Review, component:Frontend, Accessibility, GSOC

#8945 Allow all CSS system colors in stylesheets without variables usage
  .stylelintrc.js
  CHANGELOG.txt
Labels: type:Cleanup/Optimisation, status:Needs Review, Accessibility

#8919 update can-i-use-lite library for browserslist
  package-lock.json
Labels: status:Needs Review, component:Frontend, dependencies

#8943 4.0 release notes - add GSoC UX Unification section
  docs/releases/4.0.md
Labels: Documentation

#8944 Fixed empty variable issue in header template
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/shared/header.html
Labels: type:Bug, GSOC

#8897 Added border to tooltip dropdown for high contrast
  CHANGELOG.txt
  client/scss/components/_dropdown.scss
  client/scss/overrides/_utilities.dropdowns.scss
  docs/releases/4.0.md
Labels: Accessibility, GSOC

#7148 Decorating RoutablePageMixin routes using path and re_path pattern types
  CHANGELOG.txt
  docs/advanced_topics/formbuilder_routablepage_redirect.md
  docs/reference/contrib/routablepage.md
  docs/releases/4.0.md
  wagtail/contrib/routable_page/models.py
  wagtail/contrib/routable_page/tests.py
  wagtail/test/routablepage/models.py
Labels: component:RoutablePageMixin

#8963 The overflow in the viewport of report filters is fixed Issue#8929
  CHANGELOG.txt
  client/scss/components/_filters.scss
  client/scss/layouts/_report.scss
  docs/releases/4.0.md
  wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
Labels: component:Frontend, component:Reporting

#8951 add documentation for overriding the password reset form content
  docs/advanced_topics/customisation/admin_templates.md
Labels: Documentation, status:Needs Review, component:User Management

#8981 Documentation & code tests - update spelling of colour
  CHANGELOG.txt
  docs/releases/4.0.md
  docs/topics/images.md
  wagtail/contrib/forms/tests/test_forms.py
Labels: Documentation

#8965 Set atomic = False when renaming PageRevision table
  wagtail/migrations/0070_rename_pagerevision_revision.py
Labels: type:Bug, status:Needs Review

#8962 Only use hidden until-found in panels if browsers supports it
  client/src/includes/panels.ts
Labels: status:Needs Review, Release blocker, component:Frontend

#8983 Update InlinePanel and StreamField styles for new designs
  client/scss/_tools.scss
  client/scss/components/_button.scss
  client/scss/components/_chooser.scss
  client/scss/components/_panel.scss
  client/scss/components/forms/_nested-panel.scss
  client/scss/core.scss
  client/scss/tools/_mixins.guide-line.scss
  client/src/components/Draftail/Draftail.scss
  client/src/components/StreamField/StreamField.scss
  client/src/components/StreamField/blocks/BaseSequenceBlock.js
  client/src/components/StreamField/blocks/ListBlock.js
  client/src/components/StreamField/blocks/StreamBlock.js
  client/src/components/StreamField/blocks/StructBlock.js
  client/src/components/StreamField/blocks/__snapshots__/ListBlock.test.js.snap
  client/src/components/StreamField/blocks/__snapshots__/StreamBlock.test.js.snap
  client/src/components/StreamField/blocks/__snapshots__/StructBlock.test.js.snap
  client/src/components/StreamField/scss/components/c-sf-add-button.scss
  client/src/components/StreamField/scss/components/c-sf-add-panel.scss
  client/src/components/StreamField/scss/components/c-sf-block.scss
  client/src/components/StreamField/scss/components/c-sf-button.scss
  client/src/components/StreamField/scss/components/c-sf-container.scss
  client/src/entrypoints/admin/page-editor.js
  client/src/entrypoints/contrib/typed_table_block/__snapshots__/typed_table_block.test.js.snap
  client/src/entrypoints/contrib/typed_table_block/typed_table_block.js
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/reference/pages/panels.md
  docs/topics/pages.md
  wagtail/admin/forms/workflows.py
  wagtail/admin/panels.py
  wagtail/admin/templates/wagtailadmin/icons/bin.svg
  wagtail/admin/templates/wagtailadmin/panels/inline_panel.html
  wagtail/admin/templates/wagtailadmin/panels/inline_panel_child.html
  wagtail/admin/templates/wagtailadmin/shared/panel.html
  wagtail/admin/templates/wagtailadmin/workflows/create.html
  wagtail/admin/templates/wagtailadmin/workflows/edit.html
  wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/includes/searchpromotion_form.html
  wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/includes/searchpromotions_formset.html
  wagtail/test/demosite/models.py
Labels: type:Enhancement, status:Needs Review, Accessibility, component:Design system

#8986 Set BaseSetting deprecation to 5.0
  wagtail/contrib/settings/models.py
Labels: type:Cleanup/Optimisation

#9005 remove stray console-log from page-editor.js
  client/src/entrypoints/admin/page-editor.js
Labels: type:Cleanup/Optimisation

#8993 Fixed console error for breadcrumbs
  client/src/includes/breadcrumbs.js
Labels: component:Frontend, GSOC

#8995 Wagtail 4.0 - Fix various typos and backtick usage in changelog/release notes
  CHANGELOG.txt
  docs/reference/settings.md
  docs/releases/4.0.md
Labels: Documentation, status:Needs Review, Release blocker

#8994 Wagtail 4.0 - Documentation - fix up legacy release note refs & use consistent format
  docs/advanced_topics/embeds.md
  docs/advanced_topics/i18n.md
  docs/contributing/documentation_guidelines.md
  docs/contributing/documentation_modes.md
  docs/contributing/release_process.md
  docs/editor_manual/finding_your_way_around/the_dashboard.md
  docs/extending/rich_text_internals.md
  docs/getting_started/tutorial.md
  docs/reference/contrib/settings.md
  docs/reference/settings.md
  docs/reference/streamfield/blocks.md
  docs/releases/1.10.rst
  docs/releases/1.5.rst
  docs/releases/2.1.rst
  docs/releases/2.15.rst
  docs/topics/writing_templates.md
Labels: Documentation, status:Needs Review, Release blocker

#9003 Add missing chevron-down.svg
  wagtail/admin/static_src/wagtailadmin/images/icons/chevron-down.svg
Labels: status:Needs Review, Release blocker

#9009 Fix DocumentChooserBlock deconstruction for custom document models
  docs/extending/generic_views.md
  docs/reference/viewsets.md
  wagtail/admin/viewsets/chooser.py
  wagtail/documents/blocks.py
Labels: type:Bug, status:Needs Review, Release blocker, component:Streamfield

#9007 Fixed init method of legacy BaseSetting class, fixes #8996, fixes #9006
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/contrib/settings/models.py
Labels: Release blocker, component:Settings

#9011 Use correct classnames for showing/hiding edit button on chooser widget
  CHANGELOG.txt
  client/src/components/ChooserWidget/index.js
  docs/releases/4.0.md
Labels: type:Bug, component:Choosers

#9018 Ensure telepath adapter gets registered for document chooser widget
  docs/reference/viewsets.md
  wagtail/admin/viewsets/chooser.py
  wagtail/documents/views/chooser.py
  wagtail/documents/widgets.py
Labels: type:Bug, status:Needs Review, component:Streamfield, component:Choosers

#9032 Add more items to 4.0 release notes
  CHANGELOG.txt
  docs/releases/4.0.md
Labels: type:Cleanup/Optimisation

#9020 Fix error insertion logic for modal upload forms
  client/src/includes/chooserModal.js
Labels: type:Bug, status:Needs Review, Release blocker, component:Choosers

#9022 Upgrade to latest Draftail RC, fixing command palette selection issue #9017
  package-lock.json
  package.json
Labels: type:Bug, Release blocker, component:Rich text

#9021 Explicitly specify `get_preview_template` and `get_preview_context` parameters
  wagtail/models/__init__.py
  wagtail/test/testapp/models.py
Labels: type:Cleanup/Optimisation, status:Needs Review, component:Preview

#9042 Fix plural handling for "no permission to delete these snippets" errors
  wagtail/snippets/templates/wagtailsnippets/bulk_actions/confirm_bulk_delete.html
  wagtail/snippets/tests/test_bulk_actions/test_bulk_delete.py
Labels: type:Bug, component:i18n

#9041 Fix live preview error banner overlapping with preview mode selector
  client/scss/components/_preview-panel.scss
  wagtail/admin/templates/wagtailadmin/shared/side_panels/preview.html
  wagtail/admin/tests/pages/test_preview.py
  wagtail/snippets/tests/test_preview.py
Labels: component:Preview

#9046 Fix dead Transifex links
  README.md
  docs/contributing/index.md
Labels: Documentation

#9043 added role equal to status to messages
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/base.html
Labels: Accessibility, GSOC

#8973 Fix updatemodulepaths for Python 3.7
  wagtail/bin/wagtail.py
Labels: type:Bug, status:Needs Review

#9051 Update readme screenshot for Wagtail 4.0
  .github/wagtail-screenshot-with-browser.png
Labels: Documentation, status:Needs Review

#9055 backport flake8-print fix to 3.0.x
  scripts/check-translation-strings.py
  scripts/get-translator-credits.py
  scripts/nightly/get_version.py
  scripts/nightly/upload.py
  setup.py
  wagtail/bin/wagtail.py
  wagtail/images/tests/test_management_commands.py
  wagtail/search/backends/database/mysql/query.py
  wagtail/test/benchmark.py
  wagtail/test/settings.py
  wagtail/utils/setup.py
Labels: type:Cleanup/Optimisation

#9037 Add usage guide for using `RevisionMixin`, `DraftStateMixin`, and `PreviewableMixin` with snippets
  docs/reference/pages/model_reference.md
  docs/topics/snippets.md
Labels: Documentation, component:Snippets

#9056 Only show locale filter in choosers when i18n is enabled in settings
  wagtail/admin/views/generic/chooser.py
  wagtail/snippets/tests/test_snippets.py
Labels: type:Bug, status:Needs Review, component:i18n, component:Choosers

#9059 Clear existing preview data on initial load of the create/edit view
  CHANGELOG.txt
  client/src/entrypoints/admin/preview-panel.js
  docs/releases/4.0.md
  wagtail/admin/tests/pages/test_preview.py
  wagtail/admin/views/generic/preview.py
  wagtail/snippets/tests/test_preview.py
Labels: type:Bug, status:Needs Review, component:Preview

#9049 Adjust hoverable area for add block (+) Drafttail editor
  client/src/components/Draftail/Draftail.scss
Labels: component:Streamfield, component:Rich text

#9064 Fixed padding and close button bugs for chooser modal
  CHANGELOG.txt
  client/scss/components/_modals.scss
  client/scss/core.scss
  docs/releases/4.0.md
Labels: component:Frontend, GSOC

#8972 Keyboard support for sort menu order
  CHANGELOG.txt
  CONTRIBUTORS.rst
  wagtail/admin/templates/wagtailadmin/pages/index.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list.html
Labels: component:Frontend, Accessibility, GSOC

#9077 Run collectstatic as part of CI
  .circleci/config.yml
  wagtail/test/settings.py
Labels: type:Enhancement, status:Needs Review, Infrastructure

#9079 Mention WAGTAILADMIN_RICH_TEXT_EDITORS on admin customization page.
  docs/advanced_topics/customisation/page_editing_interface.md
Labels: Documentation, component:Rich text

#9076 Fix FieldBlocks commenting
  client/src/entrypoints/admin/comments.js
Labels: Release blocker, component:Streamfield, component:Commenting

#9069 Add some missing translated labels to the bulk actions
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/documents/views/bulk_actions/add_tags.py
  wagtail/documents/views/bulk_actions/add_to_collection.py
  wagtail/images/views/bulk_actions/add_tags.py
  wagtail/images/views/bulk_actions/add_to_collection.py
Labels: component:UI localization, component:Bulk Actions

#9061 Optimise userbar
  CHANGELOG.txt
  docs/releases/4.1.md
  wagtail/admin/templatetags/wagtailuserbar.py
  wagtail/admin/tests/test_userbar.py
Labels: Performance, component:Userbar

#9084 Clean up - spelling of multi-site
  CHANGELOG.txt
  docs/editor_manual/managing_redirects.md
  docs/reference/contrib/settings.md
  docs/releases/2.14.rst
  wagtail/contrib/settings/tests/site_specific/test_templates.py
  wagtail/test/demosite/fixtures/demosite.json
Labels: Documentation, type:Cleanup/Optimisation

#9085 Centered spinner icon and signing in text for login page
  client/scss/layouts/_login.scss
Labels: component:User Management, GSOC

#9087 fix styling regression for pagination (search results) in dark mode
  docs/_static/css/pagination.css
Labels: Documentation

#9100 Release note for snippet preview/revisions
  CHANGELOG.txt
  docs/releases/4.0.md
Labels: Documentation

#9044 Removed legacy unbutton styles
  CHANGELOG.txt
  client/scss/components/_button.scss
  docs/releases/4.1.md
Labels: type:Cleanup/Optimisation, component:Design system

#9080 Added buttons to pattern library
  CHANGELOG.txt
  docs/releases/4.1.md
  wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx
Labels: component:Frontend, GSOC

#9109 4.0 release notes - fix layout of UX Unification section
  docs/releases/4.0.md
Labels: Documentation

#9094 moving branding_title to the end of page title for admin users
  CHANGELOG.txt
  client/tests/integration/groups.test.js
  client/tests/integration/listing.test.js
  docs/releases/4.1.md
  wagtail/admin/templates/wagtailadmin/skeleton.html
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/pages/test_preview.py
  wagtail/snippets/tests/test_preview.py
Labels: Accessibility
