Repository wagtail/wagtail, pull requests merged in 2022-01, with the labels that each got.

#7723 Implement DeletePageAction and admin API for deleting pages
  wagtail/admin/api/actions/delete.py
  wagtail/admin/api/views.py
  wagtail/admin/tests/api/test_pages.py
  wagtail/admin/views/pages/delete.py
  wagtail/core/actions/delete_page.py
  wagtail/core/models/__init__.py
Labels: status:Needs Review, component:API

#7674 Documentation - Update blocks.rst to include `rows` kwarg for TextBlock
  docs/reference/streamfield/blocks.rst
Labels: Documentation, status:Needs Review, component:Streamfield

#7570 add check for correct search_fields on pages
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/search/apps.py
  wagtail/search/checks.py
  wagtail/search/tests/test_indexed_class.py
Labels: status:Needs Review, component:Search

#7779 Fixes #6618: Modify responsive setting for buttons on mobile
  CHANGELOG.txt
  client/scss/components/_button.scss
  docs/releases/2.16.md
Labels: status:Needs Review, component:Frontend, component:Panels

#7775 Fixes #7019: Change the padding to 0.75rem
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/src/components/Draftail/Draftail.scss
  docs/releases/2.16.md
Labels: status:Needs Review, component:Frontend, component:Page

#7803 feature: Login remember me functionality
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/admin/forms/auth.py
  wagtail/admin/templates/wagtailadmin/login.html
  wagtail/admin/tests/test_views.py
  wagtail/admin/views/account.py
Labels: status:Needs Review, component:User Management

#7765 Remove deprecated chooser panel templates
  wagtail/admin/templates/wagtailadmin/edit_handlers/chooser_panel.html
  wagtail/admin/templates/wagtailadmin/edit_handlers/page_chooser_panel.html
  wagtail/documents/templates/wagtaildocs/edit_handlers/document_chooser_panel.html
  wagtail/images/templates/wagtailimages/edit_handlers/image_chooser_panel.html
  wagtail/snippets/templates/wagtailsnippets/edit_handlers/snippet_chooser_panel.html
Labels: type:Cleanup/Optimisation

#7707 Implement MovePageAction and admin API for moving pages
  wagtail/admin/api/actions/move.py
  wagtail/admin/api/views.py
  wagtail/admin/tests/api/test_pages.py
  wagtail/admin/views/pages/move.py
  wagtail/core/actions/copy_page.py
  wagtail/core/actions/move_page.py
  wagtail/core/models/__init__.py
Labels: status:Needs Review, component:Page

#7663 Fixes #7241 and improves error visibility in high-contrast
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/scss/components/_forms.scss
  client/scss/settings/_variables.scss
  docs/releases/2.16.md
Labels: status:Needs Review, Accessibility, hacktoberfest-accepted

#5793 #5269 improve implementations of visually-hidden text in explorer and main menu toggle
  CHANGELOG.txt
  client/scss/components/_button.scss
  client/scss/components/_main-nav.scss
  docs/releases/2.16.md
  wagtail/admin/templates/wagtailadmin/base.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_navigation_explore.html
Labels: type:Cleanup/Optimisation, component:Frontend, Accessibility

#7858 Update browser support targets following UI team discussion
  docs/contributing/developing.rst
Labels: type:Enhancement, Documentation, status:Needs Review

#7855 Make API representation of Page.alias_of more consistent
  wagtail/admin/tests/api/test_pages.py
  wagtail/api/v2/serializers.py
  wagtail/api/v2/tests/test_pages.py
Labels: Release blocker

#7568 modal-workflow - block additional opens & add trigger focus management
  CHANGELOG.txt
  client/src/entrypoints/admin/__snapshots__/modal-workflow.test.js.snap
  client/src/entrypoints/admin/modal-workflow.js
  client/src/entrypoints/admin/modal-workflow.test.js
  docs/releases/2.16.md
Labels: Accessibility

#7833 rename admin/expanding-formset.js (using kebab-case file)
  CHANGELOG.txt
  client/src/entrypoints/admin/expanding-formset.js
  client/src/entrypoints/admin/expanding-formset.test.js
  client/webpack.config.js
  docs/releases/2.16.md
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/users/templates/wagtailusers/groups/includes/group_form_js.html
Labels: type:Cleanup/Optimisation, status:Needs Review, javascript

#7670 TypedTableBlock: Add borders to help visualize rows and columns
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/contrib/typed_table_block/static_src/typed_table_block/scss/typed_table_block.scss
Labels: status:Needs Review, component:Streamfield

#7764 Set default submit button label on generic create views to 'Create' instead of 'Save'
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/admin/templates/wagtailadmin/generic/form.html
  wagtail/admin/views/generic/models.py
Labels: type:Enhancement

#7649 Fix gulp watch to correctly watch files
  CHANGELOG.txt
  docs/releases/2.16.md
  gulpfile.js/tasks/watch.js
Labels: status:Needs Review, component:Frontend, hacktoberfest-accepted, javascript

#7832 Render horizontal listing as a flex container
  CHANGELOG.txt
  client/scss/components/_listing.scss
  docs/releases/2.16.md
Labels: type:Cleanup/Optimisation, status:Needs Review, component:Images, component:Frontend

#7653 Fixes #7450 Issues with Dropdowns in High contrast mode
  CHANGELOG.txt
  client/scss/components/_dropdown.legacy.scss
  docs/releases/2.16.md
Labels: status:Needs Review, Accessibility, hacktoberfest-accepted

#7826 Fix: Incorrect logging of 'move' actions as 'reorder' when the target is an intended sibling
  CHANGELOG.txt
  docs/releases/2.16.md
  wagtail/core/actions/move_page.py
  wagtail/core/tests/test_audit_log.py
Labels: status:Needs Review, component:Audit logging

#7867 Add locale selector on forms index
  wagtail/contrib/forms/templates/wagtailforms/index.html
  wagtail/contrib/forms/tests/test_views.py
  wagtail/contrib/forms/views.py
Labels: status:Needs Review, component:i18n

#7862 Add locale switcher in the page chooser
  client/scss/components/_status-tag.scss
  client/src/entrypoints/admin/page-chooser-modal.js
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/admin/templates/wagtailadmin/shared/chooser_breadcrumb.html
  wagtail/admin/tests/test_page_chooser.py
  wagtail/admin/views/chooser.py
Labels: status:Needs Review, component:i18n

#7757 Implement CopyForTranslationAction and add Admin API to submit page translations
  wagtail/admin/api/actions/copy_for_translation.py
  wagtail/admin/api/views.py
  wagtail/admin/tests/api/test_pages.py
  wagtail/contrib/simple_translation/tests/test_views.py
  wagtail/contrib/simple_translation/views.py
  wagtail/core/actions/copy_for_translation.py
  wagtail/core/models/__init__.py
  wagtail/core/tests/test_page_model.py
Labels: status:Needs Review, component:API

#6857 Change webmaster to admin
  CHANGELOG.txt
  docs/reference/settings.rst
  docs/releases/2.16.md
  wagtail/admin/mail.py
  wagtail/admin/views/workflows.py
  wagtail/documents/views/chooser.py
  wagtail/images/templates/wagtailimages/multiple/add.html
  wagtail/images/views/chooser.py
Labels: type:Enhancement

#7869 update documentation - third party tutorials
  docs/advanced_topics/third_party_tutorials.md
  docs/advanced_topics/third_party_tutorials.rst
Labels: Documentation

#7829 Django 4.0 support
  .github/workflows/test.yml
  CHANGELOG.txt
  README.md
  docs/getting_started/integrating_into_django.md
  docs/releases/2.16.md
  docs/releases/upgrading.rst
  setup.py
  tox.ini
  wagtail/project_template/requirements.txt
Labels: type:Bug, type:Cleanup/Optimisation, status:Needs Review, Compatibility

#7877 Update test_account_management.py
  wagtail/admin/tests/test_account_management.py
Labels: status:Needs Work

#7885 hooks - update unnecessary format_html to mark_safe
  docs/reference/hooks.rst
Labels: Documentation, status:Needs Review

#7893 Fix Sqlite FTS5 compatibility check
  wagtail/search/backends/database/sqlite/utils.py
Labels: type:Bug
