Repository wagtail/wagtail, pull requests merged in 2022-07, with the labels that each got.

#8794 fix - ensure tooltips get re-initialised (for human-readable-date widget)
  client/src/entrypoints/admin/core.js
  client/src/includes/chooserModal.js
Labels: component:Frontend

#8793 Documentation - upgrading - fix formatting issue
  docs/releases/upgrading.md
Labels: Documentation

#8789 Remove outdated references to old db search backend in docs
  docs/topics/search/backends.md
  docs/topics/search/indexing.md
Labels: Documentation, component:Search

#8780 Add ID for "non-existent field" system check
  wagtail/search/index.py
  wagtail/search/tests/test_indexed_class.py
Labels: type:Bug, status:Needs Review, component:Search

#8801 Bump beautifulsoup4 to 4.11.x
  setup.py
Labels: type:Cleanup/Optimisation

#8623 Add breadcrumbs and new Page Editor side panels to Snippets views
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/shared/headers/page_create_header.html
  wagtail/admin/templates/wagtailadmin/shared/headers/page_edit_header.html
  wagtail/admin/templates/wagtailadmin/shared/side_panel_toggles.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/status/locale.html
  wagtail/admin/ui/side_panels.py
  wagtail/admin/views/generic/models.py
  wagtail/snippets/side_panels.py
  wagtail/snippets/templates/wagtailsnippets/snippets/create.html
  wagtail/snippets/templates/wagtailsnippets/snippets/edit.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/_base_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/create_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/edit_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/history_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/list_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/headers/usage_header.html
  wagtail/snippets/templates/wagtailsnippets/snippets/history.html
  wagtail/snippets/templates/wagtailsnippets/snippets/side_panels/includes/status/workflow.html
  wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html
  wagtail/snippets/templates/wagtailsnippets/snippets/usage.html
  wagtail/snippets/tests.py
  wagtail/snippets/views/snippets.py
Labels: status:Needs Work, component:Snippets

#8802 Introduce new template fragment composition tags: BlockInclusionNode and fragment
  .circleci/config.yml
  CHANGELOG.txt
  Makefile
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/home.html
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
  wagtail/admin/templates/wagtailadmin/shared/dialog/end_dialog.html
  wagtail/admin/templates/wagtailadmin/shared/help_block.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: type:Enhancement, component:Design system

#8748 utils/text - move cleanForSlug into same file & add tests/jsdoc
  client/src/entrypoints/admin/page-editor.js
  client/src/utils/cleanForSlug.js
  client/src/utils/cleanForSlug.test.js
  client/src/utils/text.test.js
  client/src/utils/text.ts
Labels: type:Cleanup/Optimisation, status:Needs Review, component:Frontend

#8750 cleanup - add `noop` function for common use case
  client/src/components/Button/Button.test.js
  client/src/components/Draftail/CommentableEditor/CommentableEditor.test.tsx
  client/src/components/Draftail/blocks/EmbedBlock.test.js
  client/src/components/Sidebar/index.tsx
  client/src/components/StreamField/blocks/StaticBlock.test.js
  client/src/components/StreamField/blocks/__snapshots__/StaticBlock.test.js.snap
  client/src/entrypoints/admin/modal-workflow.js
  client/src/utils/noop.test.js
  client/src/utils/noop.ts
Labels: component:Frontend

#8764 clean up - remove needless stylelint disables
  client/scss/components/_button.scss
  client/scss/components/_icons.scss
  client/src/components/Sidebar/menu/MenuItem.scss
  client/src/components/Sidebar/modules/WagtailBranding.scss
  wagtail/admin/static_src/wagtailadmin/scss/userbar.scss
Labels: type:Cleanup/Optimisation, component:Frontend

#8327 Add generic settings to compliment site-specific settings
  docs/reference/contrib/index.rst
  docs/reference/contrib/settings.md
  wagtail/contrib/settings/apps.py
  wagtail/contrib/settings/context_processors.py
  wagtail/contrib/settings/jinja2tags.py
  wagtail/contrib/settings/models.py
  wagtail/contrib/settings/registry.py
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
  wagtail/contrib/settings/templatetags/wagtailsettings_tags.py
  wagtail/contrib/settings/tests/__init__.py
  wagtail/contrib/settings/tests/generic/__init__.py
  wagtail/contrib/settings/tests/generic/base.py
  wagtail/contrib/settings/tests/generic/test_admin.py
  wagtail/contrib/settings/tests/generic/test_model.py
  wagtail/contrib/settings/tests/generic/test_register.py
  wagtail/contrib/settings/tests/generic/test_templates.py
  wagtail/contrib/settings/tests/site_specific/__init__.py
  wagtail/contrib/settings/tests/site_specific/base.py
  wagtail/contrib/settings/tests/site_specific/test_admin.py
  wagtail/contrib/settings/tests/site_specific/test_forms.py
  wagtail/contrib/settings/tests/site_specific/test_model.py
  wagtail/contrib/settings/tests/site_specific/test_register.py
  wagtail/contrib/settings/tests/site_specific/test_templates.py
  wagtail/contrib/settings/urls.py
  wagtail/contrib/settings/views.py
  wagtail/test/testapp/migrations/0002_recreate_setting_models.py
  wagtail/test/testapp/models.py
Labels: type:Enhancement, type:Cleanup/Optimisation, status:Needs Review, component:Settings

#8719 Progressbar made visible in high contrast
  CHANGELOG.txt
  client/scss/components/_progressbar.scss
  docs/releases/4.0.md
Labels: Accessibility, GSOC

#8718 #8334 - chechbox visible in high contrast
  CHANGELOG.txt
  client/scss/elements/_forms.scss
  docs/releases/4.0.md
Labels: status:Needs Review, Accessibility, GSOC

#8806 Add new Draftail inline toolbar and command palette
  CHANGELOG.txt
  client/src/components/Draftail/CommentableEditor/CommentableEditor.scss
  client/src/components/Draftail/CommentableEditor/CommentableEditor.tsx
  client/src/components/Draftail/Draftail.scss
  client/src/components/Draftail/__snapshots__/index.test.js.snap
  client/src/components/Draftail/index.js
  docs/releases/4.0.md
  package-lock.json
  package.json
  wagtail/admin/templates/wagtailadmin/icons/bold.svg
  wagtail/admin/templates/wagtailadmin/icons/comment-large-outline.svg
  wagtail/admin/templates/wagtailadmin/icons/comment-large-reversed.svg
  wagtail/admin/templates/wagtailadmin/icons/comment-large.svg
  wagtail/admin/templates/wagtailadmin/icons/h1.svg
  wagtail/admin/templates/wagtailadmin/icons/h2.svg
  wagtail/admin/templates/wagtailadmin/icons/h3.svg
  wagtail/admin/templates/wagtailadmin/icons/h4.svg
  wagtail/admin/templates/wagtailadmin/icons/h5.svg
  wagtail/admin/templates/wagtailadmin/icons/h6.svg
  wagtail/admin/templates/wagtailadmin/icons/italic.svg
  wagtail/admin/templates/wagtailadmin/icons/link.svg
  wagtail/admin/templates/wagtailadmin/icons/list-ol.svg
  wagtail/admin/templates/wagtailadmin/icons/list-ul.svg
  wagtail/admin/wagtail_hooks.py
  wagtail/documents/wagtail_hooks.py
Labels: type:Enhancement, component:Rich text

#8832 Remove button-group component
  CHANGELOG.txt
  client/scss/components/_button.scss
  docs/releases/4.0.md
  wagtail/contrib/modeladmin/templates/modeladmin/inspect.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: type:Enhancement, component:Design system

#8671 Implement new preview panel in page editor
  CHANGELOG.txt
  client/scss/components/_preview-error.scss
  client/scss/components/_preview-panel.scss
  client/scss/core.scss
  client/scss/layouts/_page-editor.scss
  client/src/entrypoints/admin/page-editor.js
  client/src/entrypoints/admin/preview-panel.js
  client/webpack.config.js
  docs/reference/settings.md
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/icons/desktop.svg
  wagtail/admin/templates/wagtailadmin/icons/rotate.svg
  wagtail/admin/templates/wagtailadmin/icons/tablet-alt.svg
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/admin/templates/wagtailadmin/pages/_preview_button_on_create.html
  wagtail/admin/templates/wagtailadmin/pages/_preview_button_on_edit.html
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/pages/preview_error.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/preview.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/status.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/templatetags/wagtailuserbar.py
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/pages/test_preview.py
  wagtail/admin/ui/side_panels.py
  wagtail/admin/views/pages/create.py
  wagtail/admin/views/pages/edit.py
  wagtail/admin/views/pages/preview.py
  wagtail/admin/views/pages/revisions.py
  wagtail/admin/wagtail_hooks.py
  wagtail/utils/decorators.py
Labels: type:Enhancement, component:Page, component:Preview

#8856 Test Django main against git master of django-rest-framework
  .github/workflows/test.yml
Labels: type:Cleanup/Optimisation

#8178 Added pagination to docs search results page
  docs/_static/css/pagination.css
  docs/_templates/layout.html
  docs/_templates/search.html
Labels: type:Enhancement, Documentation, status:Needs Review

#8167 Display data for Twitter embed blocks
  CHANGELOG.txt
  client/src/components/Draftail/blocks/EmbedBlock.js
  client/src/components/Draftail/blocks/MediaBlock.js
  client/src/components/Draftail/blocks/MediaBlock.scss
  client/src/components/Draftail/blocks/MediaBlock.test.js
  client/src/components/Draftail/blocks/__snapshots__/EmbedBlock.test.js.snap
  client/src/components/Draftail/blocks/__snapshots__/ImageBlock.test.js.snap
  client/src/components/Draftail/blocks/__snapshots__/MediaBlock.test.js.snap
  client/src/components/Draftail/decorators/TooltipEntity.js
  docs/releases/4.0.md
Labels: type:Enhancement, component:Embeds, GSOC

#8757 Attempting to fix SQLite errors in Squash deployments by updating Docker image
  .squash.yml
Labels: Compatibility

#8852 Removed the forced-colors media query over icons to avoid override
  CHANGELOG.txt
  client/scss/components/_icons.scss
  docs/releases/4.0.md
Labels: type:Bug, Accessibility, GSOC, component:Design system

#8849 adopted shared header for redirect page
  CHANGELOG.txt
  client/scss/layouts/_redirects.scss
  docs/releases/4.0.md
  wagtail/contrib/redirects/templates/wagtailredirects/index.html
Labels: type:Cleanup/Optimisation, GSOC, component:Design system

#8850 adopted shared header template in workflows
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/workflows/index.html
  wagtail/admin/templates/wagtailadmin/workflows/task_index.html
Labels: type:Cleanup/Optimisation, GSOC, component:Design system

#8854 Adopted shared header for menu settings editing view
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
Labels: type:Enhancement, GSOC

#8847 Use dialog component for privacy settings
  CHANGELOG.txt
  client/scss/components/_dialog.scss
  client/scss/layouts/_page-editor.scss
  client/src/entrypoints/admin/modal-workflow.js
  client/src/entrypoints/admin/privacy-switch.js
  client/src/includes/dialog.js
  docs/releases/4.0.md
  wagtail/admin/panels.py
  wagtail/admin/templates/wagtailadmin/collection_privacy/set_privacy.html
  wagtail/admin/templates/wagtailadmin/collections/_privacy_switch.html
  wagtail/admin/templates/wagtailadmin/page_privacy/set_privacy.html
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/admin/templates/wagtailadmin/pages/_privacy_switch.html
  wagtail/admin/templates/wagtailadmin/pages/privacy_switch_panel.html
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/status/privacy.html
  wagtail/admin/tests/test_privacy.py
Labels: type:Enhancement, Accessibility, component:Page, component:Collections

#8792 Adopted slim header in page listing views
  CHANGELOG.txt
  client/scss/components/_listing.scss
  client/scss/core.scss
  client/scss/layouts/_form-side.scss
  client/scss/layouts/_page-editor.scss
  client/src/entrypoints/admin/wagtailadmin.js
  client/src/includes/sidePanel.js
  docs/reference/hooks.md
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/pages/_privacy_switch.html
  wagtail/admin/templates/wagtailadmin/pages/index.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list_explore.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list_move.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_navigation_move.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_explore.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_move.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_parent_page_title_explore.html
  wagtail/admin/templates/wagtailadmin/pages/page_listing_header.html
  wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.html
  wagtail/admin/tests/pages/test_explorer_view.py
  wagtail/admin/tests/test_buttons_hooks.py
  wagtail/admin/tests/test_page_chooser.py
  wagtail/admin/tests/test_privacy.py
  wagtail/admin/views/pages/listing.py
  wagtail/admin/wagtail_hooks.py
Labels: type:Enhancement, GSOC, component:Design system

#8862 Adopt shared header in Form submissions listing
  CHANGELOG.txt
  client/scss/components/_forms.scss
  client/scss/layouts/_report.scss
  docs/releases/4.0.md
  wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
  wagtail/contrib/forms/tests/test_views.py
  wagtail/contrib/forms/views.py
Labels: status:Needs Work, component:Frontend, component:Form builder, GSOC

#8871 Add styling for Django 4 div-based radio buttons markup
  CHANGELOG.txt
  client/scss/layouts/_modeladmin-choose-parent-page.scss
  docs/releases/4.0.md
Labels: component:Frontend

#8853 Contrast themes: help block border styles
  CHANGELOG.txt
  client/scss/components/_help-block.scss
  docs/releases/4.0.md
Labels: type:Bug, Accessibility, GSOC

#8861 replaced latin abbreviations with english phrases
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/src/entrypoints/admin/core.js
  client/src/entrypoints/admin/telepath/blocks.js
  docs/_templates/layout.html
  docs/advanced_topics/api/v2/configuration.md
  docs/advanced_topics/boundblocks_and_values.md
  docs/advanced_topics/deploying.md
  docs/advanced_topics/embeds.md
  docs/advanced_topics/i18n.md
  docs/advanced_topics/images/custom_image_model.md
  docs/advanced_topics/images/feature_detection.md
  docs/advanced_topics/images/image_serve_view.md
  docs/conf.py
  docs/contributing/general_guidelines.md
  docs/contributing/issue_tracking.md
  docs/contributing/release_process.md
  docs/editor_manual/copying_aliasing_existing_pages.md
  docs/editor_manual/getting_started.md
  docs/editor_manual/new_pages/inserting_images.md
  docs/editor_manual/new_pages/the_promote_tab.md
  docs/extending/audit_log.md
  docs/extending/custom_tasks.md
  docs/extending/customising_group_views.md
  docs/extending/extending_draftail.md
  docs/extending/rich_text_internals.md
  docs/getting_started/tutorial.md
  docs/reference/contrib/forms/customisation.md
  docs/reference/contrib/frontendcache.rst
  docs/reference/contrib/modeladmin/create_edit_delete_views.md
  docs/reference/contrib/modeladmin/tips_and_tricks/reversing_urls.md
  docs/reference/contrib/settings.md
  docs/reference/hooks.md
  docs/reference/pages/model_reference.rst
  docs/reference/settings.md
  docs/reference/streamfield/blocks.md
  docs/releases/4.0.md
  docs/topics/images.md
  docs/topics/pages.md
  docs/topics/search/backends.md
  docs/topics/writing_templates.md
  wagtail/admin/forms/collections.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/test_widgets.py
  wagtail/coreutils.py
  wagtail/whitelist.py
Labels: Documentation, type:Cleanup/Optimisation

#8870 Slim header- redundant styles cleanup
  client/scss/components/_form-side.scss
  client/scss/components/_listing.scss
  client/scss/core.scss
Labels: type:Cleanup/Optimisation, component:Frontend, GSOC

#8876 Fix - Remove duplicate custom bulk actions docs
  docs/extending/custom_bulk_actions.md
  docs/extending/custom_bulk_actions.rst
Labels: Documentation, component:Snippets, component:Bulk Actions

#8877 documentation - fix table of contents issue for pages reference
  docs/reference/pages/index.md
Labels: Documentation

#8735 Shortcut for accessing StreamField blocks by block name/type
  CHANGELOG.txt
  docs/releases/4.0.md
  docs/topics/streamfield.md
  wagtail/blocks/stream_block.py
  wagtail/tests/test_blocks.py
Labels: type:Enhancement, status:Needs Review, component:Streamfield

#8878 documentation - fix a few internal references
  docs/advanced_topics/multi_site_multi_instance_multi_tenancy.md
  docs/reference/contrib/settings.md
Labels: Documentation

#8881 Convert reference pages documentation section to Markdown
  docs/reference/contrib/sitemaps.rst
  docs/reference/pages/model_recipes.md
  docs/reference/pages/model_recipes.rst
  docs/reference/pages/model_reference.md
  docs/reference/pages/queryset_reference.md
Labels: Documentation, type:Cleanup/Optimisation, status:Needs Review, component:Page

#8875 Add bottom border to messages. Fixes #8836
  CHANGELOG.txt
  client/scss/components/_messages.scss
  docs/releases/4.0.md
Labels: component:Frontend, Accessibility, GSOC

#8874 Add a border around modal dialogs so they can be identified in forced colors mode. Fixes #8833
  client/scss/components/_dialog.scss
Labels: status:Needs Review, component:Frontend, GSOC

#8899 add links to styleguide help blocks for easier validation
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: status:Needs Review, component:Design system

#8896 Updated help block colors
  CHANGELOG.txt
  client/scss/components/_help-block.scss
  docs/releases/4.0.md
Labels: component:Frontend, GSOC

#8895 Added translate button to header actions dropdown along with some cleanup
  CHANGELOG.txt
  docs/reference/contrib/modeladmin/tips_and_tricks/reversing_urls.md
  docs/reference/hooks.md
  docs/releases/4.0.md
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/test_buttons_hooks.py
  wagtail/admin/wagtail_hooks.py
  wagtail/admin/widgets/button.py
  wagtail/contrib/simple_translation/wagtail_hooks.py
  wagtail/test/testapp/wagtail_hooks.py
Labels: status:Needs Review, GSOC

#8904 Adopted non collapsible breadcrumbs for root page
  wagtail/admin/templates/wagtailadmin/pages/page_listing_header.html
Labels: status:Needs Review, component:Frontend, component:Page, GSOC

#8908 Ensure consistent sidebar icon position whether expanded or collapsed
  CHANGELOG.txt
  client/src/components/Sidebar/Sidebar.scss
  client/src/components/Sidebar/menu/MenuItem.scss
  docs/releases/4.0.md
Labels: component:Frontend, component:Menu

#8920 Updated page listings header to new designs
  wagtail/admin/templates/wagtailadmin/pages/page_listing_header.html
Labels: status:Needs Review, component:Frontend, GSOC
