Repository wagtail/wagtail, pull requests merged in 2022-05, with the labels that each got.

#8451 Fix test migrations for django-taggit 3.0.0
  .github/workflows/test.yml
  setup.py
  wagtail/test/testapp/migrations/0047_restaurant_tags.py
  wagtail/test/testapp/migrations/0051_tag_verbose_name.py
Labels: type:Cleanup/Optimisation, component:Tagging

#8175 InlinePanel.get_comparison passes label as field_label
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/compare.py
  wagtail/admin/panels.py
  wagtail/admin/tests/test_compare.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: status:Needs Review, component:Model Cluster, component:Audit logging

#8467 Add margin to icons in footer actions menu
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
Labels: type:Bug, status:Needs Review

#8492 Hide side_panel_button if empty
  wagtail/admin/templates/wagtailadmin/pages/side_panels/includes/side_panel_button.html
Labels: component:Frontend, component:Panels

#8468 Switch locales selector JS error
  client/src/includes/initTooltips.js
Labels: component:i18n, component:Frontend

#8486 Add Wagtail 3 classifier to documentation
  docs/contributing/index.rst
Labels: Documentation, status:Needs Review, Compatibility

#8469 Update workflow state icon, add workflow state requested by user name
  wagtail/admin/templates/wagtailadmin/pages/side_panels/includes/page_workflow_status.html
  wagtail/admin/tests/test_workflows.py
Labels: status:Needs Work, component:Workflow

#8516 Make nested list render as a nested list
  docs/extending/forms.md
Labels: Documentation, status:Needs Review, component:Form builder

#8518 Disable webpack css url rewriting
  CHANGELOG.txt
  client/webpack.config.js
  docs/releases/3.0.md
Labels: status:Needs Review, Release blocker, component:Frontend

#8497 Remove legacy physical positioning CSS
  CHANGELOG.txt
  client/scss/components/_button.scss
  client/scss/components/_dropdown.legacy.scss
  client/scss/components/_footer.scss
  client/scss/components/_forms.scss
  client/scss/components/_header.scss
  client/scss/components/_help-block.scss
  client/scss/components/_listing.scss
  client/scss/components/_loading-mask.scss
  client/scss/components/_modals.scss
  client/scss/components/_skiplink.scss
  client/scss/components/_tooltips.scss
  client/scss/elements/_elements.scss
  client/scss/elements/_forms.scss
  client/scss/objects/_avatar.scss
  client/scss/overrides/_utilities.dropdowns.scss
  client/scss/overrides/_vendor.datetimepicker.scss
  client/src/components/CommentApp/components/Comment/style.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  client/src/components/CommentApp/main.scss
  client/src/components/Draftail/Tooltip/Tooltip.js
  client/src/components/Draftail/Tooltip/Tooltip.scss
  client/src/components/Draftail/Tooltip/__snapshots__/Tooltip.test.js.snap
  client/src/components/Draftail/blocks/MediaBlock.scss
  client/src/components/Draftail/blocks/__snapshots__/MediaBlock.test.js.snap
  client/src/components/PageExplorer/PageExplorer.scss
  client/src/components/Sidebar/Sidebar.scss
  client/src/components/Sidebar/SidebarPanel.scss
  client/src/components/Sidebar/menu/MenuItem.scss
  client/src/components/Sidebar/menu/SubMenuItem.scss
  client/tailwind.config.js
  docs/contributing/developing.md
  docs/releases/4.0.md
  package-lock.json
  package.json
  wagtail/admin/static_src/wagtailadmin/scss/layouts/404.scss
  wagtail/admin/static_src/wagtailadmin/scss/layouts/home.scss
  wagtail/admin/static_src/wagtailadmin/scss/layouts/login.scss
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/admin/static_src/wagtailadmin/scss/userbar.scss
  wagtail/contrib/typed_table_block/static_src/typed_table_block/scss/typed_table_block.scss
  wagtail/documents/static_src/wagtaildocs/scss/add-multiple.scss
  wagtail/images/static_src/wagtailimages/scss/add-multiple.scss
  wagtail/project_template/home/static/css/welcome_page.css
Labels: type:Cleanup/Optimisation, component:i18n

#8524 fix issue with image model docstrings
  wagtail/images/models.py
Labels: Documentation, status:Needs Review, component:Images

#8315 Use FormData for docs/images add-multiple's edit handling
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/documents/static_src/wagtaildocs/js/add-multiple.js
  wagtail/images/static_src/wagtailimages/js/add-multiple.js
Labels: status:Needs Review, component:Images, component:Documents

#8416 Cleanup - english spelling not us spelling in documentation
  CHANGELOG.txt
  SPONSORS.md
  client/scss/core.scss
  docs/advanced_topics/accessibility_considerations.rst
  docs/advanced_topics/add_to_django_project.rst
  docs/advanced_topics/customisation/admin_templates.rst
  docs/advanced_topics/images/image_file_formats.rst
  docs/advanced_topics/multi_site_multi_instance_multi_tenancy.rst
  docs/advanced_topics/third_party_tutorials.md
  docs/conf.py
  docs/contributing/ui_guidelines.md
  docs/extending/customising_group_views.rst
  docs/getting_started/tutorial.md
  docs/reference/contrib/modeladmin/indexview.rst
  docs/reference/contrib/settings.rst
  docs/reference/pages/index.rst
  docs/reference/pages/model_recipes.rst
  docs/reference/pages/panels.md
  docs/reference/pages/theory.rst
  docs/releases/1.0.rst
  docs/releases/2.0.rst
  docs/releases/2.1.rst
  docs/releases/2.12.rst
  docs/releases/2.15.rst
  docs/releases/2.16.md
  docs/releases/2.6.rst
  docs/releases/2.7.rst
  docs/topics/images.rst
  docs/topics/snippets.rst
  wagtail/admin/urls/__init__.py
  wagtail/contrib/settings/registry.py
Labels: Documentation, type:Cleanup/Optimisation

#8343 Add instructions about where to find cloudflare zone id
  docs/reference/contrib/frontendcache.rst
Labels: Documentation, status:Needs Review

#8387 chore(ci): add informational Codecov status checks
  CHANGELOG.txt
  CONTRIBUTORS.rst
  codecov.yml
  docs/releases/4.0.md
Labels: Infrastructure

#8529 Make 'upload one now' link on document chooser work after results refresh
  client/src/entrypoints/admin/task-chooser-modal.js
  client/src/entrypoints/documents/document-chooser-modal.js
Labels: type:Bug, component:Choosers

#8526 Change description text for switch locales
  wagtail/admin/side_panels.py
  wagtail/admin/templates/wagtailadmin/pages/side_panels/includes/page_locale_status.html
Labels: component:i18n

#8441 Replace `PageRevision` with generic `Revision` model
  CHANGELOG.txt
  docs/reference/pages/model_reference.rst
  docs/reference/signals.rst
  docs/releases/4.0.md
  wagtail/actions/copy_page.py
  wagtail/actions/publish_page_revision.py
  wagtail/actions/revert_to_page_revision.py
  wagtail/admin/api/actions/revert_to_page_revision.py
  wagtail/admin/mail.py
  wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html
  wagtail/admin/templates/wagtailadmin/home/workflow_pages_to_moderate.html
  wagtail/admin/templates/wagtailadmin/notifications/approved.html
  wagtail/admin/templates/wagtailadmin/notifications/approved.txt
  wagtail/admin/templates/wagtailadmin/notifications/approved_subject.txt
  wagtail/admin/templates/wagtailadmin/notifications/rejected.html
  wagtail/admin/templates/wagtailadmin/notifications/rejected.txt
  wagtail/admin/templates/wagtailadmin/notifications/rejected_subject.txt
  wagtail/admin/templates/wagtailadmin/notifications/submitted.html
  wagtail/admin/templates/wagtailadmin/notifications/submitted.txt
  wagtail/admin/templates/wagtailadmin/notifications/submitted_subject.txt
  wagtail/admin/templatetags/wagtailuserbar.py
  wagtail/admin/tests/api/test_pages.py
  wagtail/admin/tests/pages/test_copy_page.py
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/tests/pages/test_dashboard.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/pages/test_moderation.py
  wagtail/admin/tests/test_moderation_list.py
  wagtail/admin/userbar.py
  wagtail/admin/views/home.py
  wagtail/admin/views/pages/history.py
  wagtail/admin/views/pages/moderation.py
  wagtail/admin/views/pages/revisions.py
  wagtail/admin/views/pages/workflow.py
  wagtail/admin/views/userbar.py
  wagtail/core/models/__init__.py
  wagtail/management/commands/create_log_entries_from_revisions.py
  wagtail/management/commands/publish_scheduled_pages.py
  wagtail/management/commands/purge_revisions.py
  wagtail/migrations/0070_rename_pagerevision_revision.py
  wagtail/migrations/0071_populate_revision_content_type.py
  wagtail/migrations/0072_alter_revision_content_type_notnull.py
  wagtail/models/__init__.py
  wagtail/query.py
  wagtail/tests/test_management_commands.py
  wagtail/tests/test_page_model.py
  wagtail/tests/test_page_queryset.py
Labels: status:Needs Review, component:Page

#8560 Set referer policy of upgrade notifcation to "strict-origin-when-cross-origin"
  CHANGELOG.txt
  client/src/components/UpgradeNotification/index.js
  docs/releases/4.0.md
Labels: status:Needs Review, component:Frontend

#8368 add consistent class to header & subtitle across templates
  wagtail/admin/templates/wagtailadmin/home.html
  wagtail/admin/templates/wagtailadmin/pages/index.html
  wagtail/admin/templates/wagtailadmin/pages/move_choose_destination.html
  wagtail/admin/templates/wagtailadmin/pages/preview_error.html
  wagtail/admin/templates/wagtailadmin/reports/base_report.html
  wagtail/admin/templates/wagtailadmin/shared/header.html
  wagtail/admin/templates/wagtailadmin/workflows/index.html
  wagtail/admin/templates/wagtailadmin/workflows/task_index.html
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/contrib/forms/templates/wagtailforms/index_submissions.html
  wagtail/contrib/modeladmin/templates/modeladmin/index.html
  wagtail/contrib/redirects/templates/wagtailredirects/index.html
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/snippets/templates/wagtailsnippets/snippets/type_index.html
Labels: type:Cleanup/Optimisation

#8358 resolve npm audit fix items
  package-lock.json
Labels: type:Cleanup/Optimisation, dependencies

#8544 Use css custom properties for new font stacks (via Tailwind theme)
  CHANGELOG.txt
  client/scss/elements/_root.scss
  client/scss/settings/_variables.scss
  client/src/tokens/typography.js
  client/src/tokens/typography.stories.tsx
  client/tailwind.config.js
  docs/advanced_topics/customisation/admin_templates.rst
  docs/releases/4.0.md
Labels: type:Enhancement, status:Needs Review, component:Frontend

#8541 Dialog component css version
  .circleci/config.yml
  Makefile
  client/scss/components/_dialog.scss
  client/scss/core.scss
  client/src/components/Sidebar/Sidebar.scss
  client/src/entrypoints/admin/wagtailadmin.js
  client/src/includes/dialog.js
  client/src/tokens/colors.js
  client/src/tokens/objectStyles.js
  client/tailwind.config.js
  package-lock.json
  package.json
  wagtail/admin/templates/wagtailadmin/icons/warning.svg
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog-toggle.html
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
  wagtail/admin/templates/wagtailadmin/shared/dialog/end-dialog.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
Labels: component:Frontend, component:Design system

#8543 Cleanup - eslint config fixes
  .eslintrc.js
  client/extract-translatable-strings.js
  client/src/api/admin.test.js
  client/src/api/admin.ts
  client/src/api/client.js
  client/src/api/client.test.js
  client/src/config/wagtailConfig.js
  client/src/includes/initSkipLink.js
  client/src/includes/tabs.js
  client/src/index.ts
  client/src/plugins/scrollbarThin.js
  client/storybook/middleware.js
  client/storybook/preview.js
  client/tests/mock-fetch.js
  client/webpack.config.js
  wagtail/admin/templates/wagtailadmin/shared/icons.stories.tsx
Labels: type:Cleanup/Optimisation, component:Frontend

#8494 Make radio buttons / checkboxes display vertically under Django 4.0
  CHANGELOG.txt
  client/scss/components/_forms.scss
  docs/releases/4.0.md
Labels: type:Bug, status:Needs Review, component:Frontend

#7657 Make cross-link URLs on generic model views optional
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/generic/edit.html
  wagtail/admin/templates/wagtailadmin/generic/index.html
  wagtail/admin/views/generic/models.py
Labels: type:Cleanup/Optimisation, status:Needs Review

#8555 Added missing gettext calls to the CommentComponent
  CHANGELOG.txt
  client/src/components/CommentApp/components/Comment/index.tsx
  docs/releases/4.0.md
Labels: status:Needs Review, component:UI localization, component:Commenting

#8569 Convert .rst to .md for /advanced_topics/api
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/advanced_topics/api/index.md
  docs/advanced_topics/api/v2/configuration.md
  docs/advanced_topics/api/v2/configuration.rst
  docs/advanced_topics/api/v2/usage.md
  docs/advanced_topics/api/v2/usage.rst
  docs/releases/4.0.md
Labels: Documentation, status:Needs Review, component:API

#8540 Added functionality in bulk actions: ability to use shift+click to select multiple items at once
  CHANGELOG.txt
  client/src/entrypoints/admin/bulk-actions.js
  docs/releases/4.0.md
Labels: component:Bulk Actions

#8571 Use `GenericForeignKey` and `GenericRelation` for `Revision`
  docs/reference/pages/model_reference.rst
  docs/releases/4.0.md
  wagtail/admin/tests/pages/test_dashboard.py
  wagtail/admin/tests/pages/test_moderation.py
  wagtail/admin/views/pages/history.py
  wagtail/models/__init__.py
  wagtail/query.py
Labels: status:Needs Work, component:Revisions

#7752 Feature: Upgrade notification 2 - LTS
  CHANGELOG.txt
  client/src/components/UpgradeNotification/index.js
  client/src/includes/initUpgradeNotification.test.js
  client/src/includes/initUpgradeNotification.ts
  client/src/index.ts
  client/src/utils/utils.test.js
  client/src/utils/version.js
  client/src/utils/version.test.js
  docs/reference/settings.rst
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html
  wagtail/admin/tests/test_upgrade_notification.py
  wagtail/admin/views/home.py
Labels: status:Needs Review

#8601 Convert from .rst to .md for /advanced_topics/images
  docs/advanced_topics/embeds.md
  docs/advanced_topics/images/animated_gifs.md
  docs/advanced_topics/images/changing_rich_text_representation.md
  docs/advanced_topics/images/changing_rich_text_representation.rst
  docs/advanced_topics/images/custom_image_model.md
  docs/advanced_topics/images/feature_detection.md
  docs/advanced_topics/images/feature_detection.rst
  docs/advanced_topics/images/focal_points.md
  docs/advanced_topics/images/focal_points.rst
  docs/advanced_topics/images/image_file_formats.md
  docs/advanced_topics/images/image_file_formats.rst
  docs/advanced_topics/images/image_serve_view.md
  docs/advanced_topics/images/image_serve_view.rst
  docs/advanced_topics/images/index.md
  docs/advanced_topics/images/index.rst
  docs/advanced_topics/images/renditions.md
  docs/advanced_topics/images/renditions.rst
Labels: Documentation, component:Images

#8596 Convert from .rst to .md for /advanced_topics/customisation
  docs/advanced_topics/customisation/admin_templates.md
  docs/advanced_topics/customisation/admin_templates.rst
  docs/advanced_topics/customisation/custom_user_models.md
  docs/advanced_topics/customisation/custom_user_models.rst
  docs/advanced_topics/customisation/index.md
  docs/advanced_topics/customisation/index.rst
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/advanced_topics/customisation/page_editing_interface.rst
  docs/advanced_topics/customisation/streamfield_blocks.md
  docs/advanced_topics/customisation/streamfield_blocks.rst
Labels: Documentation, status:Needs Review

#8577 eslint - disable perfer-default-export globally
  .eslintrc.js
  client/src/includes/dialog.js
  client/storybook/preview.js
Labels: status:Needs Review, component:Frontend
