Repository wagtail/wagtail, pull requests merged in 2022-06, with the labels that each got.

#8591 eslint - fix issue with how jquery is treated as a core module
  .eslintrc.js
Labels: component:Frontend

#8538 Workflow status dialog
  CHANGELOG.txt
  client/scss/components/_workflow-timeline.scss
  client/scss/core.scss
  client/src/includes/dialog.js
  docs/releases/4.0.md
  wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
  wagtail/admin/templates/wagtailadmin/pages/side_panels/includes/page_workflow_status.html
  wagtail/admin/templates/wagtailadmin/workflows/workflow_status.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_workflows.py
Labels: type:Enhancement, Accessibility

#8617 documentation & docstrings - fix spelling - behaviour vs behavior
  CHANGELOG.txt
  CODE_OF_CONDUCT.md
  client/src/api/client.js
  docs/advanced_topics/accessibility_considerations.rst
  docs/contributing/ui_guidelines.md
  docs/releases/2.5.rst
  docs/releases/2.6.rst
  docs/releases/2.8.rst
  docs/releases/3.0.md
  wagtail/contrib/routable_page/tests.py
  wagtail/documents/migrations/0011_add_choose_permissions.py
  wagtail/documents/tests/test_models.py
  wagtail/images/migrations/0023_add_choose_permissions.py
  wagtail/images/tests/test_signal_handlers.py
  wagtail/models/sites.py
Labels: Documentation

#8008 Form Builder - allow subclasses to override form field get clean name
  CHANGELOG.txt
  docs/reference/contrib/forms/customisation.md
  docs/releases/4.0.md
  wagtail/contrib/forms/forms.py
  wagtail/contrib/forms/models.py
  wagtail/contrib/forms/tests/test_forms.py
  wagtail/contrib/forms/tests/test_models.py
  wagtail/contrib/forms/tests/test_views.py
  wagtail/contrib/forms/utils.py
  wagtail/test/testapp/models.py
Labels: component:Form builder

#8382 migrate Home (dashboard) to class based view
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/home.html
  wagtail/admin/urls/__init__.py
  wagtail/admin/views/generic/__init__.py
  wagtail/admin/views/home.py
Labels: status:Needs Review, component:Dashboard

#8473 Add missing can_reorder_children() check, fixes #8458
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/tests/test_buttons_hooks.py
  wagtail/admin/wagtail_hooks.py
Labels: component:Page, component:Permissions

#8651 Disable Webpack css-loader URL handling in Storybook. Fix #8646
  client/storybook/main.js
Labels: type:Bug, status:Needs Review, component:Design system

#8638 Added new breadcrumbs to Pattern Library
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.html
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.stories.tsx
Labels: status:Needs Review, component:Frontend

#8637 Make `ReportView` extend from generic `IndexView`
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/views/generic/models.py
  wagtail/admin/views/reports/base.py
Labels: status:Needs Review, component:Reporting

#8444 Stream field docs to markdown
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/reference/streamfield/blocks.md
  docs/reference/streamfield/index.md
  docs/reference/streamfield/widget_api.md
  docs/releases/4.0.md
Labels: Documentation, component:Streamfield, status:Needs Work

#8652 Add tab nav link and tabbed interface to pattern library(storybook)
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/panels/tabbed_interface.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/tabs/tab_nav_link.stories.tsx
  wagtail/test/settings_ui.py
Labels: component:Frontend

#8642 Fix RTL sidebar branding cropping
  CHANGELOG.txt
  client/src/components/Sidebar/Sidebar.stories.tsx
  client/src/components/Sidebar/modules/WagtailLogo.tsx
  docs/releases/4.0.md
Labels: component:Frontend, component:UI localization, component:Menu

#8589 Fix locale selector background color
  CHANGELOG.txt
  client/scss/overrides/_utilities.dropdowns.scss
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/shared/header_with_locale_selector.html
Labels: component:i18n, component:Frontend

#8267 Fixing label issues on cropping image
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/4.0.md
  wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js
  wagtail/images/templates/wagtailimages/images/edit.html
Labels: component:Images, component:Frontend, Accessibility

#8654 Redirects import page does not need header search JS
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/contrib/redirects/templates/wagtailredirects/choose_import_file.html
Labels: component:Frontend, component:Redirects

#8521 Ensure non-square avatar image will correctly show
  CHANGELOG.txt
  client/scss/objects/_avatar.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  docs/releases/4.0.md
Labels: component:Frontend, component:User Management

#8666 Removed breadcrumbs next's reliance on data-slim-header
  CHANGELOG.txt
  client/src/includes/breadcrumbs.js
  client/src/includes/breadcrumbs.test.js
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/headers/slim_header.html
Labels: component:Frontend, GSOC

#8668 Fix/splitting blocks with highlights
  client/src/components/Draftail/CommentableEditor/CommentableEditor.test.tsx
  client/src/components/Draftail/CommentableEditor/CommentableEditor.tsx
Labels: status:Needs Review, component:Streamfield, component:Frontend, component:Rich text

#8679 Added breadcrumbs next to Explorer
  CHANGELOG.txt
  client/scss/components/_header.scss
  client/src/entrypoints/admin/page-editor.js
  client/src/entrypoints/admin/wagtailadmin.js
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/pages/index.html
  wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.html
  wagtail/admin/tests/pages/test_explorer_view.py
Labels: status:Needs Review, component:Frontend, GSOC

#8701 Convert from .rst to .md for docs/extending
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/advanced_topics/amp.md
  docs/advanced_topics/embeds.md
  docs/advanced_topics/i18n.md
  docs/extending/adding_reports.md
  docs/extending/adding_reports.rst
  docs/extending/admin_views.md
  docs/extending/admin_views.rst
  docs/extending/audit_log.md
  docs/extending/audit_log.rst
  docs/extending/custom_account_settings.md
  docs/extending/custom_account_settings.rst
  docs/extending/custom_bulk_actions.md
  docs/extending/custom_bulk_actions.rst
  docs/extending/custom_tasks.md
  docs/extending/custom_tasks.rst
  docs/extending/customising_group_views.md
  docs/extending/customising_group_views.rst
  docs/extending/extending_draftail.md
  docs/extending/extending_draftail.rst
  docs/extending/forms.md
  docs/extending/generic_views.md
  docs/extending/index.md
  docs/extending/index.rst
  docs/extending/rich_text_internals.md
  docs/extending/rich_text_internals.rst
  docs/extending/template_components.md
  docs/reference/contrib/typed_table_block.md
  docs/reference/panel_api.md
  docs/releases/4.0.md
Labels: Documentation

#8498 Add Fuzzy() search query class
  docs/topics/search/searching.rst
  wagtail/search/backends/elasticsearch5.py
  wagtail/search/query.py
  wagtail/search/tests/test_elasticsearch5_backend.py
  wagtail/search/tests/test_elasticsearch6_backend.py
  wagtail/search/tests/test_elasticsearch7_backend.py
Labels: component:Search

#8634 Add show to menu option
  docs/reference/contrib/modeladmin/index.md
  docs/reference/contrib/modeladmin/menu_item.md
  wagtail/admin/tests/tests.py
  wagtail/contrib/modeladmin/options.py
  wagtail/test/modeladmintest/migrations/0011_enemy.py
  wagtail/test/modeladmintest/models.py
  wagtail/test/modeladmintest/wagtail_hooks.py
Labels: status:Needs Review, component:Modeladmin

#8720 Typo in generic views docs - People -> Person
  docs/extending/generic_views.md
Labels: type:Bug, Documentation

#8722 Use iterator() wherever PageQueryset result caching is not needed
  docs/reference/contrib/redirects.rst
  wagtail/actions/copy_page.py
  wagtail/actions/create_alias.py
  wagtail/actions/delete_page.py
  wagtail/actions/unpublish_page.py
  wagtail/admin/views/pages/bulk_actions/publish.py
  wagtail/admin/views/pages/bulk_actions/unpublish.py
  wagtail/contrib/redirects/signal_handlers.py
  wagtail/contrib/sitemaps/sitemap_generator.py
Labels: Performance

#8689 Move page chooser changes
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/4.0.md
  wagtail/admin/forms/pages.py
  wagtail/admin/templates/wagtailadmin/pages/move_choose_destination.html
  wagtail/admin/tests/pages/test_move_page.py
  wagtail/admin/tests/test_page_chooser.py
  wagtail/admin/urls/pages.py
  wagtail/admin/views/chooser.py
  wagtail/admin/views/pages/bulk_actions/move.py
  wagtail/admin/views/pages/move.py
  wagtail/admin/widgets/chooser.py
Labels: status:Needs Review, component:Page, sprint:Arnhem2022

#8736 Cleanup - eslint spread rules - remove ignoring & fix up
  .eslintrc.js
  client/src/components/Draftail/index.js
  client/src/components/PageExplorer/PageCount.test.js
  client/src/components/PageExplorer/PageExplorerItem.test.js
  client/src/components/PageExplorer/PageExplorerPanel.test.js
  client/src/components/PageExplorer/actions.test.js
  client/src/components/PageExplorer/reducers/nodes.ts
  client/src/components/Sidebar/modules/MainMenu.tsx
  client/src/entrypoints/admin/core.js
Labels: status:Needs Review, component:Frontend

#8568 migrate docs contrib redirects & searchpromotions to md
  docs/reference/contrib/redirects.md
  docs/reference/contrib/redirects.rst
  docs/reference/contrib/searchpromotions.md
  docs/reference/contrib/searchpromotions.rst
Labels: Documentation

#8730 Move `get_snippet_panel` to `get_edit_handler` and fix missing return in `get_snippet_edit_handler`
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/panels.py
  wagtail/snippets/tests.py
  wagtail/snippets/views/snippets.py
Labels: component:Snippets

#8728 Docs/postgres search boost note
  CHANGELOG.txt
  docs/releases/4.0.md
  docs/topics/search/indexing.md
Labels: Documentation, component:Search

#8712 Fix 'create one now' link on snippet choosers
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/snippets/templates/wagtailsnippets/chooser/results.html
  wagtail/snippets/tests.py
  wagtail/snippets/views/chooser.py
Labels: type:Bug, status:Needs Review, component:Snippets

#8602 documentation - markdown formatting
  docs/advanced_topics/api/v2/usage.md
  docs/advanced_topics/images/renditions.md
  docs/contributing/developing.md
  docs/contributing/issue_tracking.md
  docs/contributing/security.md
  docs/contributing/ui_guidelines.md
  docs/getting_started/index.md
  docs/getting_started/the_zen_of_wagtail.md
  docs/getting_started/tutorial.md
  docs/reference/contrib/forms/customisation.md
  docs/reference/contrib/legacy_richtext.md
  docs/reference/contrib/modeladmin/base_url.md
  docs/reference/pages/panels.md
  docs/releases/2.16.2.md
  docs/releases/2.16.md
  docs/releases/3.0.md
  docs/releases/4.0.md
  docs/topics/pages.md
Labels: Documentation, status:Needs Review

#8747 gettext utils - fix issue where `ngettext` would not work
  client/src/utils/gettext.test.js
  client/src/utils/gettext.ts
Labels: status:Needs Review, component:Frontend, component:UI localization

#8756 Documentation - support page migration to markdown
  docs/support.md
Labels: Documentation, type:Cleanup/Optimisation, status:Needs Review

#8693 Deprecate wagtail.contrib.modeladmin.menus.SubMenu in favour of wagtail.admin.menu.Menu
  CHANGELOG.txt
  docs/extending/admin_views.md
  docs/releases/4.0.md
  wagtail/admin/menu.py
  wagtail/contrib/modeladmin/menus.py
  wagtail/contrib/modeladmin/options.py
Labels: type:Cleanup/Optimisation, component:Menu, sprint:Arnhem2022

#8763 Document the prefix_default_language parameter to i18n_patterns
  docs/advanced_topics/i18n.md
Labels: Documentation, status:Needs Review, component:i18n

#8743 Remove breadcrumbs from ModelAdmin
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/contrib/modeladmin/templates/modeladmin/choose_parent.html
  wagtail/contrib/modeladmin/templates/modeladmin/includes/breadcrumb.html
  wagtail/contrib/modeladmin/templates/modeladmin/includes/header_with_breadcrumb.html
  wagtail/contrib/modeladmin/templates/modeladmin/inspect.html
  wagtail/contrib/modeladmin/tests/test_page_modeladmin.py
  wagtail/contrib/modeladmin/tests/test_simple_modeladmin.py
Labels: status:Needs Work, status:Needs Tests, component:Frontend, GSOC

#8697 Update human-readable-date with accessible tooltip
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/scss/components/_human-readable-date.scss
  client/scss/layouts/_page-editor.scss
  client/src/entrypoints/admin/page-chooser-modal.js
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
  wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html
  wagtail/admin/templates/wagtailadmin/home/recent_edits.html
  wagtail/admin/templates/wagtailadmin/home/user_pages_in_workflow_moderation.html
  wagtail/admin/templates/wagtailadmin/home/workflow_pages_to_moderate.html
  wagtail/admin/templates/wagtailadmin/pages/history.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_list.html
  wagtail/admin/templates/wagtailadmin/pages/workflow_history/list.html
  wagtail/admin/templates/wagtailadmin/reports/aging_pages.html
  wagtail/admin/templates/wagtailadmin/reports/site_history.html
  wagtail/admin/templates/wagtailadmin/shared/human_readable_date.html
  wagtail/admin/templates/wagtailadmin/tables/date_cell.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/contrib/modeladmin/tests/test_simple_modeladmin.py
  wagtail/documents/templates/wagtaildocs/documents/list.html
  wagtail/snippets/tests.py
  wagtail/users/templates/wagtailusers/users/list.html
Labels: status:Needs Review, component:Frontend, Accessibility, sprint:Arnhem2022

#8729 Fix for npm lint format issue in windows
  CHANGELOG.txt
  docs/releases/4.0.md
  package.json
Labels: status:Needs Work, GSOC

#8669 Add search form to generic chooser
  wagtail/admin/templates/wagtailadmin/generic/chooser/chooser.html
  wagtail/admin/templates/wagtailadmin/generic/chooser/results.html
  wagtail/admin/views/generic/chooser.py
Labels: status:Needs Review, component:Choosers

#8665 Storybook story for status tag
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.stories.tsx
  wagtail/admin/templatetags/patternlibrary_override_tags.py
Labels: status:Needs Review, component:Frontend, component:Design system

#8581 Make password reset form customisable
  CHANGELOG.txt
  docs/reference/settings.rst
  docs/releases/4.0.md
  wagtail/admin/forms/auth.py
  wagtail/admin/templates/wagtailadmin/account/password_reset/form.html
  wagtail/admin/tests/test_forms.py
  wagtail/admin/tests/test_views.py
  wagtail/admin/views/account.py
Labels: component:User Management

#8640 Prefetch workflow states in edit page view
  CHANGELOG.txt
  docs/releases/4.0.md
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/views/pages/edit.py
Labels: type:Cleanup/Optimisation, component:Workflow, Performance

#8783 Squash testapp migrations
  wagtail/test/testapp/migrations/0001_squashed_0073_revisablechildmodel_secret_text.py
Labels: type:Cleanup/Optimisation, status:Needs Review, Performance
