Repository wagtail/wagtail, pull requests merged in 2023-10, with the labels that each got.

#10975 [Fix] Your first Wagtail site - Tag posts - Minor grammar adjustment
  CONTRIBUTORS.md
  docs/getting_started/tutorial.md
Labels: Documentation

#10973 Added translatable label in SetActiveStateBulkAction
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/users/views/bulk_actions/set_active_state.py
Labels: status:Needs Review, component:UI localization

#10956 NameEmailSettingsPanel should be titled "Name" when email management is disabled
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/5.2.md
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/views/account.py
Labels: status:Needs Work, component:User Management

#10950 Update extending_draftail.md
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/extending/extending_draftail.md
  docs/releases/5.2.md
Labels: Documentation, component:Rich text

#10954 oembed updated , spotify url issue is now fixed by removing the trailing slash in the oembed spotify definition
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/5.2.md
  wagtail/embeds/oembed_providers.py
Labels: status:Needs Work, component:Embeds

#10897 Implemented date_since in get_most_popular() inside search_promotions.models
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/contrib/search_promotions/models.py
  wagtail/contrib/search_promotions/tests.py
Labels: status:Needs Review, component:Search

#10979 Add upgrade considerations for side panels refactoring
  docs/releases/5.2.md
Labels: Documentation

#10907 Adopt `classname` instead of `classnames` in all MenuItem/Sidebar usage
  CHANGELOG.txt
  client/src/components/Sidebar/menu/ActionMenuItem.tsx
  client/src/components/Sidebar/menu/LinkMenuItem.tsx
  client/src/components/Sidebar/menu/PageExplorerMenuItem.tsx
  client/src/components/Sidebar/menu/SubMenuItem.tsx
  docs/reference/hooks.md
  docs/releases/5.2.md
  wagtail/admin/menu.py
  wagtail/admin/search.py
  wagtail/admin/templates/wagtailadmin/shared/search_area.html
  wagtail/admin/tests/tests.py
  wagtail/admin/tests/ui/test_sidebar.py
  wagtail/admin/ui/sidebar.py
  wagtail/admin/wagtail_hooks.py
  wagtail/contrib/modeladmin/menus.py
  wagtail/contrib/settings/registry.py
  wagtail/contrib/settings/tests/generic/test_admin.py
  wagtail/contrib/settings/tests/site_specific/test_admin.py
  wagtail/test/testapp/wagtail_hooks.py
Labels: type:Cleanup/Optimisation, component:Menu

#10987 Update Image Format.classnames to be Format.classname
  CHANGELOG.txt
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/advanced_topics/images/changing_rich_text_representation.md
  docs/releases/5.2.md
  wagtail/images/formats.py
  wagtail/images/tests/tests.py
  wagtail/images/views/chooser.py
Labels: type:Cleanup/Optimisation, component:Images

#10993 Update help block link contrast
  CHANGELOG.txt
  client/scss/components/_help-block.scss
  docs/releases/5.2.md
Labels: Accessibility, component:Design system

#10860 Added Progressbar in wagtail_image_rendition command
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/images/management/commands/wagtail_update_image_renditions.py
  wagtail/images/tests/test_management_commands.py
Labels: component:Images, component:Management Commands

#11001 Eslint - allow `new SomeClass()` in unit tests
  .eslintrc.js
  client/src/components/ExpandingFormset/index.test.js
  client/src/components/InlinePanel/index.test.js
Labels: type:Cleanup/Optimisation, javascript

#11006 Add 'undocumented internals' section to 5.2 upgrade considerations
  docs/releases/5.2.md
Labels: Documentation, type:Cleanup/Optimisation

#10634 Document new choice of writing style guide
  docs/contributing/documentation_guidelines.md
  docs/contributing/general_guidelines.md
Labels: Documentation, GSoD

#11009 Fix Inconsistent URL Format in Getting Started tutorial
  docs/getting_started/tutorial.md
Labels: Documentation, Outreachy

#10981 Support ordering by multiple fields in Wagtail API
  CHANGELOG.txt
  docs/advanced_topics/api/v2/usage.md
  docs/releases/5.2.md
  wagtail/api/v2/filters.py
  wagtail/api/v2/tests/test_pages.py
Labels: component:API

#10927 Docs - Add beter docs for `permission` on `PanelGroup` / `ObjectList` etc
  CHANGELOG.txt
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/extending/forms.md
  docs/reference/pages/panels.md
  docs/releases/5.2.md
  docs/topics/permissions.md
Labels: Documentation, component:Permissions

#11033 Migrate 'select text' feature to Stimulus (w-action)
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/src/controllers/ActionController.test.js
  client/src/controllers/ActionController.ts
  docs/releases/5.2.md
  wagtail/images/static_src/wagtailimages/js/image-url-generator.js
  wagtail/images/templates/wagtailimages/images/url_generator.html
Labels: component:Images, Accessibility, javascript, Outreachy, component:Stimulus

#11040 Krishvsoni patch 2
  CONTRIBUTORS.md
  README.md
Labels: Documentation, status:Needs Work

#10948 Added Js Events for Inline panel added/removed
  CHANGELOG.txt
  client/src/components/InlinePanel/__snapshots__/index.test.js.snap
  client/src/components/InlinePanel/index.js
  client/src/components/InlinePanel/index.test.js
  docs/reference/pages/panels.md
  docs/releases/5.2.md
Labels: component:Panels, javascript

#11043 Refactor/field reset with stimulus controller
  CHANGELOG.txt
  client/src/controllers/ActionController.test.js
  client/src/controllers/ActionController.ts
  docs/releases/5.2.md
Labels: javascript, component:Stimulus

#11050 fix #11048 with word-break property
  CHANGELOG.txt
  client/src/components/CommentApp/components/Comment/style.scss
  docs/releases/5.2.md
Labels: component:Commenting

#11066 DialogController - add optional notifyTargets
  CHANGELOG.txt
  client/src/controllers/DialogController.test.js
  client/src/controllers/DialogController.ts
  docs/releases/5.2.md
Labels: javascript, component:Stimulus

#11072 Add missing `locale` context value in page create and edit views
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/views/pages/create.py
  wagtail/admin/views/pages/edit.py
Labels: type:Bug, Release blocker, component:i18n, component:Page

#11017 Use get_or_create for editor page subscriptions
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/views/pages/edit.py
Labels: component:Page

#10934 Fix issue with closing dialog in the userbar
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
Labels: status:Needs Review, component:Userbar

#11076 Migrate publishing dialog field resets to use Stimulus
  CHANGELOG.txt
  client/src/entrypoints/admin/schedule-publishing.js
  client/webpack.config.js
  docs/releases/5.2.md
  wagtail/admin/panels/publishing_panel.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: component:Page, javascript, component:Stimulus

#11080 Use the correct action log when creating a redirect
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/contrib/redirects/tests/test_redirects.py
  wagtail/contrib/redirects/views.py
Labels: type:Bug, component:Redirects

#11081 Use the correct action log when creating a redirect
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/contrib/redirects/tests/test_redirects.py
  wagtail/contrib/redirects/views.py
Labels: type:Bug, component:Redirects, hacktoberfest-accepted

#11083 Use dropdown buttons on listings in dashboard panels
  CHANGELOG.txt
  client/scss/components/_dropdown.scss
  docs/releases/5.2.md
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
  wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html
  wagtail/admin/templates/wagtailadmin/home/recent_edits.html
  wagtail/admin/templates/wagtailadmin/home/workflow_objects_to_moderate.html
Labels: type:Enhancement, component:Panels

#10961 Avoid purging Revisions in use by third-party packages
  docs/reference/management_commands.md
  docs/reference/pages/model_reference.md
  wagtail/management/commands/purge_revisions.py
  wagtail/test/testapp/migrations/0029_variousondeletemodel_cascading_toy.py
  wagtail/test/testapp/migrations/0030_purgerevisionsprotectedtestmodel.py
  wagtail/test/testapp/models.py
  wagtail/tests/test_management_commands.py
Labels: status:Needs Review, component:Management Commands, component:Revisions

#11079 Documentation - Updated FieldPanel('title'...) to use TitleFieldPanel('title'...) in docs folder
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/reference/pages/panels.md
  docs/releases/5.2.md
Labels: Documentation, component:Panels

#10861 Add `BulkController` support for shift+click behaviour
  CHANGELOG.txt
  client/src/controllers/BulkController.test.js
  client/src/controllers/BulkController.ts
  docs/releases/5.2.md
Labels: component:Form builder, component:UI localization, javascript, component:Stimulus

#11047 Set strip=False to LoginForm,UserForm to ensure consistency with Djan…
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/admin/forms/auth.py
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/tests/test_views.py
  wagtail/users/forms.py
  wagtail/users/tests/test_admin_views.py
Labels: component:User Management

#11106 Reshuffle 5.2 upgrade consideration notes
  docs/releases/5.2.md
Labels: Documentation, status:Needs Review

#11057 Helpful addition to Developer Docs on Extending Draftail
  docs/extending/extending_draftail.md
Labels: Documentation, status:Needs Work, status:Needs Info, component:Rich text

#11136 Refactor styleguide view - convert to a class based view
  CHANGELOG.txt
  docs/releases/5.3.md
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/contrib/styleguide/views.py
  wagtail/contrib/styleguide/wagtail_hooks.py
Labels: type:Cleanup/Optimisation, component:Design system

#11148 6.0 deprecations - Remove Query and QueryDailyHits models and QueryForm from wagtail.search
  wagtail/contrib/search_promotions/management/commands/copy_daily_hits_from_wagtailsearch.py
  wagtail/contrib/search_promotions/migrations/0001_initial.py
  wagtail/contrib/search_promotions/migrations/0004_copy_queries.py
  wagtail/contrib/search_promotions/tests.py
  wagtail/search/forms.py
  wagtail/search/migrations/0008_remove_query_and_querydailyhits_models.py
  wagtail/search/models.py
  wagtail/search/tests/test_queries.py
Labels: type:Cleanup/Optimisation, component:Search

#11140 Refactor styleguide index view to CBV & modify template.
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/contrib/styleguide/views.py
Labels: type:Cleanup/Optimisation, component:Design system

#11115 Move Stimulus stories to the one location
  client/src/controllers/ActionController.stories.js
  client/src/controllers/SubmitController.stories.js
Labels: component:Design system, component:Stimulus

#11086 Note that the admin should be limited to "trusted" users
  docs/topics/permissions.md
Labels: Documentation, status:Needs Review, component:Security

#11162 Sort groups by name in group index view
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/users/tests/test_admin_views.py
  wagtail/users/views/groups.py
Labels: Release blocker

#11149 Remove redundant line from wagtailadmin_tags.py
  wagtail/admin/templatetags/wagtailadmin_tags.py
Labels: type:Cleanup/Optimisation
