Repository wagtail/wagtail, pull requests merged in 2023-04, with the labels that each got.

#10266 Ensure datetimepicker widget overlay shows over modals & drop-downs
  client/scss/overrides/_vendor.datetimepicker.scss
Labels: status:Needs Review

#10292 Bulk controller
  CHANGELOG.txt
  CONTRIBUTORS.rst
  client/src/controllers/BulkController.test.js
  client/src/controllers/BulkController.ts
  client/src/controllers/index.ts
  docs/releases/5.0.md
  wagtail/contrib/simple_translation/forms.py
  wagtail/contrib/simple_translation/templates/simple_translation/admin/submit_translation.html
Labels: component:i18n

#10176 Accessibility checker outlines feature
  CHANGELOG.txt
  client/src/includes/userbar.ts
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/userbar/base.html
  wagtail/admin/templates/wagtailadmin/userbar/item_accessibility.html
Labels: status:Needs Review, Accessibility, component:Userbar

#10212 Updated ActionController.ts with click function
  CHANGELOG.txt
  client/src/controllers/ActionController.test.js
  client/src/controllers/ActionController.ts
  docs/releases/5.0.md
Labels: status:Needs Work, javascript

#10039 Fixed Migrate site switcher to use Stimulus approach AutoFieldController #10035
  .eslintrc.js
  CHANGELOG.txt
  client/src/controllers/ActionController.test.js
  client/src/controllers/ActionController.ts
  client/webpack.config.js
  docs/releases/5.0.md
  wagtail/contrib/settings/forms.py
  wagtail/contrib/settings/static_src/wagtailsettings/js/site-switcher.js
Labels: component:Settings, javascript

#8345 Style comments as per page editor design, in side panel
  CHANGELOG.txt
  client/scss/components/_form-side.scss
  client/src/components/CommentApp/components/Comment/index.tsx
  client/src/components/CommentApp/components/Comment/style.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  client/src/components/CommentApp/components/CommentReply/style.scss
  client/src/components/CommentApp/main.scss
  client/src/components/CommentApp/main.tsx
  client/src/components/CommentApp/selectors/index.ts
  client/src/components/CommentApp/state/settings.ts
  client/src/components/Draftail/CommentableEditor/CommentableEditor.scss
  client/src/components/Draftail/CommentableEditor/CommentableEditor.test.tsx
  client/src/components/Draftail/CommentableEditor/CommentableEditor.tsx
  client/src/entrypoints/admin/comments.js
  client/src/includes/sidePanel.js
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/pages/create.html
  wagtail/admin/templates/wagtailadmin/pages/edit.html
  wagtail/admin/templates/wagtailadmin/shared/field.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/comments.html
Labels: type:Enhancement, component:Commenting, component:Design system

#10345 Allow blocking redirect in Stimulus Action controller
  client/src/controllers/ActionController.test.js
  client/src/controllers/ActionController.ts
Labels: javascript

#10343 Fix autocompletion on MySQL FTS backend
  wagtail/search/backends/database/mysql/mysql.py
  wagtail/search/backends/database/mysql/query.py
  wagtail/search/tests/test_mysql_backend.py
Labels: status:Needs Review, component:Search

#10341 Fix autocompletion on sqlite FTS backend
  wagtail/search/backends/database/sqlite/query.py
  wagtail/search/backends/database/sqlite/sqlite.py
  wagtail/search/tests/test_sqlite_backend.py
Labels: status:Needs Review, component:Search

#10347 Always use expanded Sass output so CSS processing is identical in dev and prod builds
  client/webpack.config.js
Labels: type:Bug, Release blocker

#10349 Provide an `autocomplete` endpoint on the fallback search backend
  wagtail/search/backends/database/fallback.py
  wagtail/search/tests/test_db_backend.py
Labels: status:Needs Review, component:Search

#10361 Skip Locale query when WAGTAIL_I18N_ENABLED is False
  CHANGELOG.txt
  docs/releases/5.0.md
  wagtail/models/i18n.py
  wagtail/tests/test_page_model.py
  wagtail/tests/test_translatablemixin.py
Labels: status:Needs Review, component:i18n, 🚀 Performance

#10333 Improve customisability of the accessibility checker configuration
  CHANGELOG.txt
  client/src/includes/userbar.ts
  docs/advanced_topics/accessibility_considerations.md
  docs/reference/hooks.md
  docs/releases/5.0.md
  docs/topics/writing_templates.md
  wagtail/admin/tests/test_userbar.py
  wagtail/admin/userbar.py
Labels: Accessibility, component:Userbar

#10357 Docs - Add recent third party tutorials
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation

#10192 Indicate that md5 is not being used for secure purposes—and that's okay (FIPS fix)
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/coreutils.py
  wagtail/embeds/embeds.py
  wagtail/users/utils.py
Labels: status:Needs Work

#10374 Add Wagtail 5 pypi classifier to docs
  docs/contributing/index.md
Labels: Documentation

#10107 Fix dismissible `SubMenuItem` not showing the number badge when there's a new item
  CHANGELOG.txt
  client/src/components/Sidebar/menu/SubMenuItem.tsx
  docs/releases/5.0.md
Labels: type:Bug
