Repository wagtail/wagtail, pull requests merged in 2023-02, with the labels that each got.

#9998 Update 4.2 release notes for `class_name` warning
  docs/releases/4.2.md
Labels: Documentation

#10006 Update to latest pre-release of Draftail. Fixes #9937, #9942
  package-lock.json
  package.json
Labels: type:Bug, Release blocker, component:Rich text

#10014 Update guide.wagtail.org links to use most up-to-date URL and page names
  docs/advanced_topics/deploying.md
  docs/reference/contrib/redirects.md
  docs/reference/pages/panels.md
  docs/reference/settings.md
  docs/releases/2.10.rst
  docs/topics/snippets.md
  wagtail/admin/wagtail_hooks.py
  wagtail/templatetags/wagtailcore_tags.py
Labels: Documentation, Release blocker

#10016 Update guide.wagtail.org links to point to v4.2.x pages
  docs/advanced_topics/deploying.md
  docs/index.rst
  docs/reference/contrib/redirects.md
  docs/reference/pages/panels.md
  docs/reference/settings.md
  docs/releases/2.10.rst
  docs/topics/snippets.md
  wagtail/admin/wagtail_hooks.py
  wagtail/templatetags/wagtailcore_tags.py
Labels: Documentation, Release blocker

#10026 Documentation - fix up ModelAdmin items
  docs/extending/admin_views.md
  docs/reference/contrib/modeladmin/create_edit_delete_views.md
  docs/reference/contrib/modeladmin/index.md
  docs/reference/contrib/modeladmin/indexview.md
  docs/reference/contrib/modeladmin/primer.md
  docs/reference/contrib/modeladmin/tips_and_tricks/reversing_urls.md
Labels: Documentation, status:Needs Review, component:Modeladmin

#10028 Update documentation screenshots for v4.2
  docs/_static/images/adminviews_calendar_template.png
  docs/_static/images/adminviews_calendarmonth.png
  docs/_static/images/adminviews_menu_group_expanded.png
  docs/_static/images/tutorial/tutorial_2.png
  docs/_static/images/tutorial/tutorial_4a.png
  docs/_static/images/tutorial/tutorial_4b.png
  docs/_static/images/tutorial/tutorial_5.png
  docs/_static/images/tutorial/tutorial_8.png
Labels: Documentation

#10020 re-implemented the gravatar button using HTML/CSS
  CHANGELOG.txt
  client/scss/layouts/_account.scss
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/account/settings_panels/avatar.html
Labels: Accessibility, component:User Management

#9956 converted button-longrunning to Stimulus and wrote tests for it
  CHANGELOG.txt
  client/src/controllers/ProgressController.test.js
  client/src/controllers/ProgressController.ts
  client/src/controllers/index.ts
  client/src/entrypoints/admin/core.js
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/workflows/edit_task.html
Labels: javascript

#6028 Add new "Icons" page for icons customisation and reuse across the admin interface
  CHANGELOG.txt
  docs/advanced_topics/icons.md
  docs/advanced_topics/index.md
  docs/extending/extending_draftail.md
  docs/releases/5.0.md
Labels: Documentation, status:Needs Info

#10059 Add recent third party tutorials (Feb 2023)
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation, status:Needs Review

#9989 Implement new simplified userbar designs
  CHANGELOG.txt
  client/scss/components/_userbar.scss
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/icons/key.svg
  wagtail/admin/templates/wagtailadmin/userbar/base.html
  wagtail/admin/templates/wagtailadmin/userbar/item_admin.html
  wagtail/admin/wagtail_hooks.py
Labels: type:Enhancement, component:Userbar

#10064 Iterate on accessibility checker docs
  docs/advanced_topics/accessibility_considerations.md
Labels: Documentation, Accessibility

#10067 Fix broken formatting for MultiFieldPanel / FieldRowPanel permission kwarg docs
  CHANGELOG.txt
  docs/reference/pages/panels.md
  docs/releases/5.0.md
Labels: type:Bug, Documentation

#10044 Fix side panel resize direction on RTL languages. Fix #9916
  CHANGELOG.txt
  client/src/includes/sidePanel.js
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/shared/side_panels.html
Labels: component:UI localization, component:Preview

#10069 Add unit tests for CollapseAll element
  CHANGELOG.txt
  client/src/components/Minimap/CollapseAll.test.tsx
  docs/releases/5.0.md
Labels: javascript

#10062 added the stimulus progress data attributes to button-longrunning button
  client/src/controllers/ProgressController.test.js
  client/src/controllers/ProgressController.ts
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/generic/chooser/creation_form.html
  wagtail/admin/templates/wagtailadmin/generic/multiple_upload/edit_form.html
  wagtail/admin/templates/wagtailadmin/login.html
  wagtail/admin/templates/wagtailadmin/pages/action_menu/publish.html
  wagtail/admin/templates/wagtailadmin/pages/action_menu/save_draft.html
  wagtail/admin/templates/wagtailadmin/panels/publishing/schedule_publishing_panel.html
  wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/filters.html
  wagtail/admin/templates/wagtailadmin/shared/workflow_action_modal.html
  wagtail/admin/templates/wagtailadmin/workflows/create.html
  wagtail/admin/templates/wagtailadmin/workflows/create_task.html
  wagtail/admin/templates/wagtailadmin/workflows/edit.html
  wagtail/admin/templates/wagtailadmin/workflows/edit_task.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/create_form.html
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
  wagtail/contrib/modeladmin/templates/modeladmin/create.html
  wagtail/contrib/modeladmin/templates/modeladmin/edit.html
  wagtail/contrib/settings/templates/wagtailsettings/edit.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/documents/templates/wagtaildocs/documents/add.html
  wagtail/embeds/templates/wagtailembeds/chooser/chooser.html
  wagtail/images/templates/wagtailimages/chooser/confirm_duplicate_upload.html
  wagtail/images/templates/wagtailimages/images/confirm_duplicate_upload.html
  wagtail/snippets/templates/wagtailsnippets/snippets/action_menu/publish.html
  wagtail/snippets/templates/wagtailsnippets/snippets/action_menu/save.html
  wagtail/snippets/tests/test_locking.py
  wagtail/snippets/tests/test_snippets.py
Labels: status:Needs Review

#10051 Fix image saving on backends that expect a rewound file pointer
  wagtail/images/models.py
  wagtail/test/dummy_external_storage.py
  wagtail/tests/test_tests.py
Labels: component:Images

#10082 Update PR template to prompt for a description of the PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status:Needs Review

#10040 ActionController - add JSDoc note & type
  client/src/controllers/ActionController.ts
Labels: status:Needs Review, javascript

#9097 fix storybook (pattern library) tabs data
  wagtail/admin/templates/wagtailadmin/panels/tabbed_interface.stories.tsx
Labels: status:Needs Review, component:Design system

#10095 Prettier/Eslint - Ignore storybook build folder
  .eslintignore
  .prettierignore
  client/src/components/Draftail/decorators/__snapshots__/TooltipEntity.test.js.snap
Labels: javascript, component:Design system

#10045 replaced script tags with template tag and updated related javascript …
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/5.0.md
  wagtail/documents/templates/wagtaildocs/multiple/add.html
  wagtail/images/templates/wagtailimages/multiple/add.html
Labels: component:Images, component:Documents, javascript

#9927 Update Algolia autocomplete styles
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/_static/css/docsearch.overrides.css
  docs/releases/5.0.md
Labels: Documentation

#10083 Add unit tests for MinimapItem
  CHANGELOG.txt
  client/src/components/Minimap/MinimapItem.test.tsx
  docs/releases/5.0.md
Labels: type:Cleanup/Optimisation, status:Needs Review, javascript

#8914 Remove unneeded float styles on 404 page
  CHANGELOG.txt
  client/scss/layouts/_404.scss
  docs/releases/5.0.md
Labels: type:Cleanup/Optimisation, component:i18n

#10047 User bar: JS to TS conversion
  CHANGELOG.txt
  client/src/entrypoints/admin/userbar.js
  client/src/includes/userbar.ts
  docs/releases/5.0.md
Labels: type:Cleanup/Optimisation, javascript, component:Userbar

#9813 Remove deprecated Settings Tab from documentation (Wagtail 4.1)
  docs/advanced_topics/customisation/page_editing_interface.md
Labels: Documentation

#10116 Documentation - remove legacy docs references
  docs/releases/1.8.rst
  docs/releases/2.13.rst
Labels: Documentation, type:Cleanup/Optimisation

#10113 migrate initSlugCleaning to Stimulus
  CHANGELOG.txt
  client/src/controllers/SlugController.test.js
  client/src/controllers/SlugController.ts
  client/src/controllers/index.ts
  client/src/entrypoints/admin/page-editor.js
  client/src/utils/text.test.js
  client/src/utils/text.ts
  docs/releases/5.0.md
  wagtail/admin/forms/pages.py
  wagtail/admin/panels/page_utils.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/test_widgets.py
  wagtail/admin/widgets/slug.py
Labels: component:Page, javascript

#9721 Refactor Status tag styles into UI component #8656
  CHANGELOG.txt
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html
  wagtail/admin/templates/wagtailadmin/chooser/tables/parent_page_cell.html
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
  wagtail/admin/templates/wagtailadmin/home/pages_for_moderation.html
  wagtail/admin/templates/wagtailadmin/home/recent_edits.html
  wagtail/admin/templates/wagtailadmin/home/user_objects_in_workflow_moderation.html
  wagtail/admin/templates/wagtailadmin/home/workflow_objects_to_moderate.html
  wagtail/admin/templates/wagtailadmin/pages/history.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_explore.html
  wagtail/admin/templates/wagtailadmin/reports/aging_pages.html
  wagtail/admin/templates/wagtailadmin/reports/workflow.html
  wagtail/admin/templates/wagtailadmin/reports/workflow_tasks.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
  wagtail/admin/templates/wagtailadmin/shared/status_tag.html
  wagtail/admin/templates/wagtailadmin/shared/status_tag.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/workflow_history/detail.html
  wagtail/admin/templates/wagtailadmin/shared/workflow_history/list.html
  wagtail/admin/templates/wagtailadmin/tables/status_tag_cell.html
  wagtail/admin/templates/wagtailadmin/workflows/index.html
  wagtail/admin/templates/wagtailadmin/workflows/task_index.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/snippets/templates/wagtailsnippets/snippets/revisions/_actions.html
  wagtail/snippets/tests/test_snippets.py
  wagtail/users/templates/wagtailusers/users/list.html
Labels: type:Cleanup/Optimisation, component:Design system

#10132 Specify that h1, h5, h6 are disabled in rich text by default
  docs/advanced_topics/customisation/page_editing_interface.md
Labels: Documentation, component:Rich text

#10081 Add curlylint and update djhtml, semgrep versions in pre-commit config
  .pre-commit-config.yaml
  CHANGELOG.txt
  docs/releases/5.0.md
Labels: status:Needs Review, Infrastructure, dependencies

#10143 Documentation: Adding return statement to process_form_submission
  CONTRIBUTORS.rst
  docs/reference/contrib/forms/customisation.md
Labels: Documentation, component:Form builder

#9993 Adopt core shared header for ModelAdmin headers
  CHANGELOG.txt
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/shared/header.html
  wagtail/contrib/modeladmin/templates/modeladmin/index.html
Labels: component:Modeladmin

#10140 update-collections-privacy-switch
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/collections/_privacy_switch.html
Labels: type:Cleanup/Optimisation, component:Page

#10110 Migrate initErrorDetection to a Stimulus Controller w-count (tabs)
  CHANGELOG.txt
  client/src/controllers/CountController.test.js
  client/src/controllers/CountController.ts
  client/src/controllers/index.ts
  client/src/entrypoints/admin/page-editor.js
  docs/releases/5.0.md
  wagtail/admin/templates/wagtailadmin/shared/tabs/tab_nav_link.html
Labels: javascript
