Repository wagtail/wagtail, pull requests merged in 2023-06, with the labels that each got.

#10501 Add explicit names on menu item registrations
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/releases/5.1.md
  wagtail/admin/tests/test_menu.py
  wagtail/admin/wagtail_hooks.py
  wagtail/contrib/redirects/wagtail_hooks.py
  wagtail/contrib/search_promotions/wagtail_hooks.py
  wagtail/contrib/styleguide/wagtail_hooks.py
  wagtail/locales/wagtail_hooks.py
  wagtail/sites/wagtail_hooks.py
  wagtail/test/testapp/wagtail_hooks.py
  wagtail/users/wagtail_hooks.py
Labels: status:Needs Review, component:Menu, sprint:DjangoConEU2023

#10527 Add new Sustainability considerations page
  docs/advanced_topics/index.md
  docs/advanced_topics/sustainability_considerations.md
Labels: Sustainability

#10542 Small typo in JSDoc - gettext
  client/src/utils/gettext.ts
Labels: type:Cleanup/Optimisation, status:Needs Review, javascript

#10425 Revise main Getting started tutorial for clarity
  CHANGELOG.txt
  CONTRIBUTORS.rst
  docs/getting_started/tutorial.md
  docs/releases/5.1.md
Labels: Documentation

#10559 Prevent crash when comparing page revisions that include MultipleChooserPanel
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/admin/panels/multiple_chooser_panel.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: type:Bug, component:Choosers

#10520 Update type hints in admin/ui/components.py
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/admin/ui/components.py
Labels: type:Cleanup/Optimisation, component:Panels

#10567 Docs - fix typo in Django forms reference
  docs/extending/forms.md
Labels: Documentation

#10573 Documentation - clean up last two internal refs to use underscore
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/extending/rich_text_internals.md
  docs/reference/pages/panels.md
  docs/reference/panel_api.md
  docs/topics/images.md
Labels: Documentation, type:Cleanup/Optimisation, status:Needs Review

#10568 Add `TitleFieldPanel` to support shared usage of title field sync
  docs/reference/pages/panels.md
  wagtail/admin/panels/__init__.py
  wagtail/admin/panels/page_utils.py
  wagtail/admin/panels/title_field_panel.py
  wagtail/admin/tests/pages/test_create_page.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: status:Needs Review, component:Snippets, component:Panels

#10575 Use custom dark theme colors for revision comparisons. Fix #10552
  client/scss/layouts/_compare-revisions.scss
  client/scss/tools/_mixins.general.scss
Labels: type:Bug, status:Needs Review, Accessibility

#10572 Add YouTube Live url to oembed provider
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/embeds/oembed_providers.py
Labels: component:Embeds

#10485 Don't redundantly try and find a site
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/contrib/settings/context_processors.py
Labels: type:Cleanup/Optimisation, component:Site, 🚀 Performance

#10469 Order group editor object permissions
  CHANGELOG.txt
  docs/extending/customising_group_views.md
  docs/releases/5.1.md
  wagtail/users/permission_order.py
  wagtail/users/templatetags/wagtailusers_tags.py
  wagtail/users/tests/test_admin_views.py
Labels: component:Permissions

#10599 Missing Menu Prefix
  CONTRIBUTORS.rst
  docs/topics/snippets/customising.md
Labels: Documentation, component:Snippets

#10601 Fix tagit autocomplete text colour in dark mode
  CHANGELOG.txt
  client/scss/overrides/_vendor.tagit.scss
  docs/releases/5.1.md
Labels: component:Tagging, component:Design system

#10607 Remove unused window.tagit_opts declarations
  wagtail/documents/templates/wagtaildocs/documents/add.html
  wagtail/documents/templates/wagtaildocs/multiple/add.html
  wagtail/documents/views/chooser.py
  wagtail/images/templates/wagtailimages/images/add.html
  wagtail/images/templates/wagtailimages/multiple/add.html
  wagtail/images/views/chooser.py
Labels: type:Cleanup/Optimisation

#10616 Convert the CONTRIBUTORS file to Markdown
  CONTRIBUTORS.md
  docs/contributing/committing.md
Labels: Documentation, status:Needs Review

#10548 Optimise queries in collection permission policies using cache on the user object
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/permission_policies/collections.py
Labels: component:Permissions, 🚀 Performance, component:Collections, status:Ready to merge

#10583 fix empty blocks created in migration operations
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/blocks/migrations/operations.py
  wagtail/tests/streamfield_migrations/test_simple_structures.py
Labels: component:Streamfield, status:Ready to merge

#10579 Finish first batch of getting started tutorial changes
  docs/getting_started/tutorial.md
Labels: Documentation
