Repository wagtail/wagtail, pull requests merged in 2023-12, with the labels that each got.

#11286 Fix alias() not compatible with specific()
  CHANGELOG.txt
  docs/releases/6.0.md
  wagtail/query.py
  wagtail/tests/test_page_queryset.py
Labels: component:Page

#11297 Official Django 5.0 support in Wagtail 5.2.x
  .github/workflows/test.yml
  CHANGELOG.txt
  README.md
  docs/getting_started/integrating_into_django.md
  docs/releases/5.2.2.md
  docs/releases/upgrading.md
  setup.py
  tox.ini
  wagtail/project_template/requirements.txt
Labels: component:Django, dependencies

#11303 Fix display property used on The CommentControl's ToolbarButton
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/src/components/Draftail/CommentableEditor/CommentableEditor.scss
  docs/releases/5.2.2.md
Labels: component:Rich text

#11290 add way to set default ordering for child pages in wagtail
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/reference/pages/model_reference.md
  docs/releases/6.0.md
  wagtail/admin/tests/pages/test_explorer_view.py
  wagtail/admin/views/pages/listing.py
  wagtail/models/__init__.py
Labels: component:Page, status:Ready to merge

#11258 Remove Safari 14 support in Wagtail admin – update browserslist and TypeScript
  .babelrc.json
  .eslintrc.js
  client/scss/components/_button.scss
  client/scss/components/_userbar.scss
  client/src/components/CommentApp/main.scss
  client/src/components/Draftail/Draftail.scss
  client/src/components/Sidebar/Sidebar.stories.tsx
  client/src/components/Sidebar/menu/ActionMenuItem.tsx
  client/src/components/Sidebar/menu/LinkMenuItem.tsx
  client/src/components/Sidebar/menu/PageExplorerMenuItem.tsx
  client/src/components/Sidebar/menu/SubMenuItem.tsx
  client/storybook/main.js
  docs/contributing/developing.md
  package-lock.json
  package.json
  tsconfig.json
  wagtail/admin/templates/wagtailadmin/shared/avatar.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/breadcrumbs.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/dropdown/dropdown.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/header.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/help_block.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/page_breadcrumbs.stories.tsx
  wagtail/admin/templates/wagtailadmin/shared/status_tag.stories.tsx
Labels: type:Cleanup/Optimisation, javascript, dependencies

#11335 Bump telepath to 0.3.1
  setup.py
Labels: type:Cleanup/Optimisation, dependencies

#11298 Docs: Clarify appropriate use of MultipleChooserPanel
  CHANGELOG.txt
  docs/extending/generic_views.md
  docs/reference/pages/panels.md
  docs/releases/6.0.md
Labels: Documentation, component:Panels, component:Choosers

#11348 Add missing ClusterableModel import to snippet InlinePanel example
  docs/topics/snippets/features.md
Labels: Documentation

#11352 Update sitemaps.md
  docs/reference/contrib/sitemaps.md
Labels: Documentation, type:Cleanup/Optimisation

#11336 Turn on `skipLibCheck` for TypeScript
  CHANGELOG.txt
  docs/releases/6.0.md
  tsconfig.json
Labels: type:Cleanup/Optimisation, javascript

#11360 Refactor float usage within admin styles. Fix #8126
  .stylelintrc.js
  client/scss/components/_dropdown.legacy.scss
  client/scss/components/_footer.scss
  client/scss/components/_grid.legacy.scss
  client/scss/components/_header.scss
  client/scss/components/_listing.scss
  client/scss/layouts/_report.scss
  client/scss/overrides/_vendor.datetimepicker.scss
  client/scss/tools/_mixins.grid.scss
  client/src/components/CommentApp/components/Comment/style.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  client/src/components/CommentApp/components/CommentReply/style.scss
  client/src/includes/initStimulus.test.js
  client/tailwind.config.js
  docs/getting_started/tutorial.md
  wagtail/admin/templates/wagtailadmin/notifications/base.html
Labels: type:Enhancement, component:UI localization

#11390 Fix a typo in the SnippetsViewSet documentation
  wagtail/snippets/views/snippets.py
Labels: Documentation
