Repository wagtail/wagtail, pull requests merged in 2023-07, with the labels that each got.

#10574 Clean up and update deployment page
  CHANGELOG.txt
  docs/advanced_topics/deploying.md
  docs/advanced_topics/third_party_tutorials.md
  docs/releases/5.1.md
Labels: Documentation

#10605 Cast settings' verbose_name to string
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/contrib/settings/models.py
  wagtail/contrib/settings/tests/generic/test_model.py
  wagtail/test/testapp/migrations/0025_alter_importantpagesgenericsetting_options.py
  wagtail/test/testapp/models.py
Labels: component:Settings, component:UI localization, status:Ready to merge

#10611 Add more items to performance page
  CHANGELOG.txt
  docs/advanced_topics/performance.md
  docs/getting_started/index.md
  docs/getting_started/quick_install.md
  docs/releases/5.1.md
Labels: Documentation, 🚀 Performance

#10507 Docs - Align on client-side naming & fix Draftail typos
  CHANGELOG.txt
  docs/advanced_topics/customisation/admin_templates.md
  docs/advanced_topics/icons.md
  docs/extending/extending_draftail.md
  docs/releases/4.0.md
  docs/releases/5.0.md
Labels: Documentation, component:Rich text

#10623 Added regex operation to strip out spaces from phone numbers #10558
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/5.1.md
  wagtail/admin/tests/test_page_chooser.py
  wagtail/admin/views/chooser.py
Labels: component:Choosers

#10624 Switch the tutorial snippets example to be more understandable #10609
  CHANGELOG.txt
  docs/getting_started/index.md
  docs/getting_started/integrating_into_django.md
  docs/getting_started/the_zen_of_wagtail.md
  docs/getting_started/tutorial.md
  docs/releases/5.1.md
Labels: Documentation, GSoD

#10610 Auto-select single block in StreamField
  CHANGELOG.txt
  client/src/components/StreamField/blocks/StreamBlock.js
  client/src/components/StreamField/blocks/StreamBlock.test.js
  client/src/components/StreamField/blocks/__snapshots__/StreamBlock.test.js.snap
  docs/releases/5.1.md
Labels: component:Streamfield, javascript

#10534 Reduce usage of `innerHTML` & replace with `textContent` - translated/dynamic content
  CHANGELOG.txt
  client/src/components/StreamField/blocks/FieldBlock.js
  client/src/controllers/CountController.ts
  client/src/controllers/UpgradeController.test.js
  client/src/controllers/UpgradeController.ts
  client/src/includes/chooserModal.js
  docs/releases/5.1.md
  wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js
Labels: component:Security, javascript

#10547 Implement new Draftail customisation APIs. Fix #5580
  CHANGELOG.txt
  client/src/components/Draftail/__snapshots__/index.test.js.snap
  client/src/components/Draftail/index.js
  client/src/components/Draftail/index.test.js
  client/src/entrypoints/admin/draftail.js
  client/src/entrypoints/admin/draftail.test.js
  docs/extending/extending_draftail.md
  docs/releases/5.1.md
  wagtail/admin/rich_text/editors/draftail/features.py
Labels: type:Enhancement, component:Rich text

#10632 Move django-filter version upper bound to 24
  setup.py
Labels: dependencies

#10633 Increase Pillow dependency range to include 10.x
  CHANGELOG.txt
  docs/releases/5.1.md
  setup.py
Labels: dependencies

#9952 Migrate header search to a Stimulus controller (basic version)
  CHANGELOG.txt
  client/src/controllers/SwapController.test.js
  client/src/controllers/SwapController.ts
  client/src/controllers/index.ts
  client/src/entrypoints/admin/bulk-actions.js
  client/src/entrypoints/admin/core.js
  client/src/entrypoints/admin/wagtailadmin.js
  docs/releases/5.1.md
Labels: component:Search, javascript

#10636 Typo in PagePermissionHelper on user_can_unpublish_obj
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/contrib/modeladmin/helpers/permission.py
  wagtail/contrib/modeladmin/tests/test_page_modeladmin.py
Labels: component:Modeladmin, component:Page, component:Permissions

#10566 Add support for --template argument to wagtail start. Fix #10423
  CHANGELOG.txt
  docs/reference/project_template.md
  docs/releases/5.1.md
  wagtail/bin/wagtail.py
Labels: type:Enhancement, DX

#9590 Add missing TZ conversions and date formatting
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/actions/publish_revision.py
  wagtail/admin/tests/pages/test_edit_page.py
  wagtail/admin/tests/pages/test_revisions.py
  wagtail/admin/tests/test_audit_log.py
  wagtail/admin/views/generic/mixins.py
  wagtail/admin/views/pages/edit.py
  wagtail/admin/views/pages/revisions.py
  wagtail/locks.py
  wagtail/migrations/0088_fix_log_entry_json_timestamps.py
  wagtail/models/__init__.py
  wagtail/models/audit_log.py
  wagtail/snippets/tests/test_snippets.py
  wagtail/test/utils/timestamps.py
  wagtail/tests/test_audit_log.py
  wagtail/tests/test_page_model.py
  wagtail/utils/timestamps.py
  wagtail/wagtail_hooks.py
Labels: component:UI localization, component:Audit logging

#10639 Update rich text Link/Document Tooltip styles
  CHANGELOG.txt
  client/src/components/Draftail/Tooltip/Tooltip.scss
  client/src/components/Draftail/decorators/TooltipEntity.js
  client/src/components/Draftail/decorators/__snapshots__/TooltipEntity.test.js.snap
  docs/releases/5.1.md
Labels: component:Design system

#10669 Remove unused snippets _header_with_history.html
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/snippets/templates/wagtailsnippets/snippets/_header_with_history.html
Labels: type:Cleanup/Optimisation, component:Snippets

#10643 Update styles for critical buttons in dark mode
  CHANGELOG.txt
  client/scss/components/_button.scss
  client/src/tokens/colorThemes.js
  client/src/tokens/colorVariables.test.js
  docs/_static/wagtail_colors_tables.txt
  docs/releases/5.1.md
Labels: type:Bug, Accessibility, component:Design system

#10644 Update styles for block picker in dark mode
  CHANGELOG.txt
  client/src/components/ComboBox/ComboBox.scss
  client/src/tokens/colorThemes.js
  client/src/tokens/colorVariables.test.js
  client/src/tokens/objectStyles.js
  docs/_static/wagtail_colors_tables.txt
  docs/releases/5.1.md
Labels: type:Enhancement, Accessibility, component:Design system

#10679 Follow up: remove `field_as_li.html` template
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/admin/templates/wagtailadmin/chooser/anchor_link.html
  wagtail/admin/templates/wagtailadmin/chooser/email_link.html
  wagtail/admin/templates/wagtailadmin/chooser/external_link.html
  wagtail/admin/templates/wagtailadmin/chooser/phone_link.html
  wagtail/admin/templates/wagtailadmin/generic/chooser/chooser.html
  wagtail/admin/templates/wagtailadmin/generic/chooser/creation_form.html
  wagtail/admin/templates/wagtailadmin/generic/form.html
  wagtail/admin/templates/wagtailadmin/generic/multiple_upload/edit_form.html
  wagtail/admin/templates/wagtailadmin/pages/copy.html
  wagtail/admin/templates/wagtailadmin/pages/move_choose_destination.html
  wagtail/admin/templates/wagtailadmin/shared/field_as_li.html
  wagtail/admin/templates/wagtailadmin/workflows/create_task.html
  wagtail/admin/templates/wagtailadmin/workflows/edit_task.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/chooser.html
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/includes/create_form.html
  wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
  wagtail/contrib/redirects/templates/wagtailredirects/add.html
  wagtail/contrib/redirects/templates/wagtailredirects/choose_import_file.html
  wagtail/contrib/redirects/templates/wagtailredirects/confirm_import.html
  wagtail/contrib/redirects/templates/wagtailredirects/edit.html
  wagtail/contrib/simple_translation/templates/simple_translation/admin/submit_translation.html
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/documents/templates/wagtaildocs/documents/add.html
  wagtail/documents/templates/wagtaildocs/documents/edit.html
  wagtail/embeds/templates/wagtailembeds/chooser/chooser.html
  wagtail/images/templates/wagtailimages/chooser/chooser.html
  wagtail/images/templates/wagtailimages/images/add.html
  wagtail/search/templates/wagtailsearch/queries/chooser/chooser.html
  wagtail/test/testapp/templates/tests/generic_view_templates/edit.html
  wagtail/users/templates/wagtailusers/groups/create.html
  wagtail/users/templates/wagtailusers/users/create.html
  wagtail/users/templates/wagtailusers/users/edit.html
Labels: type:Cleanup/Optimisation, status:Needs Review, size:Small, component:Frontend

#10495 Documentation - revise usage of e.g.
  docs/advanced_topics/accessibility_considerations.md
  docs/advanced_topics/streamfield_migrations.md
  docs/contributing/first_contribution_guide.md
  docs/reference/pages/panels.md
  docs/releases/5.1.md
  docs/topics/snippets/features.md
  wagtail/admin/tests/test_edit_handlers.py
Labels: Documentation, status:Needs Review

#10477 Avoid `N+1` in users Index view
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/users/tests/test_admin_views.py
  wagtail/users/views/bulk_actions/user_bulk_action.py
  wagtail/users/views/users.py
Labels: component:Page, 🚀 Performance

#9961 Adopt the Stimulus `SwapController` in the modal task chooser
  client/src/controllers/SwapController.test.js
  client/src/controllers/SwapController.ts
  client/src/entrypoints/admin/task-chooser-modal.js
  wagtail/admin/templates/wagtailadmin/workflows/task_chooser/chooser.html
Labels: status:Needs Review, component:Workflow, javascript

#10684 Reinstate `field_as_li.html` template
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/admin/templates/wagtailadmin/shared/field_as_li.html
Labels: Release blocker, Compatibility

#10688 Deprecate Elasticsearch 5 and 6 search backends
  docs/releases/5.1.md
  wagtail/search/backends/elasticsearch5.py
  wagtail/search/backends/elasticsearch7.py
Labels: type:Cleanup/Optimisation, component:Search

#10617 DropdownController - fix test & refine event dispatch
  client/src/controllers/DropdownController.test.js
  client/src/controllers/DropdownController.ts
Labels: type:Bug, status:Needs Review, javascript, component:Stimulus

#10667 Documentation: Add info on `searchpromotions` stored queries
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/reference/contrib/searchpromotions.md
  docs/reference/management_commands.md
  docs/reference/settings.md
  docs/releases/5.0.md
  docs/releases/5.1.md
  docs/topics/search/searching.md
Labels: Documentation, component:Search

#10693 Fix snippet search test to work on non-fallback database backends
  CHANGELOG.txt
  docs/releases/5.2.md
  wagtail/test/testapp/models.py
Labels: type:Cleanup/Optimisation, component:Search

#10700 Fix a few minor typos in the 5.1 release notes / changelog
  CHANGELOG.txt
  docs/releases/5.1.md
Labels: Documentation

#9603 Define preview-aware and page-aware cache tags
  CHANGELOG.txt
  docs/advanced_topics/performance.md
  docs/reference/pages/model_reference.md
  docs/releases/5.2.md
  docs/topics/writing_templates.md
  wagtail/coreutils.py
  wagtail/models/__init__.py
  wagtail/templatetags/wagtail_cache.py
  wagtail/tests/test_page_model.py
  wagtail/tests/tests.py
Labels: status:Needs Review, 🚀 Performance

#10707 Add guide for migrating from modeladmin to snippets
  CHANGELOG.txt
  docs/reference/contrib/modeladmin/index.md
  docs/reference/contrib/modeladmin/migrating_to_snippets.md
  docs/releases/5.1.md
  docs/topics/snippets/customising.md
Labels: status:Needs Review, component:Modeladmin, component:Snippets

#10721 Use bakerydemo as project in Squash
  .squash.yml
Labels: status:Needs Review, Infrastructure

#10715 Fix `search_promotions` `0004_copy_queries` migration for long-lived Wagtail instances
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/contrib/search_promotions/migrations/0004_copy_queries.py
Labels: status:Needs Review

#10727 Guard against TypeError in `0088_fix_log_entry_json_timestamps` migration
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/migrations/0088_fix_log_entry_json_timestamps.py
Labels: type:Bug, component:Audit logging

#10703 Don't update the reference index while deleting it
  CHANGELOG.txt
  docs/releases/5.1.md
  wagtail/management/commands/rebuild_references_index.py
Labels: component:Search, 🚀 Performance
