Repository wagtail/wagtail, pull requests merged in 2024-01, with the labels that each got.

#11407 Upgrade sphinxcontrib-spelling to 7.x
  CHANGELOG.txt
  docs/releases/6.0.md
  setup.py
Labels: type:Cleanup/Optimisation

#11414 Bump dependencies to django-taggit>=4.0, django-modelcluster>=6.2.1
  setup.py
Labels: type:Cleanup/Optimisation

#11396 Auto increment slugs on per model basis
  CHANGELOG.txt
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/releases/6.0.md
  wagtail/admin/tests/pages/test_copy_page.py
  wagtail/admin/views/pages/copy.py
  wagtail/test/testapp/migrations/0033_customcopyformpage.py
  wagtail/test/testapp/models.py
Labels: component:Page

#11164 Migrate Styleguide ad-hoc JS to use styles only
  CHANGELOG.txt
  docs/releases/6.0.md
  wagtail/contrib/styleguide/.gitignore
  wagtail/contrib/styleguide/static/wagtailstyleguide/css/animate-progress.css
  wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
  wagtail/contrib/styleguide/views.py
Labels: type:Cleanup/Optimisation, component:Design system

#8510 feat(TypedTableBlock): added caption field (#8507)
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/src/entrypoints/contrib/table_block/__snapshots__/table.test.js.snap
  client/src/entrypoints/contrib/table_block/table.js
  client/src/entrypoints/contrib/table_block/table.test.js
  client/src/entrypoints/contrib/typed_table_block/__snapshots__/typed_table_block.test.js.snap
  client/src/entrypoints/contrib/typed_table_block/typed_table_block.js
  client/src/entrypoints/contrib/typed_table_block/typed_table_block.test.js
  docs/releases/6.0.md
  wagtail/contrib/table_block/blocks.py
  wagtail/contrib/typed_table_block/blocks.py
  wagtail/contrib/typed_table_block/templates/typed_table_block/typed_table_block.html
  wagtail/contrib/typed_table_block/tests.py
Labels: component:Streamfield

#11327 Switched TableBlock’s header controls to a field that requires user input
  CHANGELOG.txt
  client/src/entrypoints/contrib/table_block/__snapshots__/table.test.js.snap
  client/src/entrypoints/contrib/table_block/table.js
  client/src/entrypoints/contrib/table_block/table.test.js
  docs/releases/6.0.md
  wagtail/contrib/table_block/blocks.py
  wagtail/contrib/table_block/tests.py
Labels: component:Streamfield

#11329 Ensure dialog (modal) shows the close button with a visible cross icon
  CHANGELOG.txt
  client/scss/components/_dialog.scss
  docs/releases/6.0.md
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
  wagtail/admin/tests/pages/test_edit_page.py
Labels: status:Needs Review, Accessibility, component:Design system

#11325 Fix Comment Reply Spanning Outside Comment Box
  CHANGELOG.txt
  client/src/components/CommentApp/components/CommentReply/style.scss
  client/src/components/CommentApp/main.scss
  docs/releases/6.0.md
Labels: status:Needs Review, component:Commenting

#10049 Improve CSS authoring guidelines
  CHANGELOG.txt
  docs/contributing/ui_guidelines.md
  docs/releases/6.0.md
Labels: Documentation, type:Cleanup/Optimisation, Accessibility, component:UI localization

#11370 Update semver & yaml packages (NPM Audit security fixes)
  package-lock.json
Labels: component:Security, dependencies

#11476 Fix: Remove blur action from orderable controller
  client/src/controllers/OrderableController.test.js
  wagtail/admin/templates/wagtailadmin/pages/listing/_ordering_cell.html
  wagtail/admin/views/pages/listing.py
Labels: Accessibility, javascript, component:Stimulus

#11489 Add unit tests & small fixes to OrderableController
  client/src/controllers/OrderableController.test.js
  client/src/controllers/OrderableController.ts
  client/tests/mock-fetch.js
Labels: component:Stimulus

#11465 PR for issue #11459
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.0.md
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
Labels: Accessibility

#11334 Update docs on get_language_info tag
  docs/advanced_topics/i18n.md
Labels: Documentation, component:i18n

#11443 updated the anchor sizes
  CHANGELOG.txt
  client/scss/components/_panel.scss
  docs/releases/6.0.md
Labels: Accessibility, component:Panels

#11492 Raise 404 with bulk actions for models which don't exist
  CHANGELOG.txt
  docs/releases/6.0.md
  wagtail/admin/tests/pages/test_bulk_actions/test_bulk_action.py
  wagtail/admin/views/bulk_action/dispatcher.py
Labels: component:Bulk Actions

#11495 Add changelog & a few fixes for #11194 (MyST parser update)
  CHANGELOG.txt
  docs/advanced_topics/third_party_tutorials.md
  docs/contributing/developing.md
  docs/contributing/documentation_guidelines.md
  docs/reference/pages/model_reference.md
  docs/releases/6.0.md
Labels: Documentation

#11496 Formatting documentation for whitespace fixes
  .github/CONTRIBUTING.md
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/advanced_topics/documents/overview.md
  docs/contributing/ui_guidelines.md
  docs/releases/upgrading.md
  docs/tutorial/create-footer_for_all_pages.md
  docs/tutorial/create_contact_page.md
  docs/tutorial/create_portfolio_page.md
  docs/tutorial/customize_homepage.md
  docs/tutorial/deployment.md
  docs/tutorial/index.md
  docs/tutorial/set_up_site_menu.md
  docs/tutorial/style_your_site.md
Labels: Documentation

#11498 Document MIT licensing terms for handsontable 6.2.2
  docs/reference/contrib/table_block.md
Labels: Documentation

#11502 Update table_block.md
  docs/reference/contrib/table_block.md
Labels: Documentation, component:Streamfield

#11486 Universal listings: avoid error when ordering search results by latest_revision_created_at
  wagtail/admin/tests/pages/test_explorer_view.py
  wagtail/admin/views/pages/listing.py
Labels: type:Bug

#11487 Fix exclude_fields_in_copy
  CHANGELOG.txt
  docs/releases/6.0.md
  wagtail/actions/copy_page.py
  wagtail/tests/test_page_model.py
Labels: component:Page

#11288 Fix chooser buttons focus color is too dark in dark mode
  CHANGELOG.txt
  client/scss/components/_chooser.scss
  docs/releases/6.0.md
Labels: Accessibility, component:Choosers

#11478 Move accessibility checker inside the editor (#11478). Fix #10136
  CHANGELOG.txt
  client/scss/components/_a11y-result.scss
  client/scss/components/_userbar.scss
  client/scss/core.scss
  client/src/entrypoints/admin/preview-panel.js
  client/src/includes/a11y-result.test.ts
  client/src/includes/a11y-result.ts
  client/src/includes/userbar.ts
  docs/_static/wagtail_icons_table.txt
  docs/advanced_topics/accessibility_considerations.md
  docs/releases/6.0.md
  wagtail/admin/templates/wagtailadmin/icons/glasses.svg
  wagtail/admin/templates/wagtailadmin/shared/side_panels/checks.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/preview.html
  wagtail/admin/templates/wagtailadmin/userbar/base.html
  wagtail/admin/templatetags/wagtailuserbar.py
  wagtail/admin/tests/pages/test_preview.py
  wagtail/admin/tests/test_userbar.py
  wagtail/admin/ui/side_panels.py
  wagtail/admin/views/pages/create.py
  wagtail/admin/views/pages/edit.py
  wagtail/admin/views/pages/revisions.py
  wagtail/admin/wagtail_hooks.py
  wagtail/snippets/tests/test_preview.py
  wagtail/snippets/views/snippets.py
Labels: Accessibility

#11402 make TableBlock reachable by Keyboard
  CHANGELOG.txt
  client/src/entrypoints/contrib/table_block/table.js
  docs/releases/6.0.md
Labels: component:Streamfield, Accessibility

#11435 Explicitly set triggerElement when invoking modal
  CHANGELOG.txt
  client/src/entrypoints/admin/modal-workflow.js
  docs/releases/6.0.md
  wagtail/admin/templates/wagtailadmin/shared/_workflow_init.html
Labels: Accessibility, component:Choosers

#11510 Add Redirect API
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/advanced_topics/api/v2/configuration.md
  docs/reference/contrib/redirects.md
  docs/releases/6.0.md
  wagtail/contrib/redirects/api.py
  wagtail/contrib/redirects/tests/test_redirects_api.py
  wagtail/test/urls.py
Labels: component:API, component:Redirects

#11528 Fix filters from being removed when searching
  client/src/controllers/DropdownController.ts
  wagtail/admin/templates/wagtailadmin/shared/dropdown/dropdown.html
  wagtail/admin/templates/wagtailadmin/shared/headers/_filters.html
Labels: type:Bug, Release blocker, component:Stimulus

#11548 Changed all British spellings in the usage guide and advanced topics section to American spellings.
  docs/advanced_topics/accessibility_considerations.md
  docs/advanced_topics/add_to_django_project.md
  docs/advanced_topics/amp.md
  docs/advanced_topics/api/v2/configuration.md
  docs/advanced_topics/api/v2/usage.md
  docs/advanced_topics/customisation/admin_templates.md
  docs/advanced_topics/customisation/custom_user_models.md
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/advanced_topics/customisation/streamfield_blocks.md
  docs/advanced_topics/deploying.md
  docs/advanced_topics/documents/custom_document_model.md
  docs/advanced_topics/documents/title_generation_on_upload.md
  docs/advanced_topics/embeds.md
  docs/advanced_topics/i18n.md
  docs/advanced_topics/icons.md
  docs/advanced_topics/images/changing_rich_text_representation.md
  docs/advanced_topics/images/custom_image_model.md
  docs/advanced_topics/images/image_serve_view.md
  docs/advanced_topics/images/renditions.md
  docs/advanced_topics/images/title_generation_on_upload.md
  docs/advanced_topics/multi_site_multi_instance_multi_tenancy.md
  docs/advanced_topics/performance.md
  docs/advanced_topics/privacy.md
  docs/advanced_topics/streamfield_migrations.md
  docs/advanced_topics/sustainability_considerations.md
  docs/advanced_topics/testing.md
  docs/topics/images.md
  docs/topics/permissions.md
  docs/topics/search/searching.md
  docs/topics/snippets/customising.md
  docs/topics/snippets/features.md
  docs/topics/snippets/registering.md
  docs/topics/streamfield.md
  docs/topics/writing_templates.md
Labels: Documentation

#11505 Add documentation for overriding `get_upload_to` in custom image models
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/advanced_topics/images/custom_image_model.md
  docs/releases/6.0.md
  wagtail/images/models.py
Labels: Documentation, component:Images

#11546 Update Ordering, wording and help text for private pages
  CHANGELOG.txt
  docs/advanced_topics/privacy.md
  wagtail/admin/tests/test_audit_log.py
  wagtail/admin/tests/test_privacy.py
  wagtail/models/view_restrictions.py
Labels: component:Privacy

#11554 Documentation - Refactor promotion banner without jQuery & add Wagtail Space 2024 banner
  .eslintrc.js
  CHANGELOG.txt
  docs/_static/css/custom.css
  docs/_static/js/banner.js
  docs/_templates/layout.html
  docs/releases/6.0.md
Labels: Documentation

#11558 Remove Duplicate Field In Additional Field Names List
  CHANGELOG.txt
  CONTRIBUTORS.md
  wagtail/models/__init__.py
Labels: type:Cleanup/Optimisation, component:Page

#11107 Add small documentation on using forks. Fixes #10594
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/contributing/developing.md
Labels: Documentation, DX

#10571 Add RelatedObjectsColumn to the table UI framework
  CHANGELOG.txt
  wagtail/admin/templates/wagtailadmin/tables/related_objects_cell.html
  wagtail/admin/tests/ui/test_tables.py
  wagtail/admin/ui/tables/__init__.py
Labels: type:Enhancement

#10326 Replace `html5lib` with `html.parser`
  CHANGELOG.txt
  setup.py
  wagtail/admin/tests/test_compare.py
  wagtail/admin/tests/test_dbwhitelister.py
  wagtail/test/utils/wagtail_tests.py
  wagtail/tests/test_whitelist.py
  wagtail/utils/text.py
  wagtail/whitelist.py
Labels: type:Cleanup/Optimisation, 🚀 Performance, dependencies
