Repository wagtail/wagtail, pull requests merged in 2024-05, with the labels that each got.

#11927 Speed up semgrep on pre-commit
  .pre-commit-config.yaml
Labels: type:Cleanup/Optimisation

#11937 Refactor image chooser pagination to check WAGTAILIMAGES_CHOOSER_PAGE_SIZE at runtime
  CHANGELOG.txt
  docs/releases/6.2.md
  wagtail/admin/viewsets/base.py
  wagtail/admin/viewsets/chooser.py
  wagtail/images/tests/test_admin_views.py
  wagtail/images/views/chooser.py
Labels: type:Cleanup/Optimisation, component:Images, component:Choosers

#11951 Fix form action URL in user edit and delete views for custom user models
  wagtail/users/tests/test_admin_views.py
  wagtail/users/views/users.py
Labels: type:Bug, status:Needs Review

#11945 Only scan `src` in `client` directory for Tailwind to prevent unnecessary rebuilds
  CHANGELOG.txt
  docs/releases/6.2.md
  tailwind.config.js
Labels: type:Cleanup/Optimisation, 🚀 Performance, component:Design system

#11936 Partially revert listing styles changes to fix layout issues
  CHANGELOG.txt
  client/scss/components/_listing.scss
  docs/releases/6.1.1.md
  docs/releases/6.2.md
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_title_explore.html
  wagtail/users/templates/wagtailusers/users/user_cell.html
Labels: type:Bug, component:Universal listings

#11903 Support SVG icon id attributes with single quotes in the styleguide
  CHANGELOG.txt
  docs/advanced_topics/icons.md
  docs/releases/6.1.2.md
  docs/releases/6.2.md
  wagtail/contrib/styleguide/tests.py
  wagtail/contrib/styleguide/views.py
  wagtail/test/testapp/templates/tests/icons/single-quotes.svg
Labels: type:Bug
