Repository wagtail/wagtail, pull requests merged in 2024-09, with the labels that each got.

#12250 Add official hosting documentation
  CHANGELOG.txt
  docs/advanced_topics/index.md
  docs/deploy/flyio.md
  docs/deploy/index.md
  docs/deploy/under_the_hood.md
  docs/index.rst
  docs/releases/6.3.md
  docs/tutorial/deployment.md
Labels: Documentation

#12289 Reinstate support for generic IndexView without model attribute
  wagtail/admin/tests/test_views_generic.py
  wagtail/admin/views/generic/models.py
  wagtail/test/testapp/urls.py
  wagtail/test/testapp/views.py
Labels: Release blocker

#12293 Add new Puppeteer cache location to fix CircleCI ui_tests
  .circleci/config.yml
Labels: type:Bug

#12302 Force refresh of CircleCI pipenv cache
  .circleci/config.yml
Labels: type:Cleanup/Optimisation, Infrastructure

#12305 Roll back codecov CI task to v3
  .github/workflows/test.yml
Labels: Infrastructure

#12292 [UI]: Changed class from warning to failure for confirm site name mes…
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.3.md
  wagtail/admin/templates/wagtailadmin/pages/confirm_delete.html
Labels: Accessibility, component:Page

#12338 Docs - Hacktoberfest - Remove reference to the t-shirt
  docs/contributing/first_contribution_guide.md
Labels: Documentation

#12295 Fix content metrics plugin to work on the main element before falling back to `body`
  CHANGELOG.txt
  client/src/controllers/PreviewController.ts
  client/src/includes/contentMetrics.test.ts
  client/src/includes/contentMetrics.ts
  docs/releases/6.2.2.md
  docs/releases/6.3.md
Labels: type:Bug, component:Preview

#12332 Remove unnecessary filters from redirects index
  wagtail/contrib/redirects/filters.py
  wagtail/contrib/redirects/tests/test_redirects.py
Labels: type:Bug, component:Universal listings

#12339 Docs - Update spelling & reference in release notes for UserViewSet
  CHANGELOG.txt
  docs/releases/6.3.md
Labels: Documentation

#12352 Stop PopularTagsFilter from applying an IN clause when not filtering
  wagtail/admin/filters.py
  wagtail/images/tests/test_admin_views.py
Labels: type:Bug

#12279 Fix minimap toggle visibility
  CHANGELOG.txt
  client/src/components/Minimap/CollapseAll.scss
  client/src/components/Minimap/Minimap.scss
  docs/releases/6.3.md
Labels: type:Bug, Accessibility

#12359 Mark `js_translation_strings` template tag for deprecation
  CHANGELOG.txt
  docs/releases/6.3.md
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
Labels: type:Cleanup/Optimisation, status:Needs Review

#12351 Docs: Clarify file location, add missing imports
  docs/topics/snippets/customizing.md
Labels: Documentation, component:Snippets

#12273 Fix oembed providers
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.3.md
  wagtail/embeds/oembed_providers.py
Labels: component:Embeds

#12365 Update _dropdown.scss
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/scss/components/_dropdown.scss
  docs/releases/6.3.md
Labels: Accessibility

#12363 Documentation: Configure API to use the DRF's TokenAuthentication
  CHANGELOG.txt
  docs/advanced_topics/api/v2/configuration.md
  docs/releases/6.3.md
Labels: Documentation, component:Security, component:API

#12373 Update django-taggit dependency to allow 6.1.x
  setup.py
Labels: type:Cleanup/Optimisation
