Repository wagtail/wagtail, pull requests merged in 2024-02, with the labels that each got.

#11578 Fix TestForMigrations to catch missing migrations on core app
  wagtail/tests/test_migrations.py
Labels: type:Bug

#11519 fix: enum eslint error
  .eslintrc.js
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/src/controllers/OrderableController.ts
  docs/releases/6.1.md
Labels: javascript, component:Stimulus

#11580 Update Eslint rules - remove items no longer required
  .eslintrc.js
Labels: type:Cleanup/Optimisation

#11589 doc: Update tutorial.md
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/getting_started/tutorial.md
  docs/releases/6.0.md
Labels: Documentation

#11602 Limit locale filter to only show the available locales
  wagtail/admin/filters.py
  wagtail/admin/views/generic/base.py
  wagtail/snippets/tests/test_snippets.py
Labels: type:Bug, status:Needs Review

#11608 Styling fixes for universal listings
  client/scss/components/_drilldown.scss
  client/scss/components/_filters.scss
  client/scss/components/_listing.scss
Labels: Accessibility, component:Snippets, component:Page, component:Design system

#11594 Update Eslint, Prettier & pre-commit versions
  .pre-commit-config.yaml
  client/src/components/CommentApp/main.tsx
  client/src/includes/bulk-actions.js
  package-lock.json
  package.json
Labels: status:Needs Review, dependencies

#11618 Fix closing button tag for promotion banner
  docs/_templates/layout.html
Labels: Documentation

#11616 Fix minor typo (6.0 release notes) in WidgetWithScript deprecation note
  docs/releases/6.0.md
Labels: Documentation

#11614 Docs - Make sure the settings panel is listed in the `TabbedInterface` example
  CHANGELOG.txt
  docs/advanced_topics/customisation/page_editing_interface.md
  docs/releases/6.1.md
Labels: Documentation

#11584 Workflow model to get inherited from AbstractWorkflow model (#11538)
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.1.md
  wagtail/models/__init__.py
Labels: component:Workflow

#11617 Update Eslint, Prettier, Stylelint packages & pre-commit versions (v2)
  .pre-commit-config.yaml
  client/src/components/CommentApp/main.tsx
  client/src/includes/bulk-actions.js
  package-lock.json
  package.json
Labels: status:Needs Review, dependencies

#11582 Enable the option to disable shared passwords
  CHANGELOG.txt
  docs/advanced_topics/privacy.md
  docs/reference/settings.md
  docs/releases/6.1.md
  wagtail/admin/forms/collections.py
  wagtail/admin/forms/pages.py
  wagtail/admin/templates/wagtailadmin/collection_privacy/set_privacy.html
  wagtail/admin/templates/wagtailadmin/page_privacy/set_privacy.html
  wagtail/admin/tests/test_privacy.py
  wagtail/documents/tests/test_collection_privacy.py
Labels: component:Security, component:Privacy

#11128 Wagtail admin skeleton - use classnames template tag
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/admin/templates/wagtailadmin/skeleton.html
Labels: type:Cleanup/Optimisation

#11567 Changed all British spellings in the Extending and Reference section to American spellings.
  CHANGELOG.txt
  docs/advanced_topics/deploying.md
  docs/contributing/ui_guidelines.md
  docs/extending/adding_reports.md
  docs/extending/admin_views.md
  docs/extending/audit_log.md
  docs/extending/custom_account_settings.md
  docs/extending/custom_bulk_actions.md
  docs/extending/custom_tasks.md
  docs/extending/customizing_group_views.md
  docs/extending/extending_client_side.md
  docs/extending/extending_draftail.md
  docs/extending/forms.md
  docs/extending/generic_views.md
  docs/extending/index.md
  docs/extending/rich_text_internals.md
  docs/reference/contrib/forms/customization.md
  docs/reference/contrib/forms/index.md
  docs/reference/contrib/settings.md
  docs/reference/contrib/simple_translation.md
  docs/reference/contrib/sitemaps.md
  docs/reference/contrib/table_block.md
  docs/reference/contrib/typed_table_block.md
  docs/reference/hooks.md
  docs/reference/jinja2.md
  docs/reference/management_commands.md
  docs/reference/pages/index.md
  docs/reference/pages/model_recipes.md
  docs/reference/pages/model_reference.md
  docs/reference/pages/panels.md
  docs/reference/pages/theory.md
  docs/reference/settings.md
  docs/reference/signals.md
  docs/reference/streamfield/blocks.md
  docs/reference/streamfield/widget_api.md
  docs/releases/1.9.rst
  docs/releases/2.14.rst
  docs/releases/5.1.md
  docs/releases/5.2.md
  docs/releases/6.1.md
  docs/topics/snippets/customizing.md
  docs/topics/snippets/index.md
  wagtail/models/collections.py
  wagtail/test/testapp/models.py
Labels: Documentation, status:Needs Review

#11576 Fix/5919 nested inline panels ordering buttons
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/src/components/InlinePanel/index.js
  docs/releases/6.1.md
Labels: status:Needs Review, component:Panels, javascript

#11555 Merging UploadedDocument and UploadedImage into UploadedFile
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/admin/views/generic/multiple_upload.py
  wagtail/documents/admin_urls.py
  wagtail/documents/migrations/0013_delete_uploadeddocument.py
  wagtail/documents/models.py
  wagtail/documents/tests/test_admin_views.py
  wagtail/documents/views/multiple.py
  wagtail/images/admin_urls.py
  wagtail/images/migrations/0026_delete_uploadedimage.py
  wagtail/images/models.py
  wagtail/images/tests/test_admin_views.py
  wagtail/images/views/multiple.py
  wagtail/migrations/0093_uploadedfile.py
  wagtail/models/__init__.py
  wagtail/models/media.py
  wagtail/test/testapp/migrations/0001_squashed_0073_revisablechildmodel_secret_text.py
Labels: type:Cleanup/Optimisation, component:Images, component:Documents, component:Collections

#11577 Add system checks for WAGTAIL_DATE_FORMAT, WAGTAIL_DATETIME_FORMAT and WAGTAIL_TIME_FORMAT
  CHANGELOG.txt
  docs/reference/settings.md
  docs/releases/6.1.md
  wagtail/admin/checks.py
  wagtail/admin/tests/test_checks.py
Labels: status:Needs Review

#11606 Prevent displaying model verbose_name in permissions UI for custom permissions
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/test/testapp/migrations/0034_modelwithverbosename.py
  wagtail/test/testapp/models.py
  wagtail/users/templatetags/wagtailusers_tags.py
  wagtail/users/tests/test_admin_views.py
Labels: component:User Management, component:UI localization

#11641 Changed all British spellings to American spellings, in the Contributing to wagtail section.
  CHANGELOG.txt
  docs/contributing/committing.md
  docs/contributing/developing.md
  docs/contributing/documentation_guidelines.md
  docs/contributing/first_contribution_guide.md
  docs/contributing/index.md
  docs/contributing/issue_tracking.md
  docs/contributing/python_guidelines.md
  docs/contributing/security.md
  docs/contributing/translations.md
  docs/contributing/ui_guidelines.md
  docs/releases/6.1.md
Labels: Documentation

#11652 Cut down pull request template text to minimum
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:Cleanup/Optimisation, Infrastructure

#11651 Documentation - Fix broken links
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/advanced_topics/accessibility_considerations.md
  docs/advanced_topics/i18n.md
  docs/advanced_topics/third_party_tutorials.md
  docs/contributing/documentation_guidelines.md
  docs/contributing/index.md
  docs/contributing/issue_tracking.md
  docs/extending/custom_image_filters.md
  docs/reference/contrib/frontendcache.md
  docs/reference/jinja2.md
  docs/releases/1.8.rst
  docs/releases/6.1.md
  docs/topics/images.md
Labels: Documentation

#11662 Fix empty admin search on Elasticsearch (backport to 5.2)
  wagtail/search/backends/elasticsearch5.py
  wagtail/search/tests/test_elasticsearch5_backend.py
Labels: component:Search

#11658 Changed all British spellings to American spellings, in the releases section of the docs.
  docs/releases/0.4.rst
  docs/releases/0.5.rst
  docs/releases/0.7.rst
  docs/releases/0.8.3.rst
  docs/releases/0.8.6.rst
  docs/releases/1.0.rst
  docs/releases/1.1.rst
  docs/releases/1.10.rst
  docs/releases/1.12.rst
  docs/releases/1.2.rst
  docs/releases/1.3.rst
  docs/releases/1.4.5.rst
  docs/releases/1.4.rst
  docs/releases/1.5.rst
  docs/releases/1.6.rst
  docs/releases/1.7.rst
  docs/releases/1.8.rst
  docs/releases/1.9.rst
  docs/releases/2.0.1.rst
  docs/releases/2.0.rst
  docs/releases/2.1.rst
  docs/releases/2.10.rst
  docs/releases/2.11.8.rst
  docs/releases/2.13.2.rst
  docs/releases/2.13.3.rst
  docs/releases/2.13.5.rst
  docs/releases/2.14.2.rst
  docs/releases/2.14.rst
  docs/releases/2.15.2.rst
  docs/releases/2.15.rst
  docs/releases/2.16.1.rst
  docs/releases/2.16.md
  docs/releases/2.2.rst
  docs/releases/2.3.rst
  docs/releases/2.4.rst
  docs/releases/2.5.rst
  docs/releases/2.6.rst
  docs/releases/2.7.rst
  docs/releases/2.8.rst
  docs/releases/3.0.md
  docs/releases/4.0.2.md
  docs/releases/4.0.md
  docs/releases/4.1.2.md
  docs/releases/4.1.3.md
  docs/releases/4.1.4.md
  docs/releases/4.1.md
  docs/releases/4.2.2.md
  docs/releases/4.2.md
  docs/releases/5.0.1.md
  docs/releases/5.0.2.md
  docs/releases/5.0.md
  docs/releases/5.1.2.md
  docs/releases/5.1.md
  docs/releases/5.2.md
  docs/releases/6.0.md
  docs/releases/6.1.md
  docs/releases/upgrading.md
Labels: Documentation

#11694 wagtail_update_image_renditions(Fixed typo)
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/reference/management_commands.md
  docs/releases/6.1.md
Labels: Documentation, component:Images

#11676 References to Laces
  CHANGELOG.txt
  docs/extending/template_components.md
  docs/releases/6.0.md
  docs/releases/6.1.md
Labels: Documentation, status:Needs Review

#11703 Fix - Ensure that modal tabs width are not impacted by side panel opening
  CHANGELOG.txt
  client/scss/components/forms/_form-width.scss
  docs/releases/6.0.2.md
  docs/releases/index.rst
Labels: type:Bug, component:Panels, component:Choosers
