Repository wagtail/wagtail, pull requests merged in 2024-04, with the labels that each got.

#11820 Fix minor spelling (customizations) in 6.1 release notes
  docs/releases/6.1.md
Labels: Documentation

#11833 Fix timezone handling in timesince_last_update
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
Labels: type:Bug

#11841 Add re_path to imports in routablepage.md
  docs/reference/contrib/routablepage.md
Labels: Documentation

#11853 Add ability to make keyboard shortcut Global
  CHANGELOG.txt
  client/src/controllers/KeyboardController.test.js
  client/src/controllers/KeyboardController.ts
  docs/releases/6.1.md
  wagtail/admin/templates/wagtailadmin/pages/action_menu/save_draft.html
  wagtail/admin/templates/wagtailadmin/panels/publishing/schedule_publishing_panel.html
  wagtail/admin/templates/wagtailadmin/shared/side_panel_toggle.html
  wagtail/admin/templates/wagtailadmin/workflows/create.html
  wagtail/admin/templates/wagtailadmin/workflows/create_task.html
  wagtail/admin/templates/wagtailadmin/workflows/edit.html
  wagtail/admin/templates/wagtailadmin/workflows/edit_task.html
  wagtail/snippets/templates/wagtailsnippets/snippets/action_menu/publish.html
  wagtail/snippets/templates/wagtailsnippets/snippets/action_menu/save.html
Labels: Accessibility, component:Stimulus

#11854 Support forwards compatible configuration for private pages/collections
  docs/advanced_topics/privacy.md
  docs/reference/settings.md
  wagtail/admin/forms/collections.py
  wagtail/admin/forms/pages.py
  wagtail/admin/tests/test_privacy.py
  wagtail/documents/tests/test_collection_privacy.py
Labels: status:Needs Review, Release blocker, component:Privacy

#11749 Accept alias for WAGTAILIMAGES_RENDITION_STORAGE
  docs/reference/settings.md
  wagtail/images/models.py
  wagtail/images/tests/test_models.py
Labels: status:Needs Review, component:Images

#11737 Update page routing, add tests
  wagtail/models/__init__.py
  wagtail/tests/test_page_model.py
Labels: component:Routing, 🚀 Performance, status:Ready to merge

#11863 Tweak styles for w-header-button to better match the designs
  CHANGELOG.txt
  client/scss/components/_button.scss
  docs/releases/6.1.md
  wagtail/admin/templates/wagtailadmin/pages/page_listing_header.html
  wagtail/admin/templates/wagtailadmin/shared/headers/slim_header.html
  wagtail/admin/tests/pages/test_page_usage.py
  wagtail/admin/widgets/button.py
Labels: component:Design system, component:Universal listings

#11878 Add third party tutorials Q1 2024
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation

#11873 Fix issue where allow unicode slugs was not correctly used for urlify (5.2)
  client/src/controllers/SlugController.test.js
  client/src/utils/text.ts
Labels: status:Needs Review, javascript

#11886 Update "integrating into Django" docs to emphasise creating page models
  CHANGELOG.txt
  docs/getting_started/integrating_into_django.md
  docs/releases/6.1.md
Labels: Documentation

#11893 Add missing promote tab to ObjectList permission example
  docs/advanced_topics/customisation/page_editing_interface.md
Labels: Documentation

#11899 Downgrade 'Unable to find purge backend' messages to info
  wagtail/contrib/frontend_cache/tests.py
  wagtail/contrib/frontend_cache/utils.py
Labels: component:Frontend cache

#11907 Use `DjangoJSONEncoder` instead of custom `LazyStringEncoder`
  CHANGELOG.txt
  docs/releases/6.2.md
  wagtail/admin/rich_text/editors/draftail/__init__.py
Labels: type:Cleanup/Optimisation
