Repository wagtail/wagtail, pull requests merged in 2024-07, with the labels that each got.

#11965 Add admin urls to docs - #11963
  CHANGELOG.txt
  docs/extending/admin_views.md
  docs/releases/6.2.md
Labels: Documentation

#11672 Document the vary_fields property for custom image filters
  CHANGELOG.txt
  docs/extending/custom_image_filters.md
  docs/releases/6.2.md
Labels: Documentation, component:Images

#12108 Move sprite hashing out of module import time
  CHANGELOG.txt
  docs/releases/6.2.md
  wagtail/admin/icons.py
  wagtail/admin/templates/wagtailadmin/skeleton.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_icon_sprite.py
  wagtail/admin/urls/__init__.py
  wagtail/admin/views/home.py
Labels: 🚀 Performance

#12058 Add content metrics board
  CHANGELOG.txt
  client/src/entrypoints/admin/preview-panel.js
  client/src/includes/contentMetrics.test.ts
  client/src/includes/contentMetrics.ts
  client/src/includes/previewPlugin.ts
  client/src/includes/userbar.ts
  docs/releases/6.2.md
  tsconfig.json
  wagtail/admin/templates/wagtailadmin/shared/side_panels/checks.html
Labels: type:Enhancement, component:Page

#12119 Add underscore as an alt text antipattern
  client/src/includes/a11y-result.test.ts
  client/src/includes/a11y-result.ts
  docs/advanced_topics/accessibility_considerations.md
  docs/releases/6.2.md
  wagtail/admin/tests/test_userbar.py
  wagtail/admin/userbar.py
Labels: type:Enhancement, Accessibility

#12090 Content checks design upgrade: help text and separate cards
  CHANGELOG.txt
  client/scss/components/_a11y-result.scss
  client/src/entrypoints/admin/preview-panel.js
  client/src/includes/a11y-result.ts
  client/src/includes/userbar.ts
  docs/releases/6.2.md
  wagtail/admin/templates/wagtailadmin/shared/side_panels/checks.html
  wagtail/admin/templates/wagtailadmin/userbar/item_accessibility.html
  wagtail/admin/tests/test_userbar.py
  wagtail/admin/userbar.py
Labels: type:Enhancement, component:Page

#12140 Downgrade minimum version of Sphinx for Python 3.8 compatibility
  docs/Makefile
  setup.py
Labels: type:Cleanup/Optimisation

#12136 Language label fine-tunes
  client/scss/components/_status-tag.scss
Labels: type:Enhancement

#12148 Fix no-index directive for Sphinx 7.4.7
  docs/reference/pages/panels.md
Labels: Documentation, type:Cleanup/Optimisation

#12165 Remove note about database search not ordering by relevance
  docs/topics/search/searching.md
Labels: Documentation, component:Search

#12168 Prevent deconstruct_with_lookup from breaking on ListBlock subclasses with custom constructors
  wagtail/blocks/list_block.py
  wagtail/tests/test_streamfield.py
Labels: type:Bug, component:Streamfield

#12166 Ensure "Save schedule" button also trigger the overwrite confirmation dialog
  client/src/controllers/SessionController.test.js
  client/src/controllers/SessionController.ts
Labels: type:Bug

#12182 Do not suggest using the custom user model's app config as the custom wagtail.users app config
  docs/advanced_topics/customisation/custom_user_models.md
  docs/extending/customizing_group_views.md
Labels: Documentation
