Repository wagtail/wagtail, pull requests merged in 2024-10, with the labels that each got.

#12376 Updated JPG file to fix issue (email header logo usage)
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.3.md
  wagtail/admin/static_src/wagtailadmin/images/email-header.jpg
Labels: component:Design system, component:Notifications

#12315 Remove multi-line icon comments
  CHANGELOG.txt
  docs/releases/6.3.md
  wagtail/admin/icons.py
  wagtail/admin/tests/test_icon_sprite.py
Labels: 🚀 Performance, component:Icons

#12378 Clean up JSDoc on Slugify
  client/src/utils/slugify.ts
Labels: type:Cleanup/Optimisation, status:Needs Review, javascript

#12385 Fix `BulkController` example code in JSDoc
  client/src/controllers/BulkController.ts
Labels: javascript, component:Stimulus

#12383 Use correct `ACTIVE_CONTENT_LOCALE` name in wagtailConfig stubs
  client/src/config/wagtailConfig.test.js
  client/tests/stubs.js
Labels: type:Cleanup/Optimisation, javascript

#12360 Deprecate `window.wagtailConfig.BULK_ACTION_ITEM_TYPE` usage in JS
  CHANGELOG.txt
  client/src/includes/bulk-actions.js
  client/src/includes/bulk-actions.test.js
  docs/releases/6.3.md
  wagtail/admin/templates/wagtailadmin/bulk_actions/footer.html
  wagtail/admin/templates/wagtailadmin/pages/listing.html
  wagtail/documents/templates/wagtaildocs/documents/index.html
  wagtail/images/templates/wagtailimages/images/index.html
  wagtail/snippets/templates/wagtailsnippets/snippets/index.html
  wagtail/users/templates/wagtailusers/users/index.html
Labels: status:Needs Review, javascript, component:Bulk Actions

#12361 Remove `window.fileupload_opts` global usage, use data attributes instead
  CHANGELOG.txt
  docs/releases/6.3.md
  wagtail/documents/static_src/wagtaildocs/js/add-multiple.js
  wagtail/documents/templates/wagtaildocs/multiple/add.html
  wagtail/images/static_src/wagtailimages/js/add-multiple.js
  wagtail/images/templates/wagtailimages/multiple/add.html
Labels: type:Cleanup/Optimisation, component:Images, component:Documents, javascript

#12382 Remove image_format_name_to_content_type function
  wagtail/images/fields.py
  wagtail/images/models.py
Labels: type:Cleanup/Optimisation, component:Images

#12403 Add support for Python 3.13
  .github/workflows/test.yml
  CHANGELOG.txt
  README.md
  docs/releases/6.3.md
  docs/releases/upgrading.md
  setup.py
  tox.ini
Labels: type:Cleanup/Optimisation

#12395 Ensure form is always dirty after doing edits when `forceValue` is `true`
  client/src/controllers/UnsavedController.test.js
  client/src/controllers/UnsavedController.ts
Labels: component:Page, javascript, component:Stimulus

#11792 Addition of new "description" property to AbstractImage class
  CHANGELOG.txt
  docs/releases/6.3.md
  wagtail/images/migrations/0027_image_description.py
  wagtail/images/models.py
  wagtail/images/templates/wagtailimages/multiple/add.html
  wagtail/images/tests/test_models.py
  wagtail/images/tests/test_signal_handlers.py
  wagtail/images/tests/tests.py
  wagtail/test/testapp/migrations/0043_customimage_description.py
Labels: type:Enhancement, component:Images, Accessibility

#11533 Ensure that TypedTableBlock uses the correct API representations of child blocks
  CHANGELOG.txt
  docs/releases/6.3.md
  wagtail/contrib/typed_table_block/blocks.py
  wagtail/contrib/typed_table_block/tests.py
Labels: type:Bug, status:Needs Review, component:Streamfield, component:API

#12233 Incremental dashboard enhancements. Fix #12089
  CHANGELOG.txt
  client/scss/components/_avatar.scss
  client/scss/components/_header.scss
  client/scss/components/_indicator.scss
  client/scss/components/_listing.scss
  client/scss/components/_panel.scss
  client/scss/components/_status-tag.scss
  client/scss/components/_summary.scss
  client/scss/core.scss
  client/scss/layouts/_home.scss
  client/src/tokens/colorThemes.js
  client/src/tokens/colorVariables.test.js
  client/tests/integration/homepage.test.js
  docs/releases/6.3.md
  wagtail/admin/site_summary.py
  wagtail/admin/templates/wagtailadmin/home.html
  wagtail/admin/templates/wagtailadmin/home/account_summary.html
  wagtail/admin/templates/wagtailadmin/home/locked_pages.html
  wagtail/admin/templates/wagtailadmin/home/recent_edits.html
  wagtail/admin/templates/wagtailadmin/home/site_summary_pages.html
  wagtail/admin/templates/wagtailadmin/home/upgrade_notification.html
  wagtail/admin/templates/wagtailadmin/home/user_objects_in_workflow_moderation.html
  wagtail/admin/templates/wagtailadmin/home/workflow_objects_to_moderate.html
  wagtail/admin/templates/wagtailadmin/pages/listing/_locked_indicator.html
  wagtail/admin/templates/wagtailadmin/shared/avatar.html
  wagtail/admin/templates/wagtailadmin/shared/header.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/pages/test_explorer_view.py
  wagtail/admin/tests/test_dashboard.py
  wagtail/admin/tests/test_reports_views.py
  wagtail/admin/tests/test_site_summary.py
  wagtail/admin/tests/tests.py
  wagtail/admin/views/home.py
  wagtail/documents/templates/wagtaildocs/homepage/site_summary_documents.html
  wagtail/documents/tests/test_site_summary.py
  wagtail/images/templates/wagtailimages/homepage/site_summary_images.html
  wagtail/images/tests/test_site_summary.py
Labels: type:Enhancement, component:Dashboard

#12366 View draft - support different preview modes #6574
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.3.md
  wagtail/admin/tests/pages/test_view_draft.py
  wagtail/admin/views/pages/preview.py
  wagtail/test/testapp/models.py
Labels: status:Needs Review, component:Preview

#12348 'Prefers-contrast' admin theming
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/scss/components/_a11y-result.scss
  client/scss/components/_button.scss
  client/scss/components/_chooser.scss
  client/scss/components/_dropdown.scss
  client/scss/components/_filters.scss
  client/scss/components/_form-side.scss
  client/scss/components/_header.scss
  client/scss/components/_messages.scss
  client/scss/components/_panel.scss
  client/scss/components/_preview-panel.scss
  client/scss/components/forms/_input-base.scss
  client/scss/tools/_mixins.general.scss
  client/src/components/CommentApp/components/Comment/style.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  client/src/components/Draftail/Draftail.scss
  client/src/components/Minimap/CollapseAll.scss
  client/src/components/Minimap/MinimapItem.scss
  client/src/components/Sidebar/Sidebar.scss
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/Sidebar/__snapshots__/Sidebar.test.js.snap
  client/src/tokens/colorThemes.js
  client/src/tokens/colorVariables.test.js
  client/src/tokens/colors.js
  client/tailwind.config.js
  docs/releases/6.3.md
  wagtail/admin/forms/account.py
  wagtail/admin/templates/wagtailadmin/pages/listing/_page_header_buttons.html
  wagtail/admin/templates/wagtailadmin/shared/headers/slim_header.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_account_management.py
  wagtail/admin/tests/test_audit_log.py
  wagtail/admin/tests/test_views.py
  wagtail/users/migrations/0014_userprofile_contrast.py
  wagtail/users/models.py
Labels: type:Enhancement, Accessibility, component:Design system

#12416 ImageBlock for StreamField (rebase of #11791)
  CHANGELOG.txt
  client/src/entrypoints/images/image-block.js
  client/webpack.config.js
  docs/reference/streamfield/blocks.md
  docs/releases/6.3.md
  docs/topics/streamfield.md
  docs/tutorial/create_portfolio_page.md
  wagtail/api/v2/tests/test_pages.py
  wagtail/blocks/field_block.py
  wagtail/images/blocks.py
  wagtail/images/models.py
  wagtail/images/templates/wagtailimages/widgets/image.html
  wagtail/images/tests/test_blocks.py
  wagtail/images/tests/test_models.py
  wagtail/test/testapp/migrations/0045_alter_streampage_body.py
  wagtail/test/testapp/models.py
  wagtail/tests/test_blocks.py
Labels: type:Enhancement, component:Streamfield, component:Images

#12387 Fix: Updated can_handle method to check for AbstractGroupApprovalTask in mail.py file
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.3.md
  wagtail/admin/mail.py
Labels: component:Workflow, component:Notifications

#12450 Add clarification on using versionadded / versionchanged directives
  docs/contributing/documentation_guidelines.md
Labels: Documentation

#12460 Replace X links with Mastodon
  README.md
  docs/support.md
Labels: Documentation

#12442 Documentation - Add recent third party tutorials
  docs/advanced_topics/third_party_tutorials.md
Labels: Documentation

#12471 Refactor headings to follow Google Developer Style Guide
  CHANGELOG.txt
  docs/advanced_topics/api/v2/configuration.md
  docs/advanced_topics/api/v2/usage.md
  docs/advanced_topics/customisation/index.md
  docs/advanced_topics/images/feature_detection.md
  docs/advanced_topics/reference_index.md
  docs/deployment/under_the_hood.md
  docs/extending/extending_draftail.md
  docs/releases/5.0.md
  docs/releases/6.4.md
Labels: Documentation, status:Needs Review

#12322 Fix StreamValue._prefetch_blocks() to skip manually inserted items
  CHANGELOG.txt
  docs/releases/6.4.md
  wagtail/blocks/stream_block.py
  wagtail/tests/test_streamfield.py
Labels: component:Streamfield

#12374 Bugfix: Closed opened files as a coding standard
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.4.md
  wagtail/utils/setup.py
Labels: type:Cleanup/Optimisation

#12346 Add the ability to apply basic query optimisations to specific() subqueries
  CHANGELOG.txt
  docs/reference/pages/queryset_reference.md
  docs/releases/6.4.md
  wagtail/query.py
  wagtail/test/testapp/fixtures/test_specific.json
  wagtail/tests/test_page_queryset.py
Labels: component:Page, 🚀 Performance

#12472 Increase DATA_UPLOAD_MAX_NUMBER_FIELDS in project template
  docs/getting_started/integrating_into_django.md
  docs/releases/6.4.md
  wagtail/project_template/project_name/settings/base.py
Labels: Documentation, DX

#12438 Update Python docstrings in core models for better code formatting in model reference
  CHANGELOG.txt
  docs/reference/models.md
  docs/releases/6.4.md
  wagtail/models/__init__.py
  wagtail/models/i18n.py
  wagtail/models/sites.py
Labels: Documentation

#12478 Docs - Align spelling of 'subpages' to be consistent with rest of docs
  CHANGELOG.txt
  docs/advanced_topics/privacy.md
  docs/releases/0.8.rst
  wagtail/admin/userbar.py
Labels: Documentation

#12477 Improved doc according to US style
  CHANGELOG.txt
  SPONSORS.md
  docs/advanced_topics/customization/admin_templates.md
  docs/advanced_topics/customization/custom_page_listings.md
  docs/advanced_topics/customization/custom_user_models.md
  docs/advanced_topics/customization/index.md
  docs/advanced_topics/customization/page_editing_interface.md
  docs/advanced_topics/customization/streamfield_blocks.md
  docs/advanced_topics/embeds.md
  docs/advanced_topics/images/image_file_formats.md
  docs/advanced_topics/index.md
  docs/extending/custom_tasks.md
  docs/extending/forms.md
  docs/reference/contrib/settings.md
  docs/reference/contrib/sitemaps.md
  docs/reference/panels.md
  docs/releases/1.0.rst
  docs/releases/1.3.rst
  docs/releases/1.4.rst
  docs/releases/1.5.rst
  docs/releases/1.8.rst
  docs/releases/1.9.rst
  docs/releases/2.12.rst
  docs/releases/2.13.3.rst
  docs/releases/2.13.rst
  docs/releases/2.14.rst
  docs/releases/4.1.md
  docs/releases/6.0.md
  docs/releases/6.2.md
  docs/releases/6.4.md
  docs/topics/images.md
  docs/topics/pages.md
Labels: Documentation

#12490 Added formats(epub, pdf, htmlzip) to .readthedocs.yml
  .readthedocs.yml
  CHANGELOG.txt
  docs/releases/6.4.md
Labels: Documentation, status:Needs Review

#12510 Update `CloneController` - added/cleared events should not be cancelable
  client/src/controllers/CloneController.ts
Labels: type:Cleanup/Optimisation, javascript, component:Stimulus
