Repository wagtail/wagtail, pull requests merged in 2024-08, with the labels that each got.

#12215 Formalise support for Django 5.1
  .github/workflows/test.yml
  CHANGELOG.txt
  README.md
  docs/getting_started/integrating_into_django.md
  docs/releases/6.3.md
  docs/releases/upgrading.md
  setup.py
  tox.ini
  wagtail/project_template/requirements.txt
Labels: type:Cleanup/Optimisation

#12237 Allow users with edit access to pages / snippets via workflows to access ping endpoint
  wagtail/admin/tests/test_editing_sessions.py
  wagtail/admin/views/editing_sessions.py
Labels: type:Bug, component:Workflow

#12258 Prevent versioned_static failure when INSTALLED_APPS is a tuple
  wagtail/admin/staticfiles.py
Labels: type:Bug

#12263 Update NPM packages (minor only)
  package-lock.json
  package.json
Labels: status:Needs Review, javascript

#12265 Docs - Formatting / white-space clean up
  docs/advanced_topics/accessibility_considerations.md
  docs/advanced_topics/customisation/custom_page_listings.md
  docs/advanced_topics/deploying.md
  docs/reference/hooks.md
  docs/reference/management_commands.md
  docs/reference/pages/model_reference.md
  docs/releases/6.2.md
  docs/topics/images.md
  docs/tutorial/deployment.md
Labels: Documentation
