Repository wagtail/wagtail, pull requests merged in 2024-03, with the labels that each got.

#11712 More detailed release note about move of Query model
  docs/releases/6.0.md
Labels: Documentation

#11708 Remove extraneous padding in chooser modal listings
  CHANGELOG.txt
  client/scss/components/_listing.scss
  docs/releases/6.1.md
Labels: component:Choosers

#11697 Fix date formatting in mails
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.1.md
  wagtail/contrib/forms/models.py
  wagtail/contrib/forms/tests/test_models.py
Labels: component:Form builder, component:UI localization

#11724 Update universal listings & UI table unit tests to be more robust
  wagtail/admin/tests/viewsets/test_model_viewset.py
  wagtail/snippets/tests/test_viewset.py
Labels: type:Cleanup/Optimisation, component:Universal listings

#11725 Ensure unit tests for preview links are more robust
  wagtail/admin/tests/pages/test_preview.py
Labels: type:Cleanup/Optimisation, component:Preview

#11714 fix: MutationObserver in dirty form check only tests direct descendants
  CHANGELOG.txt
  client/src/controllers/UnsavedController.test.js
  client/src/controllers/UnsavedController.ts
  docs/releases/6.1.md
Labels: component:Page, javascript, component:Stimulus

#11754 (6.0.2) Backport - Move modal-workflow.js script to admin_base.html (#11620)
  CHANGELOG.txt
  docs/releases/6.0.2.md
  wagtail/admin/templates/wagtailadmin/admin_base.html
  wagtail/admin/templates/wagtailadmin/collections/edit.html
  wagtail/admin/templates/wagtailadmin/home/workflow_objects_to_moderate.html
  wagtail/admin/templates/wagtailadmin/pages/_editor_js.html
  wagtail/admin/templates/wagtailadmin/pages/index.html
  wagtail/admin/tests/viewsets/test_model_viewset.py
  wagtail/sites/templates/wagtailsites/create.html
  wagtail/sites/templates/wagtailsites/edit.html
  wagtail/users/templates/wagtailusers/groups/includes/group_form_js.html
Labels: status:Needs Review, component:Snippets, component:Choosers, component:Viewsets

#11124 make locale-switcher scrollable
  CHANGELOG.txt
  client/scss/components/_dropdown.scss
  docs/releases/6.1.md
Labels: status:Needs Review, component:UI localization

#11772 Fix title of page for UI guidelines
  docs/contributing/ui_guidelines.md
Labels: Documentation

#11213 Minimap - Ensure that we correctly handle no data-panel found scenarios
  client/src/components/Minimap/Minimap.tsx
Labels: component:Page, javascript

#11214 SwapController - Ensure untrusted data sources are logged correctly
  CHANGELOG.txt
  client/src/controllers/SwapController.test.js
  client/src/controllers/SwapController.ts
  docs/releases/6.1.md
Labels: component:Security, javascript, component:Stimulus

#11787 Docs - Add additional reference to `wagtail_update_image_renditions` command
  CHANGELOG.txt
  docs/advanced_topics/images/renditions.md
  docs/releases/6.1.md
Labels: Documentation, component:Images

#11766 Use `default_manager` instead of `objects` in `ModelIndexView`
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/snippets/views/snippets.py
  wagtail/test/testapp/migrations/0035_modelwithcustommanager.py
  wagtail/test/testapp/models.py
Labels: type:Bug, component:Snippets, status:Ready to merge

#11747 Fix dummy request SERVER_NAME when running tests
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.1.md
  wagtail/coreutils.py
  wagtail/tests/test_utils.py
Labels: type:Cleanup/Optimisation

#11804 Bump minimum version of djangorestframework to 3.15.1
  CHANGELOG.txt
  docs/releases/6.1.md
  setup.py
Labels: Compatibility

#11803 Add `_editor_js.html` include to `wagtailadmin/generic/form.html`
  CHANGELOG.txt
  docs/releases/6.1.md
  wagtail/admin/templates/wagtailadmin/generic/form.html
  wagtail/admin/tests/viewsets/test_model_viewset.py
  wagtail/snippets/templates/wagtailsnippets/snippets/create.html
  wagtail/snippets/templates/wagtailsnippets/snippets/edit.html
  wagtail/users/templates/wagtailusers/users/create.html
  wagtail/users/templates/wagtailusers/users/edit.html
Labels: type:Bug, component:Panels, component:Viewsets

#11588 Add support for related fields in generic `IndexView.list_display`
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/releases/6.1.md
  wagtail/admin/ui/tables/__init__.py
  wagtail/admin/views/generic/models.py
  wagtail/snippets/tests/test_viewset.py
  wagtail/test/testapp/migrations/0023_snippetchoosermodel_full_featured.py
  wagtail/test/testapp/models.py
  wagtail/test/testapp/wagtail_hooks.py
Labels: component:Snippets, status:Ready to merge, component:Viewsets
