Repository wagtail/wagtail, pull requests merged in 2024-06, with the labels that each got.

#12031 Add mention of html5lib in upgrade considerations
  docs/releases/6.1.md
Labels: component:Rich text, Compatibility, DX

#11979 Skip ChooseParentView if only one possible valid parent page available
  CHANGELOG.txt
  docs/releases/6.2.md
  wagtail/admin/tests/pages/test_parent_page_chooser_view.py
  wagtail/admin/views/pages/choose_parent.py
Labels: status:Ready to merge

#12019 Content checks results redesign
  client/scss/components/_a11y-result.scss
  client/scss/components/_userbar.scss
  client/src/components/CommentApp/main.scss
  client/src/tokens/typography.js
  wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html
  wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
  wagtail/admin/templates/wagtailadmin/shared/side_panels/checks.html
Labels: type:Enhancement, component:Preview

#12010 Language label redesign - admin listings
  CHANGELOG.txt
  client/scss/components/_status-tag.scss
  client/src/tokens/colorThemes.js
  client/src/tokens/colorVariables.test.js
  client/src/tokens/colors.js
  docs/_static/wagtail_colors_tables.txt
  docs/releases/6.2.md
Labels: type:Enhancement, component:i18n, component:Design system, component:Universal listings

#11986 Add alt text validation rule in the accessibility checker
  CHANGELOG.txt
  client/src/entrypoints/admin/preview-panel.js
  client/src/includes/a11y-result.test.ts
  client/src/includes/a11y-result.ts
  client/src/includes/userbar.ts
  docs/advanced_topics/accessibility_considerations.md
  docs/releases/6.2.md
  wagtail/admin/tests/test_userbar.py
  wagtail/admin/userbar.py
Labels: Accessibility, component:Userbar

#12065 Add a `deactivate` method to ProgressController
  CHANGELOG.txt
  client/src/controllers/ProgressController.test.js
  client/src/controllers/ProgressController.ts
  docs/releases/6.2.md
Labels: type:Enhancement, javascript, component:Stimulus
