Repository wagtail/wagtail, pull requests merged in 2025-03, with the labels that each got.

#12954 Fix up `stubs` & `adapter` contents to better support Jest testing
  CHANGELOG.txt
  client/tests/adapter.js
  client/tests/stubs.js
  docs/releases/6.5.md
Labels: type:Cleanup/Optimisation, javascript

#12961 Fix nondeterministic page order in test_ordering_by_content_type
  wagtail/admin/tests/pages/test_explorer_view.py
Labels: status:Ready to merge

#12971 Docs - Minor whitespace cleanup
  docs/advanced_topics/add_to_django_project.md
  docs/topics/streamfield.md
Labels: Documentation, type:Cleanup/Optimisation

#12448 Frontend cache: Fix n+1 query issues when batch purging page urls
  wagtail/contrib/frontend_cache/tests.py
  wagtail/contrib/frontend_cache/utils.py
Labels: component:Frontend cache, 🚀 Performance

#12946 Document that request_or_site is optional on BaseGenericSetting.load
  CHANGELOG.txt
  docs/reference/contrib/settings.md
  docs/releases/6.5.md
Labels: Documentation, status:Needs Review, component:Settings

#12977 Make GitHub highlight html files as Django templates
  .gitattributes
  CHANGELOG.txt
  docs/releases/6.5.md
Labels: status:Needs Review, Infrastructure, DX

#12978 Ignore AVIF deprecation in pillow-heif
  .github/workflows/test.yml
Labels: status:Needs Review, component:Images, Infrastructure

#12987 Fix typo in preview blocks documentation
  docs/topics/streamfield.md
Labels: type:Bug, Documentation

#12990 Ensure ImproperlyConfigured is thrown from db_field on unbound FieldPanels as intended
  CHANGELOG.txt
  docs/releases/6.5.md
  wagtail/admin/panels/field_panel.py
  wagtail/admin/tests/test_edit_handlers.py
Labels: type:Bug, status:Needs Review
