Repository wagtail/wagtail, pull requests merged in 2025-02, with the labels that each got.

#12838 Ensure block preview is hidden when the user clears out the search input
  client/src/components/ComboBox/ComboBox.tsx
Labels: type:Bug, component:Streamfield

#12639 Add Wagtail prefix to non-taggit settings
  CHANGELOG.txt
  docs/reference/settings.md
  docs/releases/6.5.md
  wagtail/admin/tests/test_widgets.py
  wagtail/admin/views/tags.py
  wagtail/admin/widgets/tags.py
Labels: type:Cleanup/Optimisation, component:Tagging

#11075 Take preferred language into account in JavaScriptCatalog view
  CHANGELOG.txt
  docs/releases/6.5.md
  wagtail/admin/auth.py
  wagtail/admin/localization.py
  wagtail/admin/tests/test_views.py
  wagtail/admin/urls/__init__.py
  wagtail/admin/views/i18n.py
Labels: status:Needs Review, component:UI localization, javascript

#12864 Include Python version in CircleCI cache key
  .circleci/config.yml
Labels: Infrastructure

#12863 Fix Garbled word order in GraphQL downsides section
  CHANGELOG.txt
  CONTRIBUTORS.md
  docs/advanced_topics/headless.md
  docs/releases/6.5.md
Labels: Documentation, Headless

#12733 resolved mixed declarations - Closes #12720
  .stylelintrc.js
  CHANGELOG.txt
  CONTRIBUTORS.md
  client/scss/components/_a11y-result.scss
  client/scss/components/_button.scss
  client/scss/components/_chooser.scss
  client/scss/components/_filters.scss
  client/scss/components/_grid.legacy.scss
  client/scss/components/_panel.scss
  client/scss/components/_tag.scss
  client/scss/components/_workflow-timeline.scss
  client/scss/components/forms/_field-textoutput.scss
  client/scss/components/forms/_input-base.scss
  client/scss/components/forms/_input-text.scss
  client/scss/components/forms/_nested-panel.scss
  client/scss/components/forms/_radio-checkbox.scss
  client/scss/components/forms/_select.scss
  client/scss/layouts/_login.scss
  client/scss/layouts/_report.scss
  client/src/components/ComboBox/ComboBox.scss
  client/src/components/CommentApp/components/Comment/style.scss
  client/src/components/CommentApp/components/CommentHeader/style.scss
  client/src/components/Draftail/Draftail.scss
  client/src/components/Minimap/CollapseAll.scss
  client/src/components/Sidebar/Sidebar.scss
  docs/releases/6.5.md
Labels: type:Cleanup/Optimisation, Compatibility, component:Design system

#12540 NPM package updates; `downshift`, `focus-trap-react`, `immer`, `redux`, `uuid`
  CHANGELOG.txt
  client/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
  client/src/components/CommentApp/components/Comment/index.stories.tsx
  client/src/components/CommentApp/components/CommentReply/index.stories.tsx
  client/src/components/CommentApp/main.tsx
  client/src/components/CommentApp/state/comments.test.ts
  client/src/components/CommentApp/state/comments.ts
  client/src/components/CommentApp/state/settings.ts
  client/src/components/PageExplorer/PageExplorer.test.js
  client/src/components/PageExplorer/actions.test.js
  client/src/components/PageExplorer/index.tsx
  client/src/components/StreamField/blocks/__snapshots__/StreamBlock.test.js.snap
  docs/releases/6.5.md
  package-lock.json
  package.json
Labels: status:Needs Review, Compatibility, javascript

#12847 Fix invisible nested menu items
  CHANGELOG.txt
  client/src/components/Sidebar/SidebarPanel.scss
  docs/releases/6.5.md
Labels: type:Bug, component:Menu, status:Ready to merge

#12901 Relax upper bounds of django-taggit (<7) and beautifulsoup (<5)
  setup.py
Labels: type:Cleanup/Optimisation

#12869 Force preview panel scroll behavior to instant to avoid flickering
  client/src/controllers/PreviewController.test.js
  client/src/controllers/PreviewController.ts
Labels: type:Bug, component:Preview

#12830 Validate against invalid characters in Lexeme values
  CHANGELOG.txt
  docs/releases/6.5.md
  wagtail/search/backends/database/mysql/query.py
  wagtail/search/tests/test_mysql_backend.py
Labels: type:Cleanup/Optimisation, component:Search
