Repository wagtail/wagtail, pull requests merged in 2025-08, with the labels that each got.

#13283 Refresh accessibility targets in contributing docs
  CHANGELOG.txt
  docs/contributing/developing.md
  docs/releases/7.1.md
Labels: Documentation, Accessibility

#13301 Replace myst_url_schemes links with relative external links
  docs/extending/editor_api.md
  docs/extending/extending_client_side.md
  docs/reference/ui/components.md
Labels: type:Bug, Documentation, Release blocker

#13319 Add example to `CountController` for class name & min count
  client/src/controllers/CountController.ts
Labels: Documentation, component:Stimulus

#13340 Updated missing link on an article on advanced topics docs to point to the new website
  docs/advanced_topics/i18n.md
Labels: Documentation

#13322 docs: getting_started-tutorial remove unused imports
  docs/getting_started/tutorial.md
Labels: Documentation

#13335 Add support for `attrs` in `formattedfield` tag
  CHANGELOG.txt
  docs/releases/7.2.md
  wagtail/admin/templates/wagtailadmin/shared/formatted_field.html
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_templatetags.py
Labels: status:Needs Review

#13329 Added shortcut to open keyboard shortcut dialog
  CHANGELOG.txt
  docs/releases/7.2.md
  wagtail/admin/templatetags/wagtailadmin_tags.py
  wagtail/admin/tests/test_keyboard_shortcuts.py
  wagtail/admin/wagtail_hooks.py
Labels: Accessibility, GSOC, component: Keyboard shortcuts
